= Reference
:mrdocs:

[#index]
== Global namespace

=== Namespaces

[cols=1]
|===
| Name
| link:#A[`A`] 
|===

=== Types

[cols=1]
|===
| Name
| link:#F[`F`] 
|===

=== Functions

[cols=2]
|===
| Name
| Description
| link:#f0[`f0`] 
| 
| link:#f5[`f5`] 
| See link:#A-f1[`A&colon;&colon;f1`]
| link:#f6[`f6`] 
| See link:#F-operator_bitnot[`F&colon;&colon;operator&#126;`]
|===

[#A]
== A

=== Types

[cols=2]
|===
| Name
| Description
| link:#A-B[`B`] 
| See link:#A-f1[`f1`]
| link:#A-C[`C`] 
| 
| link:#A-D[`D`] 
| 
|===

=== Functions

[cols=2]
|===
| Name
| Description
| link:#A-f1[`f1`] 
| See link:#f0[`f0`]
|===

[#A-B]
== link:#A[A]::B

See link:#A-f1[`f1`]

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename&gt;
struct B;
----

=== Member Functions

[cols=1]
|===
| Name
| link:#A-B-f2[`f2`] 
|===

=== Description

See link:#A-f1[`A&colon;&colon;f1`]

See link:#A-f1[`&colon;&colon;A&colon;&colon;f1`]

[#A-B-f2]
== link:#A[A]::link:#A-B[B]::f2

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f2();
----

[#A-C]
== link:#A[A]::C

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----

=== Member Functions

[cols=1]
|===
| Name
| link:#A-C-f3[`f3`] 
| link:#A-C-f4[`f4`] 
|===

=== Derived Classes

[cols=2]
|===
| Name
| Description
| link:#A-D[`D`]
| 
|===

[#A-C-f3]
== link:#A[A]::link:#A-C[C]::f3

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f3();
----

[#A-C-f4]
== link:#A[A]::link:#A-C[C]::f4

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f4();
----

[#A-D]
== link:#A[A]::D

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct D
    : link:#A-C[C]
----

=== Base Classes

[cols=2]
|===
| Name
| Description
| `link:#A-C[C]`
| 
|===

=== Types

[cols=2]
|===
| Name
| Description
| link:#A-D-E[`E`] 
| See link:#A-C-f3[`f3`]
|===

=== Member Functions

[cols=1]
|===
| Name
| link:#A-C-f3[`f3`] 
| link:#A-D-f4[`f4`] 
|===

[#A-D-E]
== link:#A[A]::link:#A-D[D]::E

See link:#A-C-f3[`f3`]

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct E;
----

=== Description

See link:#A-D-f4[`f4`]

See link:#A-C-f4[`C&colon;&colon;f4`]

[#A-D-f4]
== link:#A[A]::link:#A-D[D]::f4

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f4();
----

[#A-f1]
== link:#A[A]::f1

See link:#f0[`f0`]

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f1();
----

=== Description

See link:#f0[`&colon;&colon;f0`]

[#F]
== F

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct F;
----

=== Member Functions

[cols=1]
|===
| Name
| link:#F-operator_assign[`operator&equals;`] 
| link:#F-operator_mod[`operator%`] 
| link:#F-operator_mod_eq[`operator%&equals;`] 
| link:#F-operator_bitand[`operator&amp;`] 
| link:#F-operator_and[`operator&amp;&amp;`] 
| link:#F-operator_and_eq[`operator&amp;&equals;`] 
| link:#F-operator_call[`operator()`] 
| link:#F-operator_star[`operator&ast;`] 
| link:#F-operator_star_eq[`operator&ast;&equals;`] 
| link:#F-operator_plus[`operator&plus;`] 
| link:#F-operator_inc[`operator&plus;&plus;`] 
| link:#F-operator_plus_eq[`operator&plus;&equals;`] 
| link:#F-operator_comma[`operator,`] 
| link:#F-operator_minus[`operator&hyphen;`] 
| link:#F-operator_dec[`operator&hyphen;&hyphen;`] 
| link:#F-operator_minus_eq[`operator&hyphen;&equals;`] 
| link:#F-operator_ptr[`operator&hyphen;&gt;`] 
| link:#F-operator_ptrmem[`operator&hyphen;&gt;&ast;`] 
| link:#F-operator_slash[`operator&sol;`] 
| link:#F-operator_slash_eq[`operator&sol;&equals;`] 
| link:#F-operator_lshift_eq[`operator&lt;&lt;&equals;`] 
| link:#F-operator_rshift[`operator&gt;&gt;`] 
| link:#F-operator_rshift_eq[`operator&gt;&gt;&equals;`] 
| link:#F-operator_subs[`operator&lsqb;&rsqb;`] 
| link:#F-operator_xor[`operator&circ;`] 
| link:#F-operator_xor_eq[`operator&circ;&equals;`] 
| link:#F-operator_bitor[`operator&verbar;`] 
| link:#F-operator_or_eq[`operator&verbar;&equals;`] 
| link:#F-operator_or[`operator&verbar;&verbar;`] 
| link:#F-operator_bitnot[`operator&#126;`] 
| link:#F-operator_lshift[`operator&lt;&lt;`] 
| link:#F-operator_not[`operator!`] 
| link:#F-operator_eq[`operator&equals;&equals;`] 
| link:#F-operator_not_eq[`operator!&equals;`] 
| link:#F-operator_lt[`operator&lt;`] 
| link:#F-operator_le[`operator&lt;&equals;`] 
| link:#F-operator_gt[`operator&gt;`] 
| link:#F-operator_ge[`operator&gt;&equals;`] 
| link:#F-operator_3way[`operator&lt;&equals;&gt;`] 
|===

[#F-operator_assign]
== link:#F[F]::operator&equals;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&equals;(link:#F[F]& other);
----

[#F-operator_mod]
== link:#F[F]::operator%

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator%(link:#F[F]& rhs);
----

[#F-operator_mod_eq]
== link:#F[F]::operator%&equals;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator%&equals;(link:#F[F]& rhs);
----

[#F-operator_bitand]
== link:#F[F]::operator&amp;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&amp;(link:#F[F]& rhs);
----

[#F-operator_and]
== link:#F[F]::operator&amp;&amp;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&amp;&amp;(link:#F[F]& rhs);
----

[#F-operator_and_eq]
== link:#F[F]::operator&amp;&equals;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&amp;&equals;(link:#F[F]& rhs);
----

[#F-operator_call]
== link:#F[F]::operator()

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator()(link:#F[F]& rhs);
----

[#F-operator_star]
== link:#F[F]::operator&ast;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&ast;(link:#F[F]& rhs);
----

[#F-operator_star_eq]
== link:#F[F]::operator&ast;&equals;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&ast;&equals;(link:#F[F]& rhs);
----

[#F-operator_plus]
== link:#F[F]::operator&plus;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&plus;(link:#F[F]& rhs);
----

[#F-operator_inc]
== link:#F[F]::operator&plus;&plus;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&plus;&plus;();
----

[#F-operator_plus_eq]
== link:#F[F]::operator&plus;&equals;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&plus;&equals;(link:#F[F]& rhs);
----

[#F-operator_comma]
== link:#F[F]::operator,

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator,(link:#F[F]& rhs);
----

[#F-operator_minus]
== link:#F[F]::operator&hyphen;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&hyphen;(link:#F[F]& rhs);
----

[#F-operator_dec]
== link:#F[F]::operator&hyphen;&hyphen;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&hyphen;&hyphen;();
----

[#F-operator_minus_eq]
== link:#F[F]::operator&hyphen;&equals;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&hyphen;&equals;(link:#F[F]& rhs);
----

[#F-operator_ptr]
== link:#F[F]::operator&hyphen;&gt;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&hyphen;&gt;();
----

[#F-operator_ptrmem]
== link:#F[F]::operator&hyphen;&gt;&ast;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&hyphen;&gt;&ast;(link:#F[F]& rhs);
----

[#F-operator_slash]
== link:#F[F]::operator&sol;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&sol;(link:#F[F]& rhs);
----

[#F-operator_slash_eq]
== link:#F[F]::operator&sol;&equals;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&sol;&equals;(link:#F[F]& rhs);
----

[#F-operator_lshift_eq]
== link:#F[F]::operator&lt;&lt;&equals;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&lt;&lt;&equals;(link:#F[F]& rhs);
----

[#F-operator_rshift]
== link:#F[F]::operator&gt;&gt;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&gt;&gt;(link:#F[F]& rhs);
----

[#F-operator_rshift_eq]
== link:#F[F]::operator&gt;&gt;&equals;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&gt;&gt;&equals;(link:#F[F]& rhs);
----

[#F-operator_subs]
== link:#F[F]::operator&lsqb;&rsqb;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&lsqb;&rsqb;(link:#F[F]& rhs);
----

[#F-operator_xor]
== link:#F[F]::operator&circ;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&circ;(link:#F[F]& rhs);
----

[#F-operator_xor_eq]
== link:#F[F]::operator&circ;&equals;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&circ;&equals;(link:#F[F]& rhs);
----

[#F-operator_bitor]
== link:#F[F]::operator&verbar;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&verbar;(link:#F[F]& rhs);
----

[#F-operator_or_eq]
== link:#F[F]::operator&verbar;&equals;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&verbar;&equals;(link:#F[F]& rhs);
----

[#F-operator_or]
== link:#F[F]::operator&verbar;&verbar;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&verbar;&verbar;(link:#F[F]& rhs);
----

[#F-operator_bitnot]
== link:#F[F]::operator&#126;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&#126;();
----

[#F-operator_lshift]
== link:#F[F]::operator&lt;&lt;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&lt;&lt;(link:#F[F]& rhs);
----

[#F-operator_not]
== link:#F[F]::operator!

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator!();
----

[#F-operator_eq]
== link:#F[F]::operator&equals;&equals;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&equals;&equals;(link:#F[F]& rhs);
----

[#F-operator_not_eq]
== link:#F[F]::operator!&equals;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator!&equals;(link:#F[F]& rhs);
----

[#F-operator_lt]
== link:#F[F]::operator&lt;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&lt;(link:#F[F]& rhs);
----

[#F-operator_le]
== link:#F[F]::operator&lt;&equals;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&lt;&equals;(link:#F[F]& rhs);
----

[#F-operator_gt]
== link:#F[F]::operator&gt;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&gt;(link:#F[F]& rhs);
----

[#F-operator_ge]
== link:#F[F]::operator&gt;&equals;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&gt;&equals;(link:#F[F]& rhs);
----

[#F-operator_3way]
== link:#F[F]::operator&lt;&equals;&gt;

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&lt;&equals;&gt;(link:#F[F]& rhs);
----

[#f0]
== f0

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f0();
----

[#f5]
== f5

See link:#A-f1[`A&colon;&colon;f1`]

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f5();
----

=== Description

See link:#A-f1[`&colon;&colon;A&colon;&colon;f1`]

[#f6]
== f6

See link:#F-operator_bitnot[`F&colon;&colon;operator&#126;`]

=== Synopsis

Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f6();
----

=== Description

See link:#F-operator_comma[`F&colon;&colon;operator,`]

See link:#F-operator_call[`F&colon;&colon;operator()`]

See link:#F-operator_subs[`F&colon;&colon;operator&lsqb;&rsqb;`]

See link:#F-operator_plus[`F&colon;&colon;operator&plus;`]

See link:#F-operator_inc[`F&colon;&colon;operator&plus;&plus;`]

See link:#F-operator_plus_eq[`F&colon;&colon;operator&plus;&equals;`]

See link:#F-operator_bitand[`F&colon;&colon;operator&amp;`]

See link:#F-operator_and[`F&colon;&colon;operator&amp;&amp;`]

See link:#F-operator_and_eq[`F&colon;&colon;operator&amp;&equals;`]

See link:#F-operator_bitor[`F&colon;&colon;operator&verbar;`]

See link:#F-operator_or[`F&colon;&colon;operator&verbar;&verbar;`]

See link:#F-operator_or_eq[`F&colon;&colon;operator&verbar;&equals;`]

See link:#F-operator_minus[`F&colon;&colon;operator&hyphen;`]

See link:#F-operator_dec[`F&colon;&colon;operator&hyphen;&hyphen;`]

See link:#F-operator_minus_eq[`F&colon;&colon;operator&hyphen;&equals;`]

See link:#F-operator_ptr[`F&colon;&colon;operator&hyphen;&gt;`]

See link:#F-operator_ptrmem[`F&colon;&colon;operator&hyphen;&gt;&ast;`]

See link:#F-operator_lt[`F&colon;&colon;operator&lt;`]

See link:#F-operator_lshift[`F&colon;&colon;operator&lt;&lt;`]

See link:#F-operator_lshift_eq[`F&colon;&colon;operator&lt;&lt;&equals;`]

See link:#F-operator_le[`F&colon;&colon;operator&lt;&equals;`]

See link:#F-operator_3way[`F&colon;&colon;operator&lt;&equals;&gt;`]

See link:#F-operator_gt[`F&colon;&colon;operator&gt;`]

See link:#F-operator_rshift[`F&colon;&colon;operator&gt;&gt;`]

See link:#F-operator_rshift_eq[`F&colon;&colon;operator&gt;&gt;&equals;`]

See link:#F-operator_ge[`F&colon;&colon;operator&gt;&equals;`]

See link:#F-operator_star[`F&colon;&colon;operator&ast;`]

See link:#F-operator_star_eq[`F&colon;&colon;operator&ast;&equals;`]

See link:#F-operator_mod[`F&colon;&colon;operator%`]

See link:#F-operator_mod_eq[`F&colon;&colon;operator%&equals;`]

See link:#F-operator_slash[`F&colon;&colon;operator&sol;`]

See link:#F-operator_slash_eq[`F&colon;&colon;operator&sol;&equals;`]

See link:#F-operator_xor[`F&colon;&colon;operator&circ;`]

See link:#F-operator_xor_eq[`F&colon;&colon;operator&circ;&equals;`]

See link:#F-operator_assign[`F&colon;&colon;operator&equals;`]

See link:#F-operator_eq[`F&colon;&colon;operator&equals;&equals;`]

See link:#F-operator_not[`F&colon;&colon;operator!`]

See link:#F-operator_not_eq[`F&colon;&colon;operator!&equals;`]


[.small]#Created with https://www.mrdocs.com[MrDocs]#
