#ifndef CIRCLE_DESCRIBED_HPP
#define CIRCLE_DESCRIBED_HPP

// Generated by MrDocs from documented types. Do not edit by hand.
//
// Include this to gain Boost.Describe reflection over the types declared
// in circle.hpp.

#include "circle.hpp"
#include "shape.described.hpp"
#include <boost/describe.hpp>

namespace app {

BOOST_DESCRIBE_STRUCT(Circle, (Shape), (radius, area))

}  // namespace app

#endif  // CIRCLE_DESCRIBED_HPP
