#ifndef LEVEL_DESCRIBED_HPP
#define LEVEL_DESCRIBED_HPP

// Generated by MrDocs from documented types. Do not edit by hand.
//
// Include this to gain Boost.Describe reflection over the types declared
// in level.hpp.

#include "level.hpp"
#include <boost/describe.hpp>

namespace app {

BOOST_DESCRIBE_ENUM(Level, debug, info, warning, error)

}  // namespace app

#endif  // LEVEL_DESCRIBED_HPP
