#ifndef SHAPE_DESCRIBED_HPP
#define SHAPE_DESCRIBED_HPP

// Generated by MrDocs from documented types. Do not edit by hand.
//
// Include this to gain Boost.Describe reflection over the types declared
// in shape.hpp.

#include "shape.hpp"
#include <boost/describe.hpp>

namespace app {

BOOST_DESCRIBE_STRUCT(Shape, (), (name))

}  // namespace app

#endif  // SHAPE_DESCRIBED_HPP
