#ifndef VEC2_DESCRIBED_HPP
#define VEC2_DESCRIBED_HPP

// Generated by MrDocs from documented types. Do not edit by hand.
//
// Include this to gain Boost.Describe reflection over the types declared
// in vec2.hpp.

#include "vec2.hpp"
#include <boost/describe.hpp>

namespace app {

BOOST_DESCRIBE_STRUCT(Vec2, (), (x, y, length))

}  // namespace app

#endif  // VEC2_DESCRIBED_HPP
