//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// Copyright (c) 2025 Alan de Freitas (alandefreitas@gmail.com)
//
// Official repository: https://github.com/cppalliance/mrdocs
//

#ifndef INFO
#define INFO(PascalName)
#endif

// Metadata Blocks
INFO(Param)
INFO(Postcondition)
INFO(Precondition)
INFO(Returns)
INFO(See)
INFO(Throws)
INFO(TParam)

#undef INFO
