= Reference
:mrdocs:

[#index]
== Global namespace

=== Types
[cols=2]
|===
| Name | Description 

| <<#A-0e,`A`>> 
| 

| <<#A-0c,`A&lt;long&gt;`>> 
| 

| <<#A-00,`A&lt;short&gt;`>> 
| 

| <<#A-01,`A&lt;float&gt;`>> 
| 

| <<#A-07,`A&lt;unsigned int&gt;`>> 
| 

| <<#E,`E`>> 
| 

|===

[#A-0e]
== A

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
struct A;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#A-0e-B-07,`B`>> 
| 

| <<#A-0e-B-00,`B&lt;double&gt;`>> 
| 

|===



[#A-0e-B-07]
== <<#A-0e,A>>::B

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct B;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#A-0e-B-07-C,`C`>> 
| 

| <<#A-0e-B-07-D-09,`D`>> 
| 

| <<#A-0e-B-07-D-0f,`D&lt;bool&gt;`>> 
| 

|===



[#A-0e-B-07-C]
== <<#A-0e,A>>::<<#A-0e-B-07,B>>::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----




[#A-0e-B-07-D-09]
== <<#A-0e,A>>::<<#A-0e-B-07,B>>::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----




[#A-0e-B-07-D-0f]
== <<#A-0e,A>>::<<#A-0e-B-07,B>>::D&lt;bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0e-B-07-D-09,D>>&lt;bool&gt;;
----




[#A-0e-B-00]
== <<#A-0e,A>>::B&lt;double&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0e-B-07,B>>&lt;double&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#A-0e-B-00-C,`C`>> 
| 

| <<#A-0e-B-00-D-09,`D`>> 
| 

| <<#A-0e-B-00-D-0d,`D&lt;bool&gt;`>> 
| 

|===



[#A-0e-B-00-C]
== <<#A-0e,A>>::<<#A-0e-B-00,B>>&lt;double&gt;::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----




[#A-0e-B-00-D-09]
== <<#A-0e,A>>::<<#A-0e-B-00,B>>&lt;double&gt;::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----




[#A-0e-B-00-D-0d]
== <<#A-0e,A>>::<<#A-0e-B-00,B>>&lt;double&gt;::D&lt;bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0e-B-00-D-09,D>>&lt;bool&gt;;
----




[#A-0c]
== A&lt;long&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0e,A>>&lt;long&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#A-0c-B-0b,`B`>> 
| 

| <<#A-0c-B-0d,`B&lt;double&gt;`>> 
| 

| <<#A-0c-B-08,`B&lt;float&gt;`>> 
| 

|===



[#A-0c-B-0b]
== <<#A-0c,A>>&lt;long&gt;::B

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct B;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#A-0c-B-0b-C,`C`>> 
| 

| <<#A-0c-B-0b-D-00,`D`>> 
| 

| <<#A-0c-B-0b-D-0b,`D&lt;bool&gt;`>> 
| 

|===



[#A-0c-B-0b-C]
== <<#A-0c,A>>&lt;long&gt;::<<#A-0c-B-0b,B>>::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----




[#A-0c-B-0b-D-00]
== <<#A-0c,A>>&lt;long&gt;::<<#A-0c-B-0b,B>>::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----




[#A-0c-B-0b-D-0b]
== <<#A-0c,A>>&lt;long&gt;::<<#A-0c-B-0b,B>>::D&lt;bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0c-B-0b-D-00,D>>&lt;bool&gt;;
----




[#A-0c-B-0d]
== <<#A-0c,A>>&lt;long&gt;::B&lt;double&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0c-B-0b,B>>&lt;double&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#A-0c-B-0d-C,`C`>> 
| 

| <<#A-0c-B-0d-D-0c,`D`>> 
| 

| <<#A-0c-B-0d-D-03,`D&lt;bool&gt;`>> 
| 

|===



[#A-0c-B-0d-C]
== <<#A-0c,A>>&lt;long&gt;::<<#A-0c-B-0d,B>>&lt;double&gt;::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----




[#A-0c-B-0d-D-0c]
== <<#A-0c,A>>&lt;long&gt;::<<#A-0c-B-0d,B>>&lt;double&gt;::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----




[#A-0c-B-0d-D-03]
== <<#A-0c,A>>&lt;long&gt;::<<#A-0c-B-0d,B>>&lt;double&gt;::D&lt;bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0e-B-00-D-09,D>>&lt;bool&gt;;
----




[#A-0c-B-08]
== <<#A-0c,A>>&lt;long&gt;::B&lt;float&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0c-B-0b,B>>&lt;float&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#A-0c-B-08-C,`C`>> 
| 

| <<#A-0c-B-08-D-08,`D`>> 
| 

| <<#A-0c-B-08-D-03,`D&lt;bool&gt;`>> 
| 

|===



[#A-0c-B-08-C]
== <<#A-0c,A>>&lt;long&gt;::<<#A-0c-B-08,B>>&lt;float&gt;::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----




[#A-0c-B-08-D-08]
== <<#A-0c,A>>&lt;long&gt;::<<#A-0c-B-08,B>>&lt;float&gt;::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----




[#A-0c-B-08-D-03]
== <<#A-0c,A>>&lt;long&gt;::<<#A-0c-B-08,B>>&lt;float&gt;::D&lt;bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0c-B-0b-D-00,D>>&lt;bool&gt;;
----




[#A-00]
== A&lt;short&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0e,A>>&lt;short&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#A-00-B-0e,`B`>> 
| 

| <<#A-00-B-07,`B&lt;double&gt;`>> 
| 

| <<#A-00-B-00,`B&lt;void&gt;`>> 
| 

|===



[#A-00-B-0e]
== <<#A-00,A>>&lt;short&gt;::B

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct B;
----




[#A-00-B-07]
== <<#A-00,A>>&lt;short&gt;::B&lt;double&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0e-B-07,B>>&lt;double&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#A-00-B-07-C,`C`>> 
| 

| <<#A-00-B-07-D-015b,`D`>> 
| 

| <<#A-00-B-07-D-0150,`D&lt;bool&gt;`>> 
| 

|===



[#A-00-B-07-C]
== <<#A-00,A>>&lt;short&gt;::<<#A-00-B-07,B>>&lt;double&gt;::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----




[#A-00-B-07-D-015b]
== <<#A-00,A>>&lt;short&gt;::<<#A-00-B-07,B>>&lt;double&gt;::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----




[#A-00-B-07-D-0150]
== <<#A-00,A>>&lt;short&gt;::<<#A-00-B-07,B>>&lt;double&gt;::D&lt;bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0e-B-00-D-09,D>>&lt;bool&gt;;
----




[#A-00-B-00]
== <<#A-00,A>>&lt;short&gt;::B&lt;void&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0e-B-07,B>>&lt;void&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#A-00-B-00-C,`C`>> 
| 

| <<#A-00-B-00-D-03,`D`>> 
| 

| <<#A-00-B-00-D-07,`D&lt;bool&gt;`>> 
| 

|===



[#A-00-B-00-C]
== <<#A-00,A>>&lt;short&gt;::<<#A-00-B-00,B>>&lt;void&gt;::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----




[#A-00-B-00-D-03]
== <<#A-00,A>>&lt;short&gt;::<<#A-00-B-00,B>>&lt;void&gt;::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----




[#A-00-B-00-D-07]
== <<#A-00,A>>&lt;short&gt;::<<#A-00-B-00,B>>&lt;void&gt;::D&lt;bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-00-B-00-D-03,D>>&lt;bool&gt;;
----




[#A-01]
== A&lt;float&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0e,A>>&lt;float&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#A-01-B-07,`B`>> 
| 

| <<#A-01-B-08,`B&lt;double, double&gt;`>> 
| 

|===



[#A-01-B-07]
== <<#A-01,A>>&lt;float&gt;::B

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct B;
----




[#A-01-B-08]
== <<#A-01,A>>&lt;float&gt;::B&lt;double, double&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0e-B-07,B>>&lt;double, double&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#A-01-B-08-C,`C`>> 
| 

| <<#A-01-B-08-D-0ae,`D`>> 
| 

| <<#A-01-B-08-D-0af,`D&lt;bool, bool&gt;`>> 
| 

|===



[#A-01-B-08-C]
== <<#A-01,A>>&lt;float&gt;::<<#A-01-B-08,B>>&lt;double, double&gt;::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----




[#A-01-B-08-D-0ae]
== <<#A-01,A>>&lt;float&gt;::<<#A-01-B-08,B>>&lt;double, double&gt;::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----




[#A-01-B-08-D-0af]
== <<#A-01,A>>&lt;float&gt;::<<#A-01-B-08,B>>&lt;double, double&gt;::D&lt;bool, bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0e-B-00-D-09,D>>&lt;bool, bool&gt;;
----




[#A-07]
== A&lt;unsigned int&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0e,A>>&lt;unsigned int&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#A-07-B-03a,`B`>> 
| 

| <<#A-07-B-03e,`B&lt;double&gt;`>> 
| 

| <<#A-07-B-05,`B&lt;float&gt;`>> 
| 

|===



[#A-07-B-03a]
== <<#A-07,A>>&lt;unsigned int&gt;::B

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct B;
----




[#A-07-B-03e]
== <<#A-07,A>>&lt;unsigned int&gt;::B&lt;double&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0e-B-07,B>>&lt;double&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#A-07-B-03e-C,`C`>> 
| 

| <<#A-07-B-03e-D-01,`D`>> 
| 

| <<#A-07-B-03e-D-0f,`D&lt;bool&gt;`>> 
| 

|===



[#A-07-B-03e-C]
== <<#A-07,A>>&lt;unsigned int&gt;::<<#A-07-B-03e,B>>&lt;double&gt;::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----




[#A-07-B-03e-D-01]
== <<#A-07,A>>&lt;unsigned int&gt;::<<#A-07-B-03e,B>>&lt;double&gt;::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----




[#A-07-B-03e-D-0f]
== <<#A-07,A>>&lt;unsigned int&gt;::<<#A-07-B-03e,B>>&lt;double&gt;::D&lt;bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0e-B-00-D-09,D>>&lt;bool&gt;;
----




[#A-07-B-05]
== <<#A-07,A>>&lt;unsigned int&gt;::B&lt;float&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0e-B-07,B>>&lt;float&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#A-07-B-05-C,`C`>> 
| 

| <<#A-07-B-05-D-0e,`D`>> 
| 

| <<#A-07-B-05-D-01,`D&lt;bool&gt;`>> 
| 

|===



[#A-07-B-05-C]
== <<#A-07,A>>&lt;unsigned int&gt;::<<#A-07-B-05,B>>&lt;float&gt;::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----




[#A-07-B-05-D-0e]
== <<#A-07,A>>&lt;unsigned int&gt;::<<#A-07-B-05,B>>&lt;float&gt;::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----




[#A-07-B-05-D-01]
== <<#A-07,A>>&lt;unsigned int&gt;::<<#A-07-B-05,B>>&lt;float&gt;::D&lt;bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#A-0e-B-07-D-09,D>>&lt;bool&gt;;
----




[#E]
== E

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct E;
----

=== Data Members
[cols=2]
|===
| Name | Description 

| <<#E-m0,`m0`>> 
| 

| <<#E-m1,`m1`>> 
| 

| <<#E-m10,`m10`>> 
| 

| <<#E-m11,`m11`>> 
| 

| <<#E-m12,`m12`>> 
| 

| <<#E-m13,`m13`>> 
| 

| <<#E-m14,`m14`>> 
| 

| <<#E-m2,`m2`>> 
| 

| <<#E-m3,`m3`>> 
| 

| <<#E-m4,`m4`>> 
| 

| <<#E-m5,`m5`>> 
| 

| <<#E-m6,`m6`>> 
| 

| <<#E-m7,`m7`>> 
| 

| <<#E-m8,`m8`>> 
| 

| <<#E-m9,`m9`>> 
| 

|===



[#E-m0]
== <<#E,E>>::m0

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
<<#A-0e,A>>&lt;float&gt;::<<#A-01-B-08,B>>&lt;double&gt; m0;
----

[#E-m1]
== <<#E,E>>::m1

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
<<#A-0e,A>>&lt;long&gt;::<<#A-0c-B-0d,B>>&lt;double&gt; m1;
----

[#E-m10]
== <<#E,E>>::m10

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
<<#A-0e,A>>&lt;float&gt;::<<#A-01-B-08,B>>&lt;double&gt;::<<#A-01-B-08-D-0af,D>>&lt;bool&gt; m10;
----

[#E-m11]
== <<#E,E>>::m11

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
<<#A-0e,A>>&lt;long&gt;::<<#A-0c-B-0d,B>>&lt;double&gt;::<<#A-0c-B-0d-D-03,D>>&lt;bool&gt; m11;
----

[#E-m12]
== <<#E,E>>::m12

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
<<#A-0e,A>>&lt;long&gt;::<<#A-0c-B-0b,B>>&lt;float&gt;::<<#A-0c-B-08-D-03,D>>&lt;bool&gt; m12;
----

[#E-m13]
== <<#E,E>>::m13

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
<<#A-0e,A>>&lt;unsigned int&gt;::<<#A-07-B-03a,B>>&lt;float&gt;::<<#A-07-B-05-D-01,D>>&lt;bool&gt; m13;
----

[#E-m14]
== <<#E,E>>::m14

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
<<#A-0e,A>>&lt;short&gt;::<<#A-00-B-00,B>>&lt;void&gt;::<<#A-00-B-00-D-07,D>>&lt;bool&gt; m14;
----

[#E-m2]
== <<#E,E>>::m2

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
<<#A-0e,A>>&lt;long&gt;::<<#A-0c-B-0b,B>>&lt;float&gt; m2;
----

[#E-m3]
== <<#E,E>>::m3

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
<<#A-0e,A>>&lt;unsigned int&gt;::<<#A-07-B-03a,B>>&lt;float&gt; m3;
----

[#E-m4]
== <<#E,E>>::m4

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
<<#A-0e,A>>&lt;short&gt;::<<#A-00-B-00,B>>&lt;void&gt; m4;
----

[#E-m5]
== <<#E,E>>::m5

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
<<#A-0e,A>>&lt;float&gt;::<<#A-01-B-08,B>>&lt;double&gt;::<<#A-01-B-08-C,C>> m5;
----

[#E-m6]
== <<#E,E>>::m6

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
<<#A-0e,A>>&lt;long&gt;::<<#A-0c-B-0d,B>>&lt;double&gt;::<<#A-0c-B-0d-C,C>> m6;
----

[#E-m7]
== <<#E,E>>::m7

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
<<#A-0e,A>>&lt;long&gt;::<<#A-0c-B-0b,B>>&lt;float&gt;::<<#A-0c-B-08-C,C>> m7;
----

[#E-m8]
== <<#E,E>>::m8

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
<<#A-0e,A>>&lt;unsigned int&gt;::<<#A-07-B-03a,B>>&lt;float&gt;::<<#A-07-B-05-C,C>> m8;
----

[#E-m9]
== <<#E,E>>::m9

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
<<#A-0e,A>>&lt;short&gt;::<<#A-00-B-00,B>>&lt;void&gt;::<<#A-00-B-00-C,C>> m9;
----



[.small]#Created with https://www.mrdocs.com[MrDocs]#
