= Reference
:mrdocs:

[#index]
== Global namespace


=== Types

[cols=1]
|===
| Name 

| <<S0-03,`S0`>> 
| <<S0-09,`S0&lt;short&gt;`>> 
| <<S0-00,`S0&lt;void&gt;`>> 
| <<A0,`A0`>> 
| <<A1,`A1`>> 
|===

[#A0]
== A0


=== Synopsis


Declared in `&lt;decay&hyphen;to&hyphen;primary&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using A0 = <<S0-03,S0>>&lt;void&gt;;
----

[#A1]
== A1


=== Synopsis


Declared in `&lt;decay&hyphen;to&hyphen;primary&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using A1 = <<A0,A0>>::<<S0-00-M1,M1>>&lt;short&gt;::<<S0-09-M0,M0>>;
----

[#S0-03]
== S0


=== Synopsis


Declared in `&lt;decay&hyphen;to&hyphen;primary&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
struct S0;
----

=== Types

[cols=1]
|===
| Name 

| <<S0-03-M0,`M0`>> 
| <<S0-03-M1,`M1`>> 
|===



[#S0-03-M0]
== <<S0-03,S0>>::M0


=== Synopsis


Declared in `&lt;decay&hyphen;to&hyphen;primary&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using M0 = T;
----

[#S0-03-M1]
== <<S0-03,S0>>::M1


=== Synopsis


Declared in `&lt;decay&hyphen;to&hyphen;primary&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
using M1 = <<S0-03,S0>>&lt;U&gt;;
----

[#S0-09]
== S0&lt;short&gt;


=== Synopsis


Declared in `&lt;decay&hyphen;to&hyphen;primary&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<S0-03,S0>>&lt;short&gt;;
----

=== Types

[cols=1]
|===
| Name 

| <<S0-09-M0,`M0`>> 
| <<S0-09-M1,`M1`>> 
|===



[#S0-09-M0]
== <<S0-09,S0>>&lt;short&gt;::M0


=== Synopsis


Declared in `&lt;decay&hyphen;to&hyphen;primary&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using M0 = short;
----

[#S0-09-M1]
== <<S0-09,S0>>&lt;short&gt;::M1


=== Synopsis


Declared in `&lt;decay&hyphen;to&hyphen;primary&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
using M1 = <<S0-03,S0>>&lt;U&gt;;
----

[#S0-00]
== S0&lt;void&gt;


=== Synopsis


Declared in `&lt;decay&hyphen;to&hyphen;primary&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<S0-03,S0>>&lt;void&gt;;
----

=== Types

[cols=1]
|===
| Name 

| <<S0-00-M0,`M0`>> 
| <<S0-00-M1,`M1`>> 
|===



[#S0-00-M0]
== <<S0-00,S0>>&lt;void&gt;::M0


=== Synopsis


Declared in `&lt;decay&hyphen;to&hyphen;primary&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using M0 = void;
----

[#S0-00-M1]
== <<S0-00,S0>>&lt;void&gt;::M1


=== Synopsis


Declared in `&lt;decay&hyphen;to&hyphen;primary&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
using M1 = <<S0-03,S0>>&lt;U&gt;;
----



[.small]#Created with https://www.mrdocs.com[MrDocs]#
