= Reference
:mrdocs:

[#index]
== Global namespace


=== Types

[cols=1]
|===
| Name 

| <<A,`A`>> 
| <<B,`B`>> 
|===
=== Functions

[cols=1]
|===
| Name 

| <<f,`f`>> 
|===

[#A]
== A


=== Synopsis


Declared in `&lt;static&hyphen;data&hyphen;def&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
struct A;
----

=== Static Data Members

[cols=1]
|===
| Name 

| <<A-v0,`v0`>> 
| <<A-v1,`v1`>> 
| <<A-v2,`v2`>> 
| <<A-v3,`v3`>> 
| <<A-v4,`v4`>> 
| <<A-v5,`v5`>> 
| <<A-v6,`v6`>> 
| <<A-v7,`v7`>> 
|===



[#A-v0]
== <<A,A>>::v0


=== Synopsis


Declared in `&lt;static&hyphen;data&hyphen;def&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
static
int v0 = 0;
----

[#A-v1]
== <<A,A>>::v1


=== Synopsis


Declared in `&lt;static&hyphen;data&hyphen;def&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
static
int v1 = 1;
----

[#A-v2]
== <<A,A>>::v2


=== Synopsis


Declared in `&lt;static&hyphen;data&hyphen;def&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
constexpr
static
int const v2 = 2;
----

[#A-v3]
== <<A,A>>::v3


=== Synopsis


Declared in `&lt;static&hyphen;data&hyphen;def&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
static
int const v3 = 3;
----

[#A-v4]
== <<A,A>>::v4


=== Synopsis


Declared in `&lt;static&hyphen;data&hyphen;def&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
static
int const v4 = 4;
----

[#A-v5]
== <<A,A>>::v5


=== Synopsis


Declared in `&lt;static&hyphen;data&hyphen;def&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
static
int v5 = 5;
----

[#A-v6]
== <<A,A>>::v6


=== Synopsis


Declared in `&lt;static&hyphen;data&hyphen;def&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
static
int const v6 = 6;
----

[#A-v7]
== <<A,A>>::v7


=== Synopsis


Declared in `&lt;static&hyphen;data&hyphen;def&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
constexpr
static
int const v7 = 7;
----

[#B]
== B


=== Synopsis


Declared in `&lt;static&hyphen;data&hyphen;def&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct B;
----

=== Static Data Members

[cols=1]
|===
| Name 

| <<B-x0,`x0`>> 
| <<B-x1,`x1`>> 
|===



[#B-x0]
== <<B,B>>::x0


=== Synopsis


Declared in `&lt;static&hyphen;data&hyphen;def&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
static
thread_local
int const x0 = 0;
----

[#B-x1]
== <<B,B>>::x1


=== Synopsis


Declared in `&lt;static&hyphen;data&hyphen;def&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
constexpr
static
thread_local
int const x1 = 0;
----

[#f]
== f


=== Synopsis


Declared in `&lt;static&hyphen;data&hyphen;def&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
auto
f();
----



[.small]#Created with https://www.mrdocs.com[MrDocs]#
