= Reference
:mrdocs:

[#index]
== Global namespace


=== Variables

[cols=1]
|===
| Name 

| <<var,`var`>> 
| <<var_const,`var&lowbar;const`>> 
| <<var_const_t,`var&lowbar;const&lowbar;t`>> 
| <<var_constexpr,`var&lowbar;constexpr`>> 
| <<var_constexpr_t,`var&lowbar;constexpr&lowbar;t`>> 
| <<var_inline_const,`var&lowbar;inline&lowbar;const`>> 
| <<var_inline_const_t,`var&lowbar;inline&lowbar;const&lowbar;t`>> 
| <<var_inline_constexpr,`var&lowbar;inline&lowbar;constexpr`>> 
| <<var_inline_constexpr_t,`var&lowbar;inline&lowbar;constexpr&lowbar;t`>> 
| <<var_t,`var&lowbar;t`>> 
|===

[#var]
== var


=== Synopsis


Declared in `&lt;var&hyphen;inline&hyphen;constexpr&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
int var = 5;
----

[#var_const]
== var&lowbar;const


=== Synopsis


Declared in `&lt;var&hyphen;inline&hyphen;constexpr&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
int const var&lowbar;const = 4;
----

[#var_const_t]
== var&lowbar;const&lowbar;t


=== Synopsis


Declared in `&lt;var&hyphen;inline&hyphen;constexpr&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class T&gt;
T const var&lowbar;const&lowbar;t;
----

[#var_constexpr]
== var&lowbar;constexpr


=== Synopsis


Declared in `&lt;var&hyphen;inline&hyphen;constexpr&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
constexpr int var&lowbar;constexpr = 2;
----

[#var_constexpr_t]
== var&lowbar;constexpr&lowbar;t


=== Synopsis


Declared in `&lt;var&hyphen;inline&hyphen;constexpr&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class T&gt;
constexpr T var&lowbar;constexpr&lowbar;t;
----

[#var_inline_const]
== var&lowbar;inline&lowbar;const


=== Synopsis


Declared in `&lt;var&hyphen;inline&hyphen;constexpr&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
inline int const var&lowbar;inline&lowbar;const = 3;
----

[#var_inline_const_t]
== var&lowbar;inline&lowbar;const&lowbar;t


=== Synopsis


Declared in `&lt;var&hyphen;inline&hyphen;constexpr&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class T&gt;
inline T const var&lowbar;inline&lowbar;const&lowbar;t;
----

[#var_inline_constexpr]
== var&lowbar;inline&lowbar;constexpr


=== Synopsis


Declared in `&lt;var&hyphen;inline&hyphen;constexpr&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
inline constexpr int var&lowbar;inline&lowbar;constexpr = 1;
----

[#var_inline_constexpr_t]
== var&lowbar;inline&lowbar;constexpr&lowbar;t


=== Synopsis


Declared in `&lt;var&hyphen;inline&hyphen;constexpr&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class T&gt;
inline constexpr T var&lowbar;inline&lowbar;constexpr&lowbar;t;
----

[#var_t]
== var&lowbar;t


=== Synopsis


Declared in `&lt;var&hyphen;inline&hyphen;constexpr&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class T&gt;
T var&lowbar;t;
----



[.small]#Created with https://www.mrdocs.com[MrDocs]#
