= Reference
:mrdocs:

[#index]
== Global namespace

=== Types

[cols=1]
|===
| Name
| link:#A-0e[`A`] 
| link:#A-00[`A&lt;short&gt;`] 
| link:#A-07[`A&lt;unsigned int&gt;`] 
| link:#A-0c[`A&lt;long&gt;`] 
| link:#A-01[`A&lt;float&gt;`] 
| link:#E[`E`] 
|===

[#A-0e]
== A

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
struct A;
----

=== Types

[cols=1]
|===
| Name
| link:#A-0e-B-07[`B`] 
| link:#A-0e-B-00[`B&lt;double&gt;`] 
|===

[#A-0e-B-07]
== link:#A-0e[A]::B

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct B;
----

=== Types

[cols=1]
|===
| Name
| link:#A-0e-B-07-C[`C`] 
| link:#A-0e-B-07-D-09[`D`] 
| link:#A-0e-B-07-D-0f[`D&lt;bool&gt;`] 
|===

[#A-0e-B-07-C]
== link:#A-0e[A]::link:#A-0e-B-07[B]::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----

[#A-0e-B-07-D-09]
== link:#A-0e[A]::link:#A-0e-B-07[B]::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----

[#A-0e-B-07-D-0f]
== link:#A-0e[A]::link:#A-0e-B-07[B]::link:#A-0e-B-07-D-09[D]&lt;bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e-B-07-D-09[D]&lt;bool&gt;;
----

[#A-0e-B-00]
== link:#A-0e[A]::link:#A-0e-B-07[B]&lt;double&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e-B-07[B]&lt;double&gt;;
----

=== Types

[cols=1]
|===
| Name
| link:#A-0e-B-00-C[`C`] 
| link:#A-0e-B-00-D-09[`D`] 
| link:#A-0e-B-00-D-0d[`D&lt;bool&gt;`] 
|===

[#A-0e-B-00-C]
== link:#A-0e[A]::link:#A-0e-B-00[B&lt;double&gt;]::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----

[#A-0e-B-00-D-09]
== link:#A-0e[A]::link:#A-0e-B-00[B&lt;double&gt;]::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----

[#A-0e-B-00-D-0d]
== link:#A-0e[A]::link:#A-0e-B-00[B&lt;double&gt;]::link:#A-0e-B-00-D-09[D]&lt;bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e-B-00-D-09[D]&lt;bool&gt;;
----

[#A-00]
== link:#A-0e[A]&lt;short&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e[A]&lt;short&gt;;
----

=== Types

[cols=1]
|===
| Name
| link:#A-00-B-0e[`B`] 
| link:#A-00-B-00[`B&lt;void&gt;`] 
| link:#A-00-B-07[`B&lt;double&gt;`] 
|===

[#A-00-B-0e]
== link:#A-00[A&lt;short&gt;]::B

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct B;
----

[#A-00-B-00]
== link:#A-00[A&lt;short&gt;]::link:#A-0e-B-07[B]&lt;void&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e-B-07[B]&lt;void&gt;;
----

=== Types

[cols=1]
|===
| Name
| link:#A-00-B-00-C[`C`] 
| link:#A-00-B-00-D-03[`D`] 
| link:#A-00-B-00-D-07[`D&lt;bool&gt;`] 
|===

[#A-00-B-00-C]
== link:#A-00[A&lt;short&gt;]::link:#A-00-B-00[B&lt;void&gt;]::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----

[#A-00-B-00-D-03]
== link:#A-00[A&lt;short&gt;]::link:#A-00-B-00[B&lt;void&gt;]::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----

[#A-00-B-00-D-07]
== link:#A-00[A&lt;short&gt;]::link:#A-00-B-00[B&lt;void&gt;]::link:#A-00-B-00-D-03[D]&lt;bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-00-B-00-D-03[D]&lt;bool&gt;;
----

[#A-00-B-07]
== link:#A-00[A&lt;short&gt;]::link:#A-0e-B-07[B]&lt;double&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e-B-07[B]&lt;double&gt;;
----

=== Types

[cols=1]
|===
| Name
| link:#A-00-B-07-C[`C`] 
| link:#A-00-B-07-D-015b[`D`] 
| link:#A-00-B-07-D-0150[`D&lt;bool&gt;`] 
|===

[#A-00-B-07-C]
== link:#A-00[A&lt;short&gt;]::link:#A-00-B-07[B&lt;double&gt;]::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----

[#A-00-B-07-D-015b]
== link:#A-00[A&lt;short&gt;]::link:#A-00-B-07[B&lt;double&gt;]::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----

[#A-00-B-07-D-0150]
== link:#A-00[A&lt;short&gt;]::link:#A-00-B-07[B&lt;double&gt;]::link:#A-0e-B-00-D-09[D]&lt;bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e-B-00-D-09[D]&lt;bool&gt;;
----

[#A-07]
== link:#A-0e[A]&lt;unsigned int&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e[A]&lt;unsigned int&gt;;
----

=== Types

[cols=1]
|===
| Name
| link:#A-07-B-03a[`B`] 
| link:#A-07-B-05[`B&lt;float&gt;`] 
| link:#A-07-B-03e[`B&lt;double&gt;`] 
|===

[#A-07-B-03a]
== link:#A-07[A&lt;unsigned int&gt;]::B

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct B;
----

[#A-07-B-05]
== link:#A-07[A&lt;unsigned int&gt;]::link:#A-0e-B-07[B]&lt;float&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e-B-07[B]&lt;float&gt;;
----

=== Types

[cols=1]
|===
| Name
| link:#A-07-B-05-C[`C`] 
| link:#A-07-B-05-D-0e[`D`] 
| link:#A-07-B-05-D-01[`D&lt;bool&gt;`] 
|===

[#A-07-B-05-C]
== link:#A-07[A&lt;unsigned int&gt;]::link:#A-07-B-05[B&lt;float&gt;]::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----

[#A-07-B-05-D-0e]
== link:#A-07[A&lt;unsigned int&gt;]::link:#A-07-B-05[B&lt;float&gt;]::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----

[#A-07-B-05-D-01]
== link:#A-07[A&lt;unsigned int&gt;]::link:#A-07-B-05[B&lt;float&gt;]::link:#A-0e-B-07-D-09[D]&lt;bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e-B-07-D-09[D]&lt;bool&gt;;
----

[#A-07-B-03e]
== link:#A-07[A&lt;unsigned int&gt;]::link:#A-0e-B-07[B]&lt;double&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e-B-07[B]&lt;double&gt;;
----

=== Types

[cols=1]
|===
| Name
| link:#A-07-B-03e-C[`C`] 
| link:#A-07-B-03e-D-01[`D`] 
| link:#A-07-B-03e-D-0f[`D&lt;bool&gt;`] 
|===

[#A-07-B-03e-C]
== link:#A-07[A&lt;unsigned int&gt;]::link:#A-07-B-03e[B&lt;double&gt;]::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----

[#A-07-B-03e-D-01]
== link:#A-07[A&lt;unsigned int&gt;]::link:#A-07-B-03e[B&lt;double&gt;]::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----

[#A-07-B-03e-D-0f]
== link:#A-07[A&lt;unsigned int&gt;]::link:#A-07-B-03e[B&lt;double&gt;]::link:#A-0e-B-00-D-09[D]&lt;bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e-B-00-D-09[D]&lt;bool&gt;;
----

[#A-0c]
== link:#A-0e[A]&lt;long&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e[A]&lt;long&gt;;
----

=== Types

[cols=1]
|===
| Name
| link:#A-0c-B-0b[`B`] 
| link:#A-0c-B-08[`B&lt;float&gt;`] 
| link:#A-0c-B-0d[`B&lt;double&gt;`] 
|===

[#A-0c-B-0b]
== link:#A-0c[A&lt;long&gt;]::B

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct B;
----

=== Types

[cols=1]
|===
| Name
| link:#A-0c-B-0b-C[`C`] 
| link:#A-0c-B-0b-D-00[`D`] 
| link:#A-0c-B-0b-D-0b[`D&lt;bool&gt;`] 
|===

[#A-0c-B-0b-C]
== link:#A-0c[A&lt;long&gt;]::link:#A-0c-B-0b[B]::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----

[#A-0c-B-0b-D-00]
== link:#A-0c[A&lt;long&gt;]::link:#A-0c-B-0b[B]::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----

[#A-0c-B-0b-D-0b]
== link:#A-0c[A&lt;long&gt;]::link:#A-0c-B-0b[B]::link:#A-0c-B-0b-D-00[D]&lt;bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0c-B-0b-D-00[D]&lt;bool&gt;;
----

[#A-0c-B-08]
== link:#A-0c[A&lt;long&gt;]::link:#A-0c-B-0b[B]&lt;float&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0c-B-0b[B]&lt;float&gt;;
----

=== Types

[cols=1]
|===
| Name
| link:#A-0c-B-08-C[`C`] 
| link:#A-0c-B-08-D-08[`D`] 
| link:#A-0c-B-08-D-03[`D&lt;bool&gt;`] 
|===

[#A-0c-B-08-C]
== link:#A-0c[A&lt;long&gt;]::link:#A-0c-B-08[B&lt;float&gt;]::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----

[#A-0c-B-08-D-08]
== link:#A-0c[A&lt;long&gt;]::link:#A-0c-B-08[B&lt;float&gt;]::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----

[#A-0c-B-08-D-03]
== link:#A-0c[A&lt;long&gt;]::link:#A-0c-B-08[B&lt;float&gt;]::link:#A-0c-B-0b-D-00[D]&lt;bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0c-B-0b-D-00[D]&lt;bool&gt;;
----

[#A-0c-B-0d]
== link:#A-0c[A&lt;long&gt;]::link:#A-0c-B-0b[B]&lt;double&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0c-B-0b[B]&lt;double&gt;;
----

=== Types

[cols=1]
|===
| Name
| link:#A-0c-B-0d-C[`C`] 
| link:#A-0c-B-0d-D-0c[`D`] 
| link:#A-0c-B-0d-D-03[`D&lt;bool&gt;`] 
|===

[#A-0c-B-0d-C]
== link:#A-0c[A&lt;long&gt;]::link:#A-0c-B-0d[B&lt;double&gt;]::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----

[#A-0c-B-0d-D-0c]
== link:#A-0c[A&lt;long&gt;]::link:#A-0c-B-0d[B&lt;double&gt;]::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----

[#A-0c-B-0d-D-03]
== link:#A-0c[A&lt;long&gt;]::link:#A-0c-B-0d[B&lt;double&gt;]::link:#A-0e-B-00-D-09[D]&lt;bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e-B-00-D-09[D]&lt;bool&gt;;
----

[#A-01]
== link:#A-0e[A]&lt;float&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e[A]&lt;float&gt;;
----

=== Types

[cols=1]
|===
| Name
| link:#A-01-B-07[`B`] 
| link:#A-01-B-08[`B&lt;double, double&gt;`] 
|===

[#A-01-B-07]
== link:#A-01[A&lt;float&gt;]::B

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct B;
----

[#A-01-B-08]
== link:#A-01[A&lt;float&gt;]::link:#A-0e-B-07[B]&lt;double, double&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e-B-07[B]&lt;double, double&gt;;
----

=== Types

[cols=1]
|===
| Name
| link:#A-01-B-08-C[`C`] 
| link:#A-01-B-08-D-0ae[`D`] 
| link:#A-01-B-08-D-0af[`D&lt;bool, bool&gt;`] 
|===

[#A-01-B-08-C]
== link:#A-01[A&lt;float&gt;]::link:#A-01-B-08[B&lt;double, double&gt;]::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----

[#A-01-B-08-D-0ae]
== link:#A-01[A&lt;float&gt;]::link:#A-01-B-08[B&lt;double, double&gt;]::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct D;
----

[#A-01-B-08-D-0af]
== link:#A-01[A&lt;float&gt;]::link:#A-01-B-08[B&lt;double, double&gt;]::link:#A-0e-B-00-D-09[D]&lt;bool, bool&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e-B-00-D-09[D]&lt;bool, bool&gt;;
----

[#E]
== E

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct E;
----

=== Data Members

[cols=1]
|===
| Name
| link:#E-m0[`m0`] 
| link:#E-m1[`m1`] 
| link:#E-m10[`m10`] 
| link:#E-m11[`m11`] 
| link:#E-m12[`m12`] 
| link:#E-m13[`m13`] 
| link:#E-m14[`m14`] 
| link:#E-m2[`m2`] 
| link:#E-m3[`m3`] 
| link:#E-m4[`m4`] 
| link:#E-m5[`m5`] 
| link:#E-m6[`m6`] 
| link:#E-m7[`m7`] 
| link:#E-m8[`m8`] 
| link:#E-m9[`m9`] 
|===

[#E-m0]
== link:#E[E]::m0

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-01-B-08[A&lt;float&gt;::B&lt;double&gt;] m0;
----

[#E-m1]
== link:#E[E]::m1

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-0c-B-0d[A&lt;long&gt;::B&lt;double&gt;] m1;
----

[#E-m10]
== link:#E[E]::m10

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-01-B-08-D-0af[A&lt;float&gt;::B&lt;double&gt;::D&lt;bool&gt;] m10;
----

[#E-m11]
== link:#E[E]::m11

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-0c-B-0d-D-03[A&lt;long&gt;::B&lt;double&gt;::D&lt;bool&gt;] m11;
----

[#E-m12]
== link:#E[E]::m12

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-0c-B-08-D-03[A&lt;long&gt;::B&lt;float&gt;::D&lt;bool&gt;] m12;
----

[#E-m13]
== link:#E[E]::m13

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-07-B-05-D-01[A&lt;unsigned int&gt;::B&lt;float&gt;::D&lt;bool&gt;] m13;
----

[#E-m14]
== link:#E[E]::m14

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-00-B-00-D-07[A&lt;short&gt;::B&lt;void&gt;::D&lt;bool&gt;] m14;
----

[#E-m2]
== link:#E[E]::m2

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-0c-B-0b[A&lt;long&gt;::B&lt;float&gt;] m2;
----

[#E-m3]
== link:#E[E]::m3

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-07-B-03a[A&lt;unsigned int&gt;::B&lt;float&gt;] m3;
----

[#E-m4]
== link:#E[E]::m4

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-00-B-00[A&lt;short&gt;::B&lt;void&gt;] m4;
----

[#E-m5]
== link:#E[E]::m5

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-01-B-08-C[A&lt;float&gt;::B&lt;double&gt;::C] m5;
----

[#E-m6]
== link:#E[E]::m6

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-0c-B-0d-C[A&lt;long&gt;::B&lt;double&gt;::C] m6;
----

[#E-m7]
== link:#E[E]::m7

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-0c-B-08-C[A&lt;long&gt;::B&lt;float&gt;::C] m7;
----

[#E-m8]
== link:#E[E]::m8

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-07-B-05-C[A&lt;unsigned int&gt;::B&lt;float&gt;::C] m8;
----

[#E-m9]
== link:#E[E]::m9

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;3&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-00-B-00-C[A&lt;short&gt;::B&lt;void&gt;::C] m9;
----


[.small]#Created with https://www.mrdocs.com[MrDocs]#
