= Reference
:mrdocs:

[#index]
== Global namespace

=== Types

[cols=1]
|===
| Name
| <<A-0e,`A`>> 
| <<A-06,`A&lt;double&gt;`>> 
| <<A-02,`A&lt;long*&gt;`>> 
| <<A-03,`A&lt;T*&gt;`>> 
|===

[#A-0e]
== A

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
struct A;
----

[#A-06]
== A&lt;double&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<A-0e,A>>&lt;double&gt;;
----

=== Types

[cols=1]
|===
| Name
| <<A-06-D-0b,`D`>> 
| <<A-06-D-07,`D&lt;short&gt;`>> 
| <<A-06-D-04,`D&lt;float&gt;`>> 
|===

[#A-06-D-0b]
== <<A-06,A>>&lt;double&gt;::D

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct D;
----

=== Types

[cols=1]
|===
| Name
| <<A-06-D-0b-E-01,`E`>> 
| <<A-06-D-0b-E-04,`E&lt;T*&gt;`>> 
|===

[#A-06-D-0b-E-01]
== <<A-06,A>>&lt;double&gt;::<<A-06-D-0b,D>>::E

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
struct E;
----

[#A-06-D-0b-E-04]
== <<A-06,A>>&lt;double&gt;::<<A-06-D-0b,D>>::E&lt;T*&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
struct <<A-06-D-0b-E-01,E>>&lt;T*&gt;;
----

=== Types

[cols=1]
|===
| Name
| <<A-06-D-0b-E-04-F,`F`>> 
|===

[#A-06-D-0b-E-04-F]
== <<A-06,A>>&lt;double&gt;::<<A-06-D-0b,D>>::<<A-06-D-0b-E-04,E>>&lt;T*&gt;::F

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct F;
----

[#A-06-D-07]
== <<A-06,A>>&lt;double&gt;::D&lt;short&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<A-06-D-0b,D>>&lt;short&gt;;
----

=== Types

[cols=1]
|===
| Name
| <<A-06-D-07-E-07,`E`>> 
| <<A-06-D-07-E-01,`E&lt;int*&gt;`>> 
|===

[#A-06-D-07-E-07]
== <<A-06,A>>&lt;double&gt;::<<A-06-D-07,D>>&lt;short&gt;::E

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
struct E;
----

[#A-06-D-07-E-01]
== <<A-06,A>>&lt;double&gt;::<<A-06-D-07,D>>&lt;short&gt;::E&lt;int*&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<A-06-D-0b-E-01,E>>&lt;int*&gt;;
----

=== Types

[cols=1]
|===
| Name
| <<A-06-D-07-E-01-F,`F`>> 
|===

[#A-06-D-07-E-01-F]
== <<A-06,A>>&lt;double&gt;::<<A-06-D-07,D>>&lt;short&gt;::<<A-06-D-07-E-01,E>>&lt;int*&gt;::F

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct F;
----

[#A-06-D-04]
== <<A-06,A>>&lt;double&gt;::D&lt;float&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<A-06-D-0b,D>>&lt;float&gt;;
----

=== Types

[cols=1]
|===
| Name
| <<A-06-D-04-G-06,`G`>> 
| <<A-06-D-04-G-0c,`G&lt;T*&gt;`>> 
|===

[#A-06-D-04-G-06]
== <<A-06,A>>&lt;double&gt;::<<A-06-D-04,D>>&lt;float&gt;::G

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
struct G;
----

[#A-06-D-04-G-0c]
== <<A-06,A>>&lt;double&gt;::<<A-06-D-04,D>>&lt;float&gt;::G&lt;T*&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
struct <<A-06-D-04-G-06,G>>&lt;T*&gt;;
----

[#A-02]
== A&lt;long*&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<A-0e,A>>&lt;long*&gt;;
----

=== Types

[cols=1]
|===
| Name
| <<A-02-B-06,`B`>> 
| <<A-02-B-0d,`B&lt;int&gt;`>> 
| <<A-02-B-05,`B&lt;int*&gt;`>> 
|===

[#A-02-B-06]
== <<A-02,A>>&lt;long*&gt;::B

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct B;
----

[#A-02-B-0d]
== <<A-02,A>>&lt;long*&gt;::B&lt;int&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<A-03-B-05,B>>&lt;int&gt;;
----

[#A-02-B-05]
== <<A-02,A>>&lt;long*&gt;::B&lt;int*&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<A-03-B-05,B>>&lt;int*&gt;;
----

=== Types

[cols=1]
|===
| Name
| <<A-02-B-05-C,`C`>> 
|===

[#A-02-B-05-C]
== <<A-02,A>>&lt;long*&gt;::<<A-02-B-05,B>>&lt;int*&gt;::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----

[#A-03]
== A&lt;T*&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
struct <<A-0e,A>>&lt;T*&gt;;
----

=== Types

[cols=1]
|===
| Name
| <<A-03-B-05,`B`>> 
| <<A-03-B-0b,`B&lt;int&gt;`>> 
| <<A-03-B-01,`B&lt;U*&gt;`>> 
|===

[#A-03-B-05]
== <<A-03,A>>&lt;T*&gt;::B

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct B;
----

[#A-03-B-0b]
== <<A-03,A>>&lt;T*&gt;::B&lt;int&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<A-03-B-05,B>>&lt;int&gt;;
----

[#A-03-B-01]
== <<A-03,A>>&lt;T*&gt;::B&lt;U*&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct <<A-03-B-05,B>>&lt;U*&gt;;
----

=== Types

[cols=1]
|===
| Name
| <<A-03-B-01-C,`C`>> 
|===

[#A-03-B-01-C]
== <<A-03,A>>&lt;T*&gt;::<<A-03-B-01,B>>&lt;U*&gt;::C

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;2&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----


[.small]#Created with https://www.mrdocs.com[MrDocs]#
