= Reference
:mrdocs:

[#index]
== Global namespace

=== Types

[cols=1]
|===
| Name
| <<R0,`R0`>> 
| <<R1,`R1`>> 
| <<R2,`R2`>> 
| <<S0-0c,`S0`>> 
| <<S0-09,`S0&lt;2&gt;`>> 
| <<S0-073,`S0&lt;3&gt;`>> 
| <<S0-0e,`S0&lt;5&gt;`>> 
| <<S0-07e,`S0&lt;6&gt;`>> 
| <<U1,`U1`>> 
| <<U2,`U2`>> 
| <<U3,`U3`>> 
|===

[#U1]
== U1

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using U1 = <<S0-0c,S0>>&lt;4&gt;;
----

[#U2]
== U2

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using U2 = <<S0-0c,S0>>&lt;5&gt;::<<S0-0e-S1,S1>>;
----

[#U3]
== U3

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using U3 = <<S0-07e,S0>>&lt;6&gt;;
----

[#R0]
== R0

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R0
    : <<S0-0c,S0>>&lt;1&gt;;
----

=== Base Classes

[,cols=2]
|===
| Name
| Description
| `<<S0-0c,S0>>&lt;1&gt;`
| 
|===

=== Types

[cols=1]
|===
| Name
| <<S0-0c-S1,`S1`>> 
|===

[#R1]
== R1

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R1
    : <<S0-0c,S0>>&lt;2&gt;::<<S0-09,S1>>;
----

=== Base Classes

[,cols=2]
|===
| Name
| Description
| `<<S0-0c,S0>>&lt;2&gt;::<<S0-09,S1>>`
| 
|===

[#R2]
== R2

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R2
    : <<S0-073,S0>>&lt;3&gt;;
----

=== Base Classes

[,cols=2]
|===
| Name
| Description
| `<<S0-073,S0>>&lt;3&gt;`
| 
|===

[#S0-0c]
== S0

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    int I,
    typename T = void&gt;
struct S0;
----

=== Types

[cols=1]
|===
| Name
| <<S0-0c-S1,`S1`>> 
|===

=== Derived Classes

[,cols=2]
|===
| Name
| Description
| <<R0,`R0`>>
| 
|===

[#S0-0c-S1]
== <<S0-0c,S0>>::S1

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct S1;
----

[#S0-09]
== S0&lt;2&gt;

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<S0-0c,S0>>&lt;2&gt;;
----

[#S0-073]
== S0&lt;3&gt;

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<S0-0c,S0>>&lt;3&gt;;
----

=== Derived Classes

[,cols=2]
|===
| Name
| Description
| <<R2,`R2`>>
| 
|===

[#S0-0e]
== S0&lt;5&gt;

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<S0-0c,S0>>&lt;5&gt;;
----

=== Types

[cols=1]
|===
| Name
| <<S0-0e-S1,`S1`>> 
|===

[#S0-0e-S1]
== <<S0-0e,S0>>&lt;5&gt;::S1

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct S1;
----

[#S0-07e]
== S0&lt;6&gt;

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<S0-0c,S0>>&lt;6&gt;;
----


[.small]#Created with https://www.mrdocs.com[MrDocs]#
