= Reference
:mrdocs:

[#index]
== Global namespace

=== Types

[cols=1]
|===
| Name
| link:#R0[`R0`] 
| link:#R1[`R1`] 
| link:#R2[`R2`] 
| link:#S0-0c[`S0`] 
| link:#S0-09[`S0&lt;2&gt;`] 
| link:#S0-073[`S0&lt;3&gt;`] 
| link:#S0-0e[`S0&lt;5&gt;`] 
| link:#S0-07e[`S0&lt;6&gt;`] 
| link:#U1[`U1`] 
| link:#U2[`U2`] 
| link:#U3[`U3`] 
|===

[#U1]
== U1

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using U1 = link:#S0-0c[S0&lt;4&gt;];
----

[#U2]
== U2

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using U2 = link:#S0-0e-S1[S0&lt;5&gt;::S1];
----

[#U3]
== U3

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using U3 = link:#S0-07e[S0&lt;6&gt;];
----

[#R0]
== R0

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R0
    : link:#S0-0c[S0&lt;1&gt;]
----

=== Base Classes

[cols=2]
|===
| Name
| Description
| `link:#S0-0c[S0&lt;1&gt;]`
| 
|===

=== Types

[cols=1]
|===
| Name
| link:#S0-0c-S1[`S1`] 
|===

[#R1]
== R1

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R1
    : link:#S0-09[S0&lt;2&gt;::S1]
----

=== Base Classes

[cols=2]
|===
| Name
| Description
| `link:#S0-09[S0&lt;2&gt;::S1]`
| 
|===

[#R2]
== R2

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R2
    : link:#S0-073[S0&lt;3&gt;]
----

=== Base Classes

[cols=2]
|===
| Name
| Description
| `link:#S0-073[S0&lt;3&gt;]`
| 
|===

[#S0-0c]
== S0

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    int I,
    typename T = void&gt;
struct S0;
----

=== Types

[cols=1]
|===
| Name
| link:#S0-0c-S1[`S1`] 
|===

=== Derived Classes

[cols=2]
|===
| Name
| Description
| link:#R0[`R0`]
| 
|===

[#S0-0c-S1]
== link:#S0-0c[S0]::S1

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct S1;
----

[#S0-09]
== link:#S0-0c[S0]&lt;2&gt;

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#S0-0c[S0]&lt;2&gt;;
----

[#S0-073]
== link:#S0-0c[S0]&lt;3&gt;

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#S0-0c[S0]&lt;3&gt;;
----

=== Derived Classes

[cols=2]
|===
| Name
| Description
| link:#R2[`R2`]
| 
|===

[#S0-0e]
== link:#S0-0c[S0]&lt;5&gt;

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#S0-0c[S0]&lt;5&gt;;
----

=== Types

[cols=1]
|===
| Name
| link:#S0-0e-S1[`S1`] 
|===

[#S0-0e-S1]
== link:#S0-0e[S0&lt;5&gt;]::S1

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct S1;
----

[#S0-07e]
== link:#S0-0c[S0]&lt;6&gt;

=== Synopsis

Declared in `&lt;template&hyphen;specialization&hyphen;inheritance&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#S0-0c[S0]&lt;6&gt;;
----


[.small]#Created with https://www.mrdocs.com[MrDocs]#
