= Reference
:mrdocs:

[#index]
== Global namespace

=== Types

[cols=1]
|===
| Name
| <<S0-03,`S0`>> 
| <<S0-00,`S0&lt;void&gt;`>> 
| <<A5,`A5`>> 
| <<A9,`A9`>> 
|===

[#A5]
== A5

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using A5 = <<S0-03,S0>>&lt;void&gt;;
----

[#A9]
== A9

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using A9 = <<A5,A5>>::<<S0-00-S2-0d,S2>>&lt;char&gt;::<<S0-00-S2-02-M3,M3>>&lt;int&gt;::<<S0-00-S2-02-M3,M3>>&lt;unsigned int&gt;::<<S0-00-S2-02-M2,M2>>;
----

[#S0-03]
== S0

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
struct S0;
----

=== Types

[cols=1]
|===
| Name
| <<S0-03-S2,`S2`>> 
|===

[#S0-03-S2]
== <<S0-03,S0>>::S2

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct S2;
----

=== Types

[cols=1]
|===
| Name
| <<S0-03-S2-M2,`M2`>> 
| <<S0-03-S2-M3,`M3`>> 
|===

[#S0-03-S2-M2]
== <<S0-03,S0>>::<<S0-03-S2,S2>>::M2

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using M2 = U;
----

[#S0-03-S2-M3]
== <<S0-03,S0>>::<<S0-03-S2,S2>>::M3

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
using M3 = <<S0-03-S2,S2>>&lt;U&gt;;
----

[#S0-00]
== <<S0-03,S0>>&lt;void&gt;

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<S0-03,S0>>&lt;void&gt;;
----

=== Types

[cols=1]
|===
| Name
| <<S0-00-S2-0d,`S2`>> 
| <<S0-00-S2-02,`S2&lt;char&gt;`>> 
|===

[#S0-00-S2-0d]
== <<S0-00,S0&lt;void&gt;>>::S2

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct S2;
----

[#S0-00-S2-02]
== <<S0-00,S0&lt;void&gt;>>::<<S0-03-S2,S2>>&lt;char&gt;

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<S0-03-S2,S2>>&lt;char&gt;;
----

=== Types

[cols=1]
|===
| Name
| <<S0-00-S2-02-M2,`M2`>> 
| <<S0-00-S2-02-M3,`M3`>> 
|===

[#S0-00-S2-02-M2]
== <<S0-00,S0&lt;void&gt;>>::<<S0-00-S2-02,S2&lt;char&gt;>>::M2

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using M2 = char;
----

[#S0-00-S2-02-M3]
== <<S0-00,S0&lt;void&gt;>>::<<S0-00-S2-02,S2&lt;char&gt;>>::M3

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
using M3 = <<S0-00-S2-0d,S2>>&lt;char&gt;;
----


[.small]#Created with https://www.mrdocs.com[MrDocs]#
