= Reference
:mrdocs:

[#index]
== Global namespace

=== Namespaces

[cols=1]
|===
| Name
| link:#A[`A`] 
|===

=== Using Declarations

[cols=2]
|===
| Name
| Description
| link:#f[`f`] 
| f overloads are also available in the global namespace
|===

[#A]
== A

=== Functions

[cols=2]
|===
| Name
| Description
| link:#A-f-08[`f`] 
| `f` overloads
|===

[#A-f-08]
== link:#A[A]::f

`f` overloads

=== Synopses

Declared in `&lt;using&hyphen;function&hyphen;after&period;cpp&gt;`

A non&hyphen;shadowing declaration


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
link:#A-f-00[f](char);
----

[.small]#link:#A-f-00[_» more&period;&period;&period;_]#

A shadow declaration


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
link:#A-f-01[f](int);
----

[.small]#link:#A-f-01[_» more&period;&period;&period;_]#

[#A-f-00]
== link:#A[A]::f

A non&hyphen;shadowing declaration

=== Synopsis

Declared in `&lt;using&hyphen;function&hyphen;after&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f(char);
----

=== Description

This declaration is not part of the shadow declarations of the using directive because it comes after it&period;

Only the declarations at the point of the using directive are considered for shadowing in the documentation&period;

[#A-f-01]
== link:#A[A]::f

A shadow declaration

=== Synopsis

Declared in `&lt;using&hyphen;function&hyphen;after&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f(int);
----

[#f]
== f

f overloads are also available in the global namespace

=== Synopsis

Declared in `&lt;using&hyphen;function&hyphen;after&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using A::f;
----

=== Introduced Symbols

[cols=2]
|===
| Name
| Description
| link:#A-f-01[A::f]
| A shadow declaration
|===

[.small]#Created with https://www.mrdocs.com[MrDocs]#
