= Reference
:mrdocs:

[#index]
== Global namespace

=== Types

[cols=2]
|===
| Name
| Description
| link:#A[`A`] 
| This struct will be inherited as public
| link:#B[`B`] 
| This struct will be inherited as public
| link:#C[`C`] 
| This struct will be inherited as protected
| link:#D[`D`] 
| This struct will be inherited as protected
| link:#E[`E`] 
| This struct will be inherited as private
| link:#F[`F`] 
| This struct will be inherited as private
| link:#Tag[`Tag`] 
| A tag template to create distinct f functions&period;
| link:#U[`U`] 
| This struct inherits from A, B, C, D, E, and F in various ways,
|===

[#A]
== A

This struct will be inherited as public

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct A;
----

=== Member Functions

[cols=2]
|===
| Name
| Description
| link:#A-f[`f`] 
| Public member function f taking a Tag&lt;0&gt;&period;
|===

=== Derived Classes

[cols=2]
|===
| Name
| Description
| link:#U[`U`]
| This struct inherits from A, B, C, D, E, and F in various ways,
|===

[#A-f]
== link:#A[A]::f

Public member function f taking a Tag&lt;0&gt;&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f(link:#Tag[Tag&lt;0&gt;]);
----

=== Description

That is the only member function that will be publicly accessible in U via inheritance&period;

[#B]
== B

This struct will be inherited as public

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct B;
----

=== Protected Member Functions

[cols=2]
|===
| Name
| Description
| link:#B-f[`f`] 
| Protected member function f taking a Tag&lt;1&gt;&period;
|===

=== Derived Classes

[cols=2]
|===
| Name
| Description
| link:#U[`U`]
| This struct inherits from A, B, C, D, E, and F in various ways,
|===

[#B-f]
== link:#B[B]::f

Protected member function f taking a Tag&lt;1&gt;&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f(link:#Tag[Tag&lt;1&gt;]);
----

[#C]
== C

This struct will be inherited as protected

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----

=== Member Functions

[cols=2]
|===
| Name
| Description
| link:#C-f[`f`] 
| Public member function f taking a Tag&lt;2&gt;&period;
|===

[#C-f]
== link:#C[C]::f

Public member function f taking a Tag&lt;2&gt;&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f(link:#Tag[Tag&lt;2&gt;]);
----

[#D]
== D

This struct will be inherited as protected

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct D;
----

=== Protected Member Functions

[cols=2]
|===
| Name
| Description
| link:#D-f[`f`] 
| Protected member function f taking a Tag&lt;3&gt;&period;
|===

[#D-f]
== link:#D[D]::f

Protected member function f taking a Tag&lt;3&gt;&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f(link:#Tag[Tag&lt;3&gt;]);
----

[#E]
== E

This struct will be inherited as private

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct E;
----

=== Member Functions

[cols=2]
|===
| Name
| Description
| link:#E-f[`f`] 
| Public member function f taking a Tag&lt;4&gt;&period;
|===

[#E-f]
== link:#E[E]::f

Public member function f taking a Tag&lt;4&gt;&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f(link:#Tag[Tag&lt;4&gt;]);
----

[#F]
== F

This struct will be inherited as private

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct F;
----

=== Protected Member Functions

[cols=2]
|===
| Name
| Description
| link:#F-f[`f`] 
| Protected member function f taking a Tag&lt;5&gt;&period;
|===

[#F-f]
== link:#F[F]::f

Protected member function f taking a Tag&lt;5&gt;&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f(link:#Tag[Tag&lt;5&gt;]);
----

[#Tag]
== Tag

A tag template to create distinct f functions&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;int idx&gt;
struct Tag;
----

[#U]
== U

This struct inherits from A, B, C, D, E, and F in various ways,

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct U
    : link:#A[A]
    , link:#B[B]
    , protected link:#C[C]
    , protected link:#D[D]
----

=== Base Classes

[cols=2]
|===
| Name
| Description
| `link:#A[A]`
| This struct will be inherited as public
| `link:#B[B]`
| This struct will be inherited as public
|===

=== Protected Base Classes

[cols=2]
|===
| Name
| Description
| `link:#C[C]`
| This struct will be inherited as protected
| `link:#D[D]`
| This struct will be inherited as protected
|===

=== Member Functions

[cols=2]
|===
| Name
| Description
| link:#U-f-0f0[`f`] 
| `f` overloads
|===

=== Using Declarations

[cols=2]
|===
| Name
| Description
| link:#U-U-0a[`U`] 
| Bring all the A&colon;&colon;A constructors into U&period;
| link:#U-U-01b[`U`] 
| Bring all the B&colon;&colon;B constructors into U&period;
| link:#U-U-01d[`U`] 
| Bring all the C&colon;&colon;C constructors into U&period;
| link:#U-U-0c[`U`] 
| Bring all the D&colon;&colon;D constructors into U&period;
| link:#U-U-04[`U`] 
| Bring all the E&colon;&colon;E constructors into U&period;
| link:#U-U-06[`U`] 
| Bring all the F&colon;&colon;F constructors into U&period;
| link:#U-f-00c[`f`] 
| Bring all the A&colon;&colon;f functions into U&period;
| link:#U-f-0be[`f`] 
| Bring all the B&colon;&colon;f functions into U&period;
| link:#U-f-0f7[`f`] 
| Bring all the C&colon;&colon;f functions into U&period;
| link:#U-f-009[`f`] 
| Bring all the D&colon;&colon;f functions into U&period;
| link:#U-f-0bd[`f`] 
| Bring all the E&colon;&colon;f functions into U&period;
| link:#U-f-02[`f`] 
| Bring all the F&colon;&colon;f functions into U&period;
|===

=== Protected Member Functions

[cols=2]
|===
| Name
| Description
| link:#U-f-07[`f`] 
| `f` overloads
|===

=== Description

The documentation of this struct should include the function f twice&colon; once in the member functions

[#U-f-0f0]
== link:#U[U]::f

`f` overloads

=== Synopses

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

Public member function f taking a Tag&lt;0&gt;&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
link:#A-f[f](link:#Tag[Tag&lt;0&gt;]);
----

[.small]#link:#A-f[_» more&period;&period;&period;_]#

Public member function f taking a Tag&lt;2&gt;&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
link:#C-f[f](link:#Tag[Tag&lt;2&gt;]);
----

[.small]#link:#C-f[_» more&period;&period;&period;_]#

[#A-f]
== link:#A[A]::f

Public member function f taking a Tag&lt;0&gt;&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f(link:#Tag[Tag&lt;0&gt;]);
----

=== Description

That is the only member function that will be publicly accessible in U via inheritance&period;

[#C-f]
== link:#C[C]::f

Public member function f taking a Tag&lt;2&gt;&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f(link:#Tag[Tag&lt;2&gt;]);
----

[#U-U-0a]
== link:#U[U]::U

Bring all the A&colon;&colon;A constructors into U&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using A::U;
----

[#U-U-01b]
== link:#U[U]::U

Bring all the B&colon;&colon;B constructors into U&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using B::U;
----

[#U-U-01d]
== link:#U[U]::U

Bring all the C&colon;&colon;C constructors into U&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using C::U;
----

[#U-U-0c]
== link:#U[U]::U

Bring all the D&colon;&colon;D constructors into U&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using D::U;
----

[#U-U-04]
== link:#U[U]::U

Bring all the E&colon;&colon;E constructors into U&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using E::U;
----

[#U-U-06]
== link:#U[U]::U

Bring all the F&colon;&colon;F constructors into U&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using F::U;
----

[#U-f-00c]
== link:#U[U]::f

Bring all the A&colon;&colon;f functions into U&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using A::f;
----

=== Introduced Symbols

[cols=2]
|===
| Name
| Description
| link:#A-f[A::f]
| Public member function f taking a Tag&lt;0&gt;&period;
|===
[#U-f-0be]
== link:#U[U]::f

Bring all the B&colon;&colon;f functions into U&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using B::f;
----

=== Introduced Symbols

[cols=2]
|===
| Name
| Description
| link:#B-f[B::f]
| Protected member function f taking a Tag&lt;1&gt;&period;
|===
[#U-f-0f7]
== link:#U[U]::f

Bring all the C&colon;&colon;f functions into U&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using C::f;
----

=== Introduced Symbols

[cols=2]
|===
| Name
| Description
| link:#C-f[C::f]
| Public member function f taking a Tag&lt;2&gt;&period;
|===
[#U-f-009]
== link:#U[U]::f

Bring all the D&colon;&colon;f functions into U&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using D::f;
----

=== Introduced Symbols

[cols=2]
|===
| Name
| Description
| link:#D-f[D::f]
| Protected member function f taking a Tag&lt;3&gt;&period;
|===
[#U-f-0bd]
== link:#U[U]::f

Bring all the E&colon;&colon;f functions into U&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using E::f;
----

=== Introduced Symbols

[cols=2]
|===
| Name
| Description
| link:#E-f[E::f]
| Public member function f taking a Tag&lt;4&gt;&period;
|===
[#U-f-02]
== link:#U[U]::f

Bring all the F&colon;&colon;f functions into U&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using F::f;
----

=== Introduced Symbols

[cols=2]
|===
| Name
| Description
| link:#F-f[F::f]
| Protected member function f taking a Tag&lt;5&gt;&period;
|===
[#U-f-07]
== link:#U[U]::f

`f` overloads

=== Synopses

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

Protected member function f taking a Tag&lt;1&gt;&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
link:#B-f[f](link:#Tag[Tag&lt;1&gt;]);
----

[.small]#link:#B-f[_» more&period;&period;&period;_]#

Protected member function f taking a Tag&lt;3&gt;&period;


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
link:#D-f[f](link:#Tag[Tag&lt;3&gt;]);
----

[.small]#link:#D-f[_» more&period;&period;&period;_]#

[#B-f]
== link:#B[B]::f

Protected member function f taking a Tag&lt;1&gt;&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f(link:#Tag[Tag&lt;1&gt;]);
----

[#D-f]
== link:#D[D]::f

Protected member function f taking a Tag&lt;3&gt;&period;

=== Synopsis

Declared in `&lt;using&hyphen;member&hyphen;function&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f(link:#Tag[Tag&lt;3&gt;]);
----


[.small]#Created with https://www.mrdocs.com[MrDocs]#
