//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// Copyright (c) 2025 Alan de Freitas (alandefreitas@gmail.com)
//
// Official repository: https://github.com/cppalliance/mrdocs
//

#ifndef INFO
#define INFO(PascalName)
#endif

INFO(Reference)
INFO(CopyDetails)
INFO(Link)
INFO(Text)
INFO(SoftBreak)
INFO(LineBreak)
INFO(Code)
INFO(Emph)
INFO(Strong)
INFO(Image)
INFO(FootnoteReference)
INFO(Strikethrough)
INFO(Math)
INFO(Superscript)
INFO(Subscript)
INFO(Highlight)

#undef INFO
