= Mr.Docs Website

The Mr.Docs website is quite simple:

- An landing page with examples
- The documentation

The landing page is a simple `index.html` file with a few example panels.
It is generated from a `index.html.hbs` file using handlebars.
The data for the page comes from `data.json`.

To generate the index.html page from index.html.hbs, run:

[source,sh]
----
MRDOCS_ROOT=/path/to/mrdocs
export MRDOCS_ROOT
npm ci
node render.js
----

The landing page also includes a link to the documentation.
The documentation is an Antora project also generated by the CI pipeline.

== Adding snippets

The landing page includes snippets of code and their corresponding documentation.
These snippets are defined in `data.json` in the `panels` array.

Each panel has a snippet of code that is tested as part of the Mr.Docs test suite.
When the template is rendered, the script will run Mr.Docs on each snippet and include the output in the panel.

To add a new panel, add a new object to the `panels` array in `data.json`.
The panel has a `snippet` key that contains the relative path of the snippet in the `snippets` directory.
The `snippet` must always match the name of the symbol that should be documented and included in the panel.
