= Reference
:mrdocs:

[#index]
== Global namespace


=== Functions

[cols=1]
|===
| Name 

| <<f0,`f0`>> 

| <<f1,`f1`>> 

| <<f2,`f2`>> 

| <<f3,`f3`>> 

| <<g0,`g0`>> 

| <<g1,`g1`>> 

| <<g2,`g2`>> 

| <<h0,`h0`>> 

| <<h1,`h1`>> 

| <<i,`i`>> 

| <<j0,`j0`>> 

| <<j1,`j1`>> 

|===

[#f0]
== f0


=== Synopsis


Declared in `&lt;function&hyphen;template&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
void
f0(int x);
----

[#f1]
== f1


=== Synopsis


Declared in `&lt;function&hyphen;template&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
void
f1(T t);
----

[#f2]
== f2


=== Synopsis


Declared in `&lt;function&hyphen;template&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T = int&gt;
void
f2();
----

[#f3]
== f3


=== Synopsis


Declared in `&lt;function&hyphen;template&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename T,
    class U = int&gt;
void
f3();
----

[#g0]
== g0


=== Synopsis


Declared in `&lt;function&hyphen;template&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;int I&gt;
void
g0(int x);
----

[#g1]
== g1


=== Synopsis


Declared in `&lt;function&hyphen;template&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;int I = 1&gt;
void
g1();
----

[#g2]
== g2


=== Synopsis


Declared in `&lt;function&hyphen;template&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    int J,
    int I = 1&gt;
void
g2();
----

[#h0]
== h0


=== Synopsis


Declared in `&lt;function&hyphen;template&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class x&colon;auto&gt;
void
h0(auto x);
----

[#h1]
== h1


=== Synopsis


Declared in `&lt;function&hyphen;template&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    class x&colon;auto,
    class auto&colon;2&gt;
void
h1(
    auto x,
    auto);
----

[#i]
== i


=== Synopsis


Declared in `&lt;function&hyphen;template&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename T = int,
    int I = 1&gt;
void
i();
----

[#j0]
== j0


=== Synopsis


Declared in `&lt;function&hyphen;template&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;template&lt;typename U&gt; typename T&gt;
void
j0();
----

[#j1]
== j1


=== Synopsis


Declared in `&lt;function&hyphen;template&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    template&lt;typename W&gt; typename X,
    template&lt;typename Y&gt; typename Z&gt;
void
j1();
----



[.small]#Created with https://www.mrdocs.com[MrDocs]#
