= Reference
:mrdocs:

[#index]
== Global namespace

=== Namespaces

[cols=1]
|===
| Name
| <<B,`B`>> 
|===

=== Types

[cols=2]
|===
| Name
| Description
| <<A-09,`A`>> 
| The partial specialization of A is enabled via a template parameter
| <<A-02,`A&lt;T&gt;`>> 
| Specialization for floating point types
| <<S-02,`S`>> 
| SFINAE with std&colon;&colon;void&lowbar;t
| <<S-08,`S&lt;T, std::void&lowbar;t&lt;T::a::b&gt;&gt;`>> 
| SFINAE with std&colon;&colon;void&lowbar;t
|===

=== Functions

[cols=2]
|===
| Name
| Description
| <<f1,`f1`>> 
| Enabled via return type
| <<f10,`f10`>> 
| Enabled via type template parameter
| <<f2,`f2`>> 
| Enabling a specified return type
| <<f3,`f3`>> 
| Enabling a specified return type in another namespace
| <<f4,`f4`>> 
| Enabled via return type with std&colon;&colon;enable&lowbar;if
| <<f5,`f5`>> 
| Enabled via a non&hyphen;type template parameter with helper
| <<f6,`f6`>> 
| Enabled via a non&hyphen;type template parameter without helper
| <<f7,`f7`>> 
| Enabled via a non&hyphen;type template parameter using int instead of bool
| <<f8,`f8`>> 
| Enabled via parameter without helper
| <<f9,`f9`>> 
| Enabled via parameter with helper
|===

[#B]
== B

=== Types

[cols=2]
|===
| Name
| Description
| <<B-C,`C`>> 
| 
|===

[#B-C]
== <<B,B>>::C

=== Synopsis

Declared in `&lt;sfinae&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----

=== Non-Member Functions

[cols=2]
|===
| Name
| Description
| <<f3,`&colon;&colon;f3`>>
| Enabling a specified return type in another namespace
|===

[#A-09]
== A

The partial specialization of A is enabled via a template parameter

=== Synopsis

Declared in `&lt;sfinae&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    class T,
    class Enable = void&gt;
class A;
----

[#A-02]
== A&lt;T&gt;

Specialization for floating point types

=== Synopsis

Declared in `&lt;sfinae&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class T&gt;
requires std&colon;&colon;is&lowbar;integral&lowbar;v&lt;T&gt;
class <<A-09,A>>&lt;T&gt;;
----

[#S-02]
== S

SFINAE with std&colon;&colon;void&lowbar;t

=== Synopsis

Declared in `&lt;sfinae&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    class T,
    class Enable = void&gt;
struct S;
----

=== Member Functions

[cols=1]
|===
| Name
| <<S-02-store,`store`>> 
|===

[#S-02-store]
== <<S-02,S>>::store

=== Synopsis

Declared in `&lt;sfinae&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
store(void const*);
----

[#S-08]
== S&lt;T, std::void&lowbar;t&lt;T::a::b&gt;&gt;

SFINAE with std&colon;&colon;void&lowbar;t

=== Synopsis

Declared in `&lt;sfinae&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class T&gt;
struct <<S-02,S>>&lt;T, std::void&lowbar;t&lt;T::a::b&gt;&gt;;
----

=== Member Functions

[cols=1]
|===
| Name
| <<S-08-store,`store`>> 
|===

[#S-08-store]
== <<S-08,S>>&lt;T, std::void&lowbar;t&lt;T::a::b&gt;&gt;::store

=== Synopsis

Declared in `&lt;sfinae&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
store(void const*);
----

[#f1]
== f1

Enabled via return type

=== Synopsis

Declared in `&lt;sfinae&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class T&gt;
T
f1(T value)
requires std&colon;&colon;is&lowbar;integral&lowbar;v&lt;T&gt;;
----

[#f10]
== f10

Enabled via type template parameter

=== Synopsis

Declared in `&lt;sfinae&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class T&gt;
requires std&colon;&colon;is&lowbar;integral&lowbar;v&lt;T&gt;
void
f10(T value);
----

=== Description

This pattern should not be used because the function signature is unmodified and therefore only supports one overload&period;

It&apos;s a common mistake is to declare two function templates that differ only in their default template arguments&period;

This does not work because the declarations are treated as redeclarations of the same function template (default template arguments are not accounted for in function template equivalence)&period;

[#f2]
== f2

Enabling a specified return type

=== Synopsis

Declared in `&lt;sfinae&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class T&gt;
int
f2(T value)
requires std&colon;&colon;is&lowbar;integral&lowbar;v&lt;T&gt;;
----

[#f3]
== f3

Enabling a specified return type in another namespace

=== Synopsis

Declared in `&lt;sfinae&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class T&gt;
<<B,B>>::<<B-C,C>>
f3(T value)
requires std&colon;&colon;is&lowbar;integral&lowbar;v&lt;T&gt;;
----

[#f4]
== f4

Enabled via return type with std&colon;&colon;enable&lowbar;if

=== Synopsis

Declared in `&lt;sfinae&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class T&gt;
T
f4(T value)
requires std&colon;&colon;is&lowbar;integral&lowbar;v&lt;T&gt;;
----

[#f5]
== f5

Enabled via a non&hyphen;type template parameter with helper

=== Synopsis

Declared in `&lt;sfinae&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class T&gt;
requires std&colon;&colon;is&lowbar;integral&lowbar;v&lt;T&gt;
T
f5(T value);
----

[#f6]
== f6

Enabled via a non&hyphen;type template parameter without helper

=== Synopsis

Declared in `&lt;sfinae&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class T&gt;
requires std&colon;&colon;is&lowbar;integral&lowbar;v&lt;T&gt;
T
f6(T value);
----

[#f7]
== f7

Enabled via a non&hyphen;type template parameter using int instead of bool

=== Synopsis

Declared in `&lt;sfinae&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class T&gt;
requires std&colon;&colon;is&lowbar;integral&lowbar;v&lt;T&gt;
void
f7(T value);
----

[#f8]
== f8

Enabled via parameter without helper

=== Synopsis

Declared in `&lt;sfinae&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class T&gt;
T
f8(T value)
requires std&colon;&colon;is&lowbar;integral&lowbar;v&lt;T&gt;;
----

[#f9]
== f9

Enabled via parameter with helper

=== Synopsis

Declared in `&lt;sfinae&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;class T&gt;
T
f9(T value)
requires std&colon;&colon;is&lowbar;integral&lowbar;v&lt;T&gt;;
----


[.small]#Created with https://www.mrdocs.com[MrDocs]#
