= Reference
:mrdocs:

[#index]
== Global namespace

=== Types

[cols=1]
|===
| Name
| link:#A-0e[`A`] 
| link:#A-0f[`A&lt;bool&gt;`] 
| link:#A-00b[`A&lt;short&gt;`] 
| link:#A-000[`A&lt;int&gt;`] 
| link:#D[`D`] 
|===

[#A-0e]
== A

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
struct A;
----

=== Types

[cols=1]
|===
| Name
| link:#A-0e-B[`B`] 
| link:#A-0e-C[`C`] 
|===

=== Member Functions

[cols=1]
|===
| Name
| link:#A-0e-f[`f`] 
|===

[#A-0e-B]
== link:#A-0e[A]::B

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct B;
----

=== Member Functions

[cols=1]
|===
| Name
| link:#A-0e-B-g[`g`] 
|===

[#A-0e-B-g]
== link:#A-0e[A]::link:#A-0e-B[B]::g

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
g();
----

[#A-0e-C]
== link:#A-0e[A]::C

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct C;
----

=== Member Functions

[cols=1]
|===
| Name
| link:#A-0e-C-h[`h`] 
|===

[#A-0e-C-h]
== link:#A-0e[A]::link:#A-0e-C[C]::h

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
h();
----

[#A-0e-f]
== link:#A-0e[A]::f

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f();
----

[#A-0f]
== link:#A-0e[A]&lt;bool&gt;

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e[A]&lt;bool&gt;;
----

=== Types

[cols=1]
|===
| Name
| link:#A-0f-B[`B`] 
| link:#A-0f-C-00[`C`] 
| link:#A-0f-C-01[`C&lt;double*&gt;`] 
| link:#A-0f-C-0c[`C&lt;U*&gt;`] 
|===

=== Member Functions

[cols=1]
|===
| Name
| link:#A-0f-f[`f`] 
|===

[#A-0f-B]
== link:#A-0f[A&lt;bool&gt;]::B

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct B;
----

[#A-0f-C-00]
== link:#A-0f[A&lt;bool&gt;]::C

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct C;
----

[#A-0f-C-01]
== link:#A-0f[A&lt;bool&gt;]::link:#A-0e-C[C]&lt;double*&gt;

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e-C[C]&lt;double*&gt;;
----

=== Member Functions

[cols=1]
|===
| Name
| link:#A-0f-C-01-j[`j`] 
|===

[#A-0f-C-01-j]
== link:#A-0f[A&lt;bool&gt;]::link:#A-0f-C-01[C&lt;double*&gt;]::j

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
j();
----

[#A-0f-C-0c]
== link:#A-0f[A&lt;bool&gt;]::link:#A-0e-C[C]&lt;U*&gt;

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct link:#A-0e-C[C]&lt;U*&gt;;
----

=== Member Functions

[cols=1]
|===
| Name
| link:#A-0f-C-0c-j[`j`] 
|===

[#A-0f-C-0c-j]
== link:#A-0f[A&lt;bool&gt;]::link:#A-0f-C-0c[C&lt;U*&gt;]::j

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
j();
----

[#A-0f-f]
== link:#A-0f[A&lt;bool&gt;]::f

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f();
----

[#A-00b]
== link:#A-0e[A]&lt;short&gt;

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e[A]&lt;short&gt;;
----

=== Types

[cols=1]
|===
| Name
| link:#A-00b-B[`B`] 
| link:#A-00b-C[`C`] 
|===

=== Member Functions

[cols=1]
|===
| Name
| link:#A-00b-f[`f`] 
|===

[#A-00b-B]
== link:#A-00b[A&lt;short&gt;]::B

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct B;
----

[#A-00b-C]
== link:#A-00b[A&lt;short&gt;]::C

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct C;
----

=== Member Functions

[cols=1]
|===
| Name
| link:#A-00b-C-i[`i`] 
|===

[#A-00b-C-i]
== link:#A-00b[A&lt;short&gt;]::link:#A-00b-C[C]::i

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
i();
----

[#A-00b-f]
== link:#A-00b[A&lt;short&gt;]::f

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f();
----

[#A-000]
== link:#A-0e[A]&lt;int&gt;

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e[A]&lt;int&gt;;
----

=== Types

[cols=1]
|===
| Name
| link:#A-000-B-03[`B`] 
| link:#A-000-B-09[`B&lt;long&gt;`] 
| link:#A-000-C[`C`] 
|===

=== Member Functions

[cols=1]
|===
| Name
| link:#A-000-f[`f`] 
|===

[#A-000-B-03]
== link:#A-000[A&lt;int&gt;]::B

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct B;
----

[#A-000-B-09]
== link:#A-000[A&lt;int&gt;]::link:#A-0e-B[B]&lt;long&gt;

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#A-0e-B[B]&lt;long&gt;;
----

=== Member Functions

[cols=1]
|===
| Name
| link:#A-000-B-09-g[`g`] 
|===

[#A-000-B-09-g]
== link:#A-000[A&lt;int&gt;]::link:#A-000-B-09[B&lt;long&gt;]::g

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
g();
----

[#A-000-C]
== link:#A-000[A&lt;int&gt;]::C

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct C;
----

[#A-000-f]
== link:#A-000[A&lt;int&gt;]::f

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f();
----

[#D]
== D

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct D;
----

=== Types

[cols=1]
|===
| Name
| link:#D-E-0e[`E`] 
| link:#D-E-0d[`E&lt;int&gt;`] 
|===

[#D-E-0e]
== link:#D[D]::E

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
struct E;
----

=== Member Functions

[cols=1]
|===
| Name
| link:#D-E-0e-k[`k`] 
|===

[#D-E-0e-k]
== link:#D[D]::link:#D-E-0e[E]::k

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
k();
----

[#D-E-0d]
== link:#D[D]::link:#D-E-0e[E]&lt;int&gt;

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct link:#D-E-0e[E]&lt;int&gt;;
----

=== Member Functions

[cols=1]
|===
| Name
| link:#D-E-0d-k[`k`] 
|===

[#D-E-0d-k]
== link:#D[D]::link:#D-E-0d[E&lt;int&gt;]::k

=== Synopsis

Declared in `&lt;spec&hyphen;mem&hyphen;implicit&hyphen;instantiation&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
k();
----


[.small]#Created with https://www.mrdocs.com[MrDocs]#
