= Reference
:mrdocs:

[#index]
== Global namespace

=== Types

[cols=1]
|===
| Name
| link:#A[`A`] 
| link:#B[`B`] 
| link:#C[`C`] 
| link:#D[`D`] 
| link:#E[`E`] 
|===

=== Functions

[cols=1]
|===
| Name
| link:#f0[`f0`] 
| link:#f1[`f1`] 
| link:#f2[`f2`] 
| link:#f3[`f3`] 
| link:#f4[`f4`] 
| link:#f5[`f5`] 
| link:#f6[`f6`] 
| link:#f7[`f7`] 
| link:#f8[`f8`] 
| link:#g0[`g0`] 
| link:#g1[`g1`] 
| link:#g2[`g2`] 
| link:#g3[`g3`] 
| link:#g4[`g4`] 
| link:#g5[`g5`] 
| link:#g6[`g6`] 
| link:#g7[`g7`] 
| link:#g8[`g8`] 
| link:#h0[`h0`] 
| link:#h1[`h1`] 
| link:#h2[`h2`] 
| link:#h3[`h3`] 
| link:#h4[`h4`] 
| link:#h5[`h5`] 
| link:#h6[`h6`] 
| link:#h7[`h7`] 
| link:#h8[`h8`] 
| link:#i0[`i0`] 
| link:#i1[`i1`] 
| link:#i2[`i2`] 
| link:#i3[`i3`] 
| link:#i4[`i4`] 
| link:#i5[`i5`] 
| link:#i6[`i6`] 
| link:#i7[`i7`] 
| link:#i8[`i8`] 
| link:#j0[`j0`] 
| link:#j1[`j1`] 
| link:#j2[`j2`] 
| link:#j3[`j3`] 
| link:#j4[`j4`] 
| link:#j5[`j5`] 
| link:#j6[`j6`] 
| link:#j7[`j7`] 
| link:#j8[`j8`] 
|===

[#C]
== C

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using C = link:#A[A];
----

[#D]
== D

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using D = link:#B[B]&lt;short, long&gt;;
----

[#E]
== E

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
using E = link:#B[B]&lt;T, long&gt;;
----

[#A]
== A

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct A;
----

[#B]
== B

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    typename T,
    typename U&gt;
struct B;
----

[#f0]
== f0

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f0(link:#A[A]);
----

[#f1]
== f1

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f1(link:#A[A] const);
----

[#f2]
== f2

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f2(link:#A[A]&);
----

[#f3]
== f3

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f3(link:#A[A] const&);
----

[#f4]
== f4

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f4(link:#A[A]*);
----

[#f5]
== f5

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f5(link:#A[A] const*);
----

[#f6]
== f6

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f6(link:#A[A]**);
----

[#f7]
== f7

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f7(link:#A[A] const**);
----

[#f8]
== f8

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f8(link:#A[A] const const**);
----

[#g0]
== g0

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
g0(link:#C[C]);
----

[#g1]
== g1

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
g1(link:#C[C] const);
----

[#g2]
== g2

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
g2(link:#C[C]&);
----

[#g3]
== g3

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
g3(link:#C[C] const&);
----

[#g4]
== g4

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
g4(link:#C[C]*);
----

[#g5]
== g5

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
g5(link:#C[C] const*);
----

[#g6]
== g6

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
g6(link:#C[C]**);
----

[#g7]
== g7

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
g7(link:#C[C] const**);
----

[#g8]
== g8

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
g8(link:#C[C] const const**);
----

[#h0]
== h0

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
h0(link:#B[B]&lt;short, long&gt;);
----

[#h1]
== h1

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
h1(link:#B[B]&lt;short, long&gt; const);
----

[#h2]
== h2

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
h2(link:#B[B]&lt;short, long&gt;&);
----

[#h3]
== h3

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
h3(link:#B[B]&lt;short, long&gt; const&);
----

[#h4]
== h4

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
h4(link:#B[B]&lt;short, long&gt;*);
----

[#h5]
== h5

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
h5(link:#B[B]&lt;short, long&gt; const*);
----

[#h6]
== h6

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
h6(link:#B[B]&lt;short, long&gt;**);
----

[#h7]
== h7

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
h7(link:#B[B]&lt;short, long&gt; const**);
----

[#h8]
== h8

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
h8(link:#B[B]&lt;short, long&gt; const const**);
----

[#i0]
== i0

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
i0(link:#D[D]);
----

[#i1]
== i1

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
i1(link:#D[D] const);
----

[#i2]
== i2

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
i2(link:#D[D]&);
----

[#i3]
== i3

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
i3(link:#D[D] const&);
----

[#i4]
== i4

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
i4(link:#D[D]*);
----

[#i5]
== i5

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
i5(link:#D[D] const*);
----

[#i6]
== i6

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
i6(link:#D[D]**);
----

[#i7]
== i7

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
i7(link:#D[D] const**);
----

[#i8]
== i8

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
i8(link:#D[D] const const**);
----

[#j0]
== j0

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
j0(link:#E[E]&lt;short&gt;);
----

[#j1]
== j1

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
j1(link:#E[E]&lt;short&gt; const);
----

[#j2]
== j2

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
j2(link:#E[E]&lt;short&gt;&);
----

[#j3]
== j3

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
j3(link:#E[E]&lt;short&gt; const&);
----

[#j4]
== j4

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
j4(link:#E[E]&lt;short&gt;*);
----

[#j5]
== j5

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
j5(link:#E[E]&lt;short&gt; const*);
----

[#j6]
== j6

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
j6(link:#E[E]&lt;short&gt;**);
----

[#j7]
== j7

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
j7(link:#E[E]&lt;short&gt; const**);
----

[#j8]
== j8

=== Synopsis

Declared in `&lt;type&hyphen;resolution&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
j8(link:#E[E]&lt;short&gt; const const**);
----


[.small]#Created with https://www.mrdocs.com[MrDocs]#
