= The Configuration File

[,yaml]
----
generate: # <.>
concurrency: # <.>
defines: # <.>
ignore-failures: # <.>
input:
  include: # <.>
multipage: # <.>
source-root: # <.>
filters: # <.>
referenced-declarations: # <.>
anonymous-namespaces: # <.>
inaccessible-members: # <.>
inaccessible-bases: # <.>
----
<.> Optional `generate` key
<.> Optional `concurrency` key
<.> Optional `defines` key
<.> Optional `ignore-failures` key
<.> Optional `include` key
<.> Optional `multipage` key
<.> Optional `source-root` key
<.> Optional `filters` key
<.> Optional `referenced-declarations` key
<.> Optional `anonymous-namespaces` key
<.> Optional `inaccessible-members` key
<.> Optional `inaccessible-bases` key

== Available configuration keys

[cols="3,6,1"]
|===
|Keys |Description |Required

|concurrency
|The generator to use. Supported generators are
`adoc`, `html`, and `xml`. Defaults to `adoc`.
|No

|concurrency
|The amount of parallelism desired. 0 to use
the hardware-suggested concurrency.
|No

|defines
|Additional preprocessor directives in the form "NAME=VALUE".
|No

|ignore-failures
|Whether to ignore failures during symbol extraction. `true` or `false`.
|No

|include
|The amount of parallelism desired. 0 to use
the hardware-suggested concurrency.
|No

|multipage
|Whether to emit the reference as a set of files or just one file. `true` or `false`.
|No

|source-root
|The absolute or relative path to the directory containing the
input file hierarchy.
|No

|filters
|Patterns specifying symbols which should be included/excluded.
See xref:filters[specifying filters] for details.
|No

|referenced-declarations
|When to extract external declarations referenced by symbols.
Unconditionally extracted when `always`, never extracted when `never`,
and only extracted when used as a base class/deduced local class return type
when set to `dependency`.
|No

|anonymous-namespaces
|Whether to extract anonymous namespaces. `always` or `never`.
|No

|inaccessible-members
|Whether to extract private/protected members. `always` or `never`.
|No

|inaccessible-bases
|Whether to extract private/protected bases. `always` or `never`.

|===
