= The Configuration File

MrDocs uses a configuration file to control how the documentation is generated.
The file is used to specify options such as the generator to use, additional compilation options, and filters.

Here's an example of a configuration file:

[source,yaml]
--------
include::partial$mrdocs-example.yml[]
--------

The xref:usage.adoc[Usage] page provides a detailed explanation of what to combine options from the configuration file and the command line.

The <<config-options-reference>> section provides a detailed explanation of the options available.

More information about the generators can be found in the xref:generators.adoc[Generators] page.

== YAML Schema

To get linting and autocompletion in the config file, a schema for the config can be specified. The schema for `mrdocs.yml` is provided xref:attachment$mrdocs.schema.json[here].

The schema for `mrdocs.yml` is available from https://www.schemastore.org/json/, which is automatically detected and used by most editors.

To manually set the schema in an editor, the following can be used:

* In JetBrains IDEs, `# $schema: <url>` can be used to bind a schema to a file.
* In editors with plugins based on the https://github.com/redhat-developer/yaml-language-server[YAML language server], `# yaml-language-server: $schema=<url>` can be used.

The following shows an example of a file specifying an inline-schema that's compatible with JetBrains IDEs and editors using the YAML language server.

[source,yaml]
--------
include::partial$mrdocs-schema-example.yml[]
--------

== Build Options

A number of options can be used to specify with which compile options MrDocs should be run.

[source,yaml]
----
source-root: ..
compilation-database: ../CMakeLists.txt
cmake: '-D MRDOCS_BUILD=ON'
defines: 'MRDOCS_BUILD'
----

The compile options primarily come from the `compilation-database` file.
When this file is generated from a `CMakeLists.txt` script, the `cmake` option can be used to specify additional options to pass to CMake.

Additionally, the `defines` option can be used to specify preprocessor definitions that should be used when generating the documentation.
These definitions are included in all targets of the compilation database.

== Filters

Not all symbols in a project may be relevant to the documentation.
MrDocs provides a way to filter out symbols based on their location and names.

=== File Filters

Symbols can also be filtered based on the files where they are declared. This can be useful for excluding files that exclusively contain implementation details or test code.

The `input` option is a list of directories to include and a list of file patterns to include. Only symbols in files from these directories will be extracted.

[,yaml]
----
input:
  - ../include
----

The default value for `input` is `"<source-root>/."`, so only symbols defined in your project source directory will be extracted.

The `file-patterns` options allows you to specify a list of glob file patterns to include. Only symbols in files whose filename match these patterns will be extracted.

[,yaml]
----
file-patterns:
  - '*.hpp'
  - '*.h'
----

The default value for `file-patterns` include a variety of common C++ header file extensions.

The `exclude` option is a list of subdirectories in `input` we want to exclude. Meanwhile, `exclude-patterns` can use glob patterns to exclude files from the extraction process.

[,yaml]
----
input:
  - ../include
exclude:
  - ../include/detail
exclude-patterns:
  - ../include/*/detail/**
  - ../include/*/impl/**
----

The glob patterns support the following wildcards:

* `*` matches all characters except delimiters `/`
* `**` matches all characters
* `?` matches any single character.
* `[<chars>]` matches one character in the bracket.
* `[<char>-<char>]` matches one character in the bracket range.
* `[^<chars>]` or `[!<chars>]` matches one character not in the bracket.
* `{<glob>,...}` matches one of the globs in the list.
* `\` escapes the next character so it is treated as a literal.

=== Symbol Filters

Symbols can also be filtered based on their qualified names. You can use glob patterns to specify which symbols to include or exclude.

[,yaml]
----
include-symbols:
  - 'my_library::public_namespace::*'
----

By default, all symbols are included by `include-symbols`. The syntax for symbol glob patterns is the same as for file patterns, with the exception that the delimiter `::` is used instead of `/`. So you can match all symbols in a namespace and its subnamespaces with `my_library::public_namespace::**`.

The option `exclude-symbols` can be used to exclude symbols from the extraction process.

[,yaml]
----
include-symbols:
  - 'my_library::**'
exclude-symbols:
  - 'my_library::private_namespace::**'
----

[,cpp]
----
// excluded by `include-symbols`
void f0();

// included because it matches the prefix of 'my_library::**' in `include-symbols`
namespace my_library
{
    // included because it matches the pattern 'my_library::**' in `include-symbols`
    void f1();

    namespace private_namespace
    {
        // excluded by the pattern 'my_library::private_namespace::**' in `exclude-symbols`
        void f2();
    }
}
----

=== Private Symbols

The `implementation-defined` and `see-below` options can be used to designate symbols as implementation details or "see below" in the documentation.

[,yaml]
----
include-symbols:
  - 'my_library::**'
implementation-defined:
  - 'my_library::detail::**'
see-below:
  - 'my_library::see_below::**'
----

[,cpp]
----
namespace my_library
{
    namespace detail
    {
        // There's no documentation page for A
        // Any reference to `A` is rendered as `/* implementation detail */`
        class A {};
    }

    namespace see_below
    {
        // The documentation page for B is marked as "see below" and its members are not extracted.
        class B {
            // There's no documentation page for iterator
            class iterator;
        };
    }

    // This function is documented, but the return type is rendered as `/* implementation detail */`
    detail::A
    foo();
}
----

=== Whitelisting Rules

The rules for whitelisting symbols (`include-symbols`, `implementation-defined`, and `see-below`) are less strict than the rules for blacklisting symbols (`exclude-symbols`). A symbol is considered whitelisted if it matches any of the following conditions:

1. The symbol strictly matches one of the patterns.
** For instance, the patterns `std::vector` and `std::*` both match `std::vector` strictly.
2. The symbol is a parent namespace of an included symbol.
** For instance, the pattern `std::filesystem::*` also includes `std` and `std::filesystem`.
3. The parent symbol is also included.
** For instance, the pattern `std::*` also matches `std::vector::iterator` because `std::vector::iterator` is a member of  `std::vector`, which is matches the pattern.
4. The symbol is a child of a literal pattern representing a namespace.
** For instance, the literal pattern `std` matches `std::filesystem::path::iterator` because `std` is a literal pattern matching a namespace. In other words, these literal patterns represent the namespace and its subnamespaces as if the pattern were `std::**`.

For exclusion rules, the symbol must strictly match the pattern to be excluded.

[#config-options-reference]
== Reference

The following options can be defined both in the configuration file and on the command line, where the command line options always take precedence.

[config-options-reference,level=3]
====
include::partial$ConfigOptions.json[]
====
