= The Configuration File

MrDocs uses a configuration file to control how the documentation is generated.
The file is used to specify options such as the generator to use, additional compilation options, and filters.

Here's an example of a configuration file:

[source,yaml]
--------
include::partial$mrdocs-example.yml[]
--------

The xref:usage.adoc[Usage] page provides a detailed explanation of what to combine options from the configuration file and the command line.
The <<config-options-reference>> section provides a detailed explanation of the options available.

== YAML Schema

To get linting and autocompletion in the config file, a schema for the config can be specified.
In JetBrains IDEs, `# $schema: <url>` can be used to bind a schema to a file.
In editors with plugins based on the https://github.com/redhat-developer/yaml-language-server[YAML language server], `# yaml-language-server: $schema=<url>` can be used.
The schema for `mrdocs.yml` is provided xref:attachment$mrdocs.schema.json[here].
The following shows an example of a file specifying an inline-schema that's compatible with JetBrains IDEs and editors using the YAML language server.

[source,yaml]
--------
include::partial$mrdocs-schema-example.yml[]
--------

== Build Options

A number of options can be used to specify with which compile options MrDocs should be run.

[source,yaml]
----
source-root: ..
compilation-database: ../CMakeLists.txt
cmake: '-D MRDOCS_BUILD=ON'
defines: 'MRDOCS_BUILD'
----

The compile options primarily come from the `compilation-database` file.
When this file is generated from a `CMakeLists.txt` script, the `cmake` option can be used to specify additional options to pass to CMake.

Additionally, the `defines` option can be used to specify preprocessor definitions that should be used when generating the documentation.
These definitions are included in all targets of the compilation database.

== Generators

MrDocs supports multiple output formats that can be specified via the `generate` option:

|===
|Format |Description

|`adoc`
|AsciiDoc format.

|`html`
|HTML format.

|`xml`
|XML format.
|===

* Asciidoc is a text-based format that is easy to read and write.
It can also be converted to other formats such as HTML and Markdown.

* HTML can be generated directly with the `html` format.

* XML is a structured format that can be used in tests or as an intermediary format for other tools.

The `generate` option can be used to specify the output format:

[source,yaml]
----
# ...
generate: adoc
# ...
----

=== Generator Templates

MrDocs attempts to support various alternatives for customizing the output format and style without complex workflows to post-process XML output.
For the Asciidoc and HTML generators, the desired customization can usually be achieved by modifying the templates used to generate the output.

In the root of the installation directory, you will find the `share/mrdocs/addons/generator` directory.
This directory contains the templates used to generate the documentation with the markup formats.
Users can create a copy of these files and provide their own `addons` directory via the `addons` option.
This allows users to customize the output format to their needs.

[source,yaml]
----
addons: /path/to/custom/addons
----

One advantage of custom templates over post-processing XML files is the ability to access symbols as a graph.
If symbol `A` refers to symbol `B`, some properties of symbol `B` are likely to be required in the documentation of `A`.
All templates and generators can access a reference to `B` by searching the symbol tree or simply by accessing the elements `A` refers to.

// === Generator Plugins

== Filters

=== Symbol Filters

Not all symbols in a project may be relevant to the documentation.
MrDocs provides a way to filter out symbols based on their names.

[,yaml]
----
filters:
  symbols: # <.>
    exclude: # <.>
    include: # <.>
----

<.> Optional `symbols` key
<.> Optional `exclude` key
<.> Optional `include` key

Symbol filter patterns are specified using (optionally) qualified names, and may contain wildcards:

[,yaml]
----
filters:
  symbols:
    exclude:
      - 'A::B'
      - 'A::f*'
----

If a symbol matches a pattern in the exclude list, that symbol and its members will not be extracted:

[,yaml]
----
filters:
  symbols:
    exclude:
      - 'A'
----

[,cpp]
----
// ok, does not match any excluded pattern
void f0();

namespace A // matches the pattern 'A', will not be extracted
{
    // enclosing namespace matches an excluded pattern:
    // the symbol will not be extracted
    void f1();
}
----

The `filters.symbols.include` key can be used to override the exclude list for specific symbols.
A symbol which matches an included pattern and an excluded pattern will be extracted.

This permits fine-grained control of extraction for individual members of a class or namespace:

[,yaml]
----
filters:
  symbols:
    exclude:
      - 'A'
    include:
      - 'A::g*'
----

[,cpp]
----
namespace A
{
    // enclosing namespace matches an excluded pattern, will not be extracted
    void f0();

    // ok, matches the pattern 'A::g*' which overrides the exclude list
    void g0();
}
----

In order for a filter pattern to match a symbol, it must consist of simple identifiers that match the name as written in its declaration: namespace aliases, typedef-names, and `decltype` specifiers naming the symbol cannot be used.

NOTE: Specifying include patterns is only useful when the pattern would match a subset of symbols matched by an exclude pattern.
An include pattern without a subsuming exclude pattern will be ignored.

=== File Filters

Symbols can also be filtered based on the files they are declared in.
This can be useful for excluding files that exclusively contain implementation details or test code.

[,yaml]
----
input:
  include:
      - ../include  # <.>
  file-patterns:
      - *.hpp       # <.>
----

<.> A list of directories to include.
Only symbols defined in these files will be extracted.
<.> A list of file patterns to include.
Only symbols defined in files matching these patterns will be extracted.

=== Private Symbols

The `implementation-detail` and `see-below` options can be used to designate namespaces as implementation detail namespaces.

[,yaml]
----
implementation-detail: 'impl'
see-below: 'see_below'
----

If a namespace is designated as an implementation detail namespace, all symbols within that namespace will be marked as implementation details in the documentation.

[,cpp]
----
namespace impl
{
    class A {};
}

/// @brief A foo function
A foo();
----

The `impl` namespace is designated as an implementation detail namespace, so all symbols within it will be marked as implementation details in the documentation.
This means the symbol `A` would not be documented and the function `foo` could be documented as follows:

[,cpp]
----
/* implementation detail */ foo();
----

On the other hand, if a namespace is designated as a `see_below` namespace, all symbols within that namespace will be marked as "see below" in the documentation.

[,cpp]
----
namespace see_below
{
    class B {};
}
----

In the documentation, the symbol `B` would be marked as "see-below" and could be documented as:

[,cpp]
----
class B { /* see below */ };
----

[#config-options-reference]
== Reference

The following options can be defined both in the configuration file and on the command line, where the command line options always take precedence.

[config-options-reference,level=3]
====
include::partial$ConfigOptions.json[]
====
