= Specifying Filters

[,yaml]
----
filters:
  symbols: # <.>
    exclude: # <.>
    include: # <.>
----
<.> Optional `symbols` key
<.> Optional `exclude` key
<.> Optional `include` key

== Filtering Symbols

Symbol filter patterns specified using (optionally) qualified names, and may contain wildcards:

[,yaml]
----
filters:
  symbols:
    exclude:
      - 'A::B'
      - 'A::f*'
----

If a symbol matches a pattern in the exclude list, that symbol and its members will not be extracted:

[,yaml]
----
filters:
  symbols:
    exclude:
      - 'A'
----

[,cpp]
----
void f0(); // ok, does not match any excluded pattern

namespace A // matches the pattern 'A', will not be extracted
{
    void f1(); // enclosing namespace matches an excluded pattern, will not be extracted
}
----

In all contexts, a symbol which matches an included pattern and an excluded pattern will be extracted.
NOTE: Included patterns which do not match a subset of an excluded pattern

NOTE: Specifying include patterns is only useful when the pattern would match a subset of symbols matched by an exclude pattern. An include pattern without a subsuming exclude pattern is meaningless and will be ignored.

This permits fine-grained control of extraction for individual members of a class or namespace:

[,yaml]
----
filters:
  symbols:
    exclude:
      - 'A'
    include:
      - 'A::g*'
----

[,cpp]
----
namespace A
{
    void f0(); // enclosing namespace matches an excluded pattern, will not be extracted
    void g0(); // ok, matches the pattern 'A::g*' which overrides the exclude list
}
----

In order for a filter pattern to match a symbol, it must consist of simple identifiers
which matches the name as written in its declaration; namespace aliases, typedef-names,
and `decltype` specifiers naming the symbol cannot be used.
