= Install

== Binaries

Binaries are available from our https://github.com/cppalliance/mrdox/releases[Release Page,window="_blank"]

== Source

=== Requirements

==== LLVM

MrDox depends on a recent version of LLVM.

Here are the instructions to clone LLVM version required by this project.

[source,bash]
----
git clone https://github.com/llvm/llvm-project.git
cd llvm-project
git checkout 731264b0c2af7aa46bd39625202a99e06cfccff9
----

Here are the instructions to build and install LLVM with the settings required by this project.

Windows:

[source,bash]
----
# From Administrator CMD.EXE, after running vcvars64.bat
cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -D LLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -D CMAKE_CONFIGURATION_TYPES="Debug;RelWithDebInfo" -D LLVM_ENABLE_RTTI=ON -D CMAKE_INSTALL_PREFIX=/path/to/llvm+clang -D LLVM_ENABLE_IDE=OFF -D LLVM_ENABLE_DIA_SDK=OFF
cd build
cmake --build . --config RelWithDebInfo -j <threads>
cmake --build . --config Debug -j <threads>
cmake --install . --prefix "/path/to/llvm+clang/Debug" --config Debug
cmake --install . --prefix "/path/to/llvm+clang/RelWithDebInfo" --config RelWithDebInfo
----

Unix variants:

[source,bash]
----
cmake -S llvm -B build -D LLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -D CMAKE_BUILD_TYPE=RelWithDebInfo -D LLVM_ENABLE_RTTI=ON -D CMAKE_INSTALL_PREFIX=/path/to/llvm+clang/RelWithDebInfo
cd build
cmake --build . -j <threads>
cmake --install .
----

==== fmt

MrDox uses the `fmt` library to format its messages. The library can be downloaded from https://vcpkg.io/en/getting-started.html[vcpkg] or installed from https://github.com/fmtlib/fmt[their official repository].

When using vcpkg, its toolchain should be provided to the mrdox cmake configure command:

[source,bash]
----
cmake -B [build directory] -S [path to mrdox] -D CMAKE_TOOLCHAIN_FILE=[path to vcpkg]/scripts/buildsystems/vcpkg.cmake
----

When the `fmt` library has been installed from their official release, the library path should be provided to the mrdox cmake configure command:

[source,bash]
----
cmake -B [build directory] -S [path to mrdox] -D FMT_ROOT=[path to installed fmt]
----

Alternatively, when neither option is available, the mrdox configure script will attempt to automatically download the `fmt` library during configuration.

==== duktape

The MrDox templating system uses the duktape JS interpreter for its handlebars templating system. The library can be downloaded from https://vcpkg.io/en/getting-started.html[vcpkg] or installed from https://duktape.org/[their official repository].

When using vcpkg, its toolchain should be provided to the mrdox cmake configure command:

[source,bash]
----
cmake -B [build directory] -S [path to mrdox] -D CMAKE_TOOLCHAIN_FILE=[path to vcpkg]/scripts/buildsystems/vcpkg.cmake
----

When duktape has been installed from their https://github.com/svaarala/duktape/releases/tag/v2.7.0[official release], the duktape source path should be provided to the mrdox cmake configure command:

[source,bash]
----
cmake -B [build directory] -S [path to mrdox] -D DUKTAPE_SOURCE_ROOT=[path to duktape source]
----

Alternatively, when neither option is available, the mrdox configure script will attempt to automatically download duktape during configuration.

=== MrDox

Once the LLVM variants and dependencies are available in `/path/to/llvm+clang`, you can download MrDox:

[source,bash]
----
git clone https://github.com/cppalliance/mrdox
cd mrdox
----

Configure it with:

Windows:

[source,bash]
----
git clone https://github.com/cppalliance/mrdox
cd mrdox
cmake -G "Visual Studio 17 2022" -A x64 -B bin64 -D CMAKE_PREFIX_PATH="/path/to/llvm+clang/RelWithDebInfo"
----

Unix variants:

[source,bash]
----
git clone https://github.com/cppalliance/mrdox
cd mrdox
cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D LLVM_ROOT=/path/to/llvm+clang/RelWithDebInfo -D Clang_ROOT=/path/to/llvm+clang/RelWithDebInfo
----

Then build and install it with:

[source,bash]
----
cd build
cmake --build . -j <threads>
cmake --install .
----

