= Install

== Binaries

Binary packages are available from our https://github.com/cppalliance/mrdox/releases[Release Page,window="_blank"]

== Source

For consistency, these instructions assume you are using the `SRC_DIR` variable to refer to the directory where you are going to clone MrDox and any other requirements.
Please create an environment variable with that directory and adjust it accordingly.
For instance:

Windows (Command Prompt):

[source,commandline]
----
set SRC_DIR=C:\Users\%USERNAME%\src
echo %SRC_DIR%
----

Windows (PowerShell):

[source,bash]
----
$env:SRC_DIR = "C:\Users\$env:USERNAME\src"
echo $env:SRC_DIR
----

Unix-variants (Linux, macOS, etc.):

[source,bash]
----
export SRC_DIR="$HOME/src"
echo $SRC_DIR
----

=== Requirements

==== LLVM

MrDox depends on a recent version of LLVM.

Here are the instructions to clone LLVM version required by this project.

[source,bash]
----
git clone https://github.com/llvm/llvm-project.git
cd llvm-project
git checkout 731264b0c2af7aa46bd39625202a99e06cfccff9
----

Here are the instructions to build and install LLVM with the settings required by this project.

Windows:

[source,commandline]
----
# From Administrator CMD.EXE, after running vcvars64.bat
cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -D LLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -D CMAKE_CONFIGURATION_TYPES="Debug;RelWithDebInfo" -D LLVM_ENABLE_RTTI=ON -D CMAKE_INSTALL_PREFIX=%SRC_DIR%/llvm+clang -D LLVM_ENABLE_IDE=OFF -D LLVM_ENABLE_DIA_SDK=OFF
cd build
cmake --build . --config RelWithDebInfo -j %NUMBER_OF_PROCESSORS%
cmake --build . --config Debug -j %NUMBER_OF_PROCESSORS%
cmake --install . --prefix "%SRC_DIR%/llvm+clang/Debug" --config Debug
cmake --install . --prefix "%SRC_DIR%/llvm+clang/RelWithDebInfo" --config RelWithDebInfo
----

Unix variants:

[source,bash]
----
cmake -S llvm -B build -D LLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -D CMAKE_BUILD_TYPE=RelWithDebInfo -D LLVM_ENABLE_RTTI=ON -D CMAKE_INSTALL_PREFIX=$SRC_DIR/llvm+clang/RelWithDebInfo
cd build
cmake --build . -j "$(nproc)"
cmake --install .
----

==== Duktape

Duktape is a JavaScript engine that is used by MrDox to parse and evaluate JavaScript code.
It provides no CMake integration scripts.
The MrDox configuration script needs direct access to the installed source files for Duktape.

The release files can be obtained from the Duktape repository:

Windows:

[source,commandline]
----
curl -L -o "duktape-2.7.0.tar.xz" "https://github.com/svaarala/duktape/releases/download/v2.7.0/duktape-2.7.0.tar.xz"
duktape_dir="%SRC_DIR%\duktape"
mkdir "%duktape_dir%"
tar -xvf "duktape-2.7.0.tar.xz" -C "%duktape_dir%"
----

Unix variants:

[source,bash]
----
curl -L -o "duktape-2.7.0.tar.xz" "https://github.com/svaarala/duktape/releases/download/v2.7.0/duktape-2.7.0.tar.xz"
duktape_dir="$SRC_DIR/duktape"
mkdir -p "$duktape_dir"
tar -xvf "duktape-2.7.0.tar.xz" -C "$duktape_dir"
----

==== Other dependencies

These other dependencies provide CMake integration scripts.
They can be obtained from https://www.vcpkg.io/[vcpkg] or installed manually.

* fmt >= 10
* zlib
* libtinfo

=== MrDox

Once the dependencies are available in `SRC_DIR`, you can download MrDox:

[source,bash]
----
git clone https://github.com/cppalliance/mrdox
cd mrdox
----

Configure it with:

Windows:

[source,bash]
----
git clone https://github.com/cppalliance/mrdox
cd mrdox
cmake -G "Visual Studio 17 2022" -A x64 -B bin64 -D CMAKE_PREFIX_PATH="%SRC_DIR%/llvm+clang/RelWithDebInfo" -D DUKTAPE_SOURCE_ROOT="%SRC_DIR%\duktape\duktape-2.7.0"
----

Unix variants:

[source,bash]
----
git clone https://github.com/cppalliance/mrdox
cd mrdox
cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D LLVM_ROOT=/path/to/llvm+clang/RelWithDebInfo -D Clang_ROOT=/path/to/llvm+clang/RelWithDebInfo -D DUKTAPE_SOURCE_ROOT="$SRC_DIR/duktape/duktape-2.7.0"
----

Then build and install it with:

[source,bash]
----
cd build
cmake --build . -j <threads>
cmake --install .
----

== Package layout

The MrDox installation directory follows the "Filesystem Hierarchy Standard" (FHS) layout:

* `bin`: the MrDox executable intended to be used by users or invoked from the command line.
* `share`: resource files installed by MrDox
* `doc`: the MrDox documentation
* `include`: the MrDox headers
* `lib`: the MrDox library

The FHS layout provides a directory structure that also serves as a widely accepted convention for organizing files and directories in Unix-like systems, but that can be used in any operating system.
