= Install
:tabs-sync-option:

[#mrdocs-binaries]
== Binary Packages

Binary packages are available from our https://github.com/cppalliance/mrdocs/releases[Release Page,window="_blank"].
Most users should use these packages.

mrdocs-releases::[]

[#mrdocs-bootstrap-script]
== Bootstrap Script

The bootstrap script available in the repository provides an alternative way to install MrDocs and its
dependencies from source. Just run the script from the root of the MrDocs repository:

[source,bash]
----
git clone https://www.github.com/cppalliance/mrdocs.git
cd mrdocs
python bootstrap.py
----

Or if you just want to install MrDocs without cloning the repository, you can run the script directly from the web:

[tabs]
====
Windows PowerShell::
+
--
[source,powershell]
----
python -c "$(Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/cppalliance/mrdocs/refs/heads/develop/bootstrap.py' -UseBasicParsing | Select-Object -ExpandProperty Content)"
----
--

Unix Variants::
+
--
[source,bash]
----
python -c "$(curl -fsSL https://raw.githubusercontent.com/cppalliance/mrdocs/refs/heads/develop/bootstrap.py)"
----
--
====

This method automates the download, configuration, and build steps for MrDocs and all required third-party libraries.
It is especially useful for developers and for users who prefer a streamlined, interactive setup or need to install
MrDocs in custom environments.

The script will prompt you for the installation directory and all other options.
Every option can be defined in the command line directly instead of being prompted.
All options can be listed with the `--help` option.

The `--non-interactive` option allows you to run the script without any prompts, using
values specified in the command line and default values for other options. This allows you
to only customize the most common options and leave the others to their defaults. This
is handy for developers to refresh dependencies:

[source,bash]
----
python bootstrap.py --non-interactive --mrdocs-build-type=Release --third-party-src-dir=/path/to/dependencies
----

In the default case, the script will download the source code to the current directory
and install MrDocs system-wide.

[tabs]
====
Windows PowerShell::
+
--
[source,powershell]
----
python -c "$(Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/cppalliance/mrdocs/refs/heads/develop/bootstrap.py' -UseBasicParsing)" --non-interactive
----
--

Unix Variants::
+
--
[source,bash]
----
python -c "$(curl -fsSL https://raw.githubusercontent.com/cppalliance/mrdocs/refs/heads/develop/bootstrap.py)" --non-interactive
----
--
====

The script handles tool checks, repository cloning, patching, and CMake configuration, reducing
manual intervention and potential errors.
This approach is recommended for developers, advanced users, or those integrating MrDocs
into larger projects.

[#mrdocs-source]
== Manually Install from Source

The following instructions assume we are at a parent directory that's going to contain both the MrDocs and the third-party dependencies directories.

[source]
----
+ <parent-directory>
  + mrdocs
  + third-party
----

Clone the MrDocs repository with:

[source,bash]
----
git clone https://github.com/cppalliance/mrdocs
----

Also create and go to the `third-party` directory, where we are going to download and install our dependencies:

[source,bash]
----
mkdir third-party
cd third-party
----

[NOTE]
====
These instructions assume all dependencies are installed in the `third-party` directory for simplicity.
Feel free to install them anywhere you want and adjust the main MrDocs configuration command later.
====

[#install-fmt]
=== Fmt

MrDocs uses the `fmt` library for formatting strings.
From the `third-party` directory, you can clone the `fmt` repository and install it with the following commands:

[source,bash]
----
git clone https://github.com/fmtlib/fmt --branch 10.2.1 --depth 1 <.>
cd fmt
cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release -D FMT_DOC=OFF -D FMT_TEST=OFF <.>
cmake --build ./build --config Release <.>
cmake --install ./build --prefix ./install <.>
cd ..
----

<.> Shallow clones the fmt repository.
<.> Configure the fmt library with CMake, excluding the documentation and tests.
<.> Builds the fmt library in the `build` directory.
<.> Installs the fmt library in the `install` directory.

[IMPORTANT]
====
All instructions in this document assume you are using a CMake version above 3.26.
Binaries are available at https://cmake.org/download/[CMake's official website,window="_blank"].
====

=== Duktape

MrDocs uses the `duktape` library for JavaScript parsing.
From the `third-party` directory, you can download the `duktape` source code from the official release:

[tabs]
====
Windows PowerShell::
+
--
[source,bash]
----
Invoke-WebRequest -Uri "https://github.com/svaarala/duktape/releases/download/v2.7.0/duktape-2.7.0.tar.xz" -OutFile "duktape-2.7.0.tar.xz" <.>
----

<.> Downloads the `duktape` source code.
--

Unix Variants::
+
--
[source,bash]
----
curl -LJO https://github.com/svaarala/duktape/releases/download/v2.7.0/duktape-2.7.0.tar.xz <.>
----

<.> Downloads the `duktape` source code.
--
====

Then patch the Duktape source code to provide CMake support.

[source,bash]
----
tar -xf duktape-2.7.0.tar.xz <.>
cp ../mrdocs/third-party/duktape/CMakeLists.txt ./duktape-2.7.0/CMakeLists.txt <.>
cp ../mrdocs/third-party/duktape/duktapeConfig.cmake.in ./duktape-2.7.0/duktapeConfig.cmake.in <.>
cd duktape-2.7.0
----

<.> Extracts the `duktape` source code.
<.> Patches the source code with a `CMakeLists.txt` file to the `duktape-2.7.0` directory so that we can build it with CMake.
<.> Copies the `duktapeConfig.cmake.in` file to the `duktape-2.7.0` directory so that we can install it with CMake and find it later from other CMake projects.

Now adjust the `duk_config.h` file to indicate we are statically building Duktape.

[tabs]
====
Windows PowerShell::
+
--
[source,bash]
----
$content = Get-Content -Path "src\duk_config.h" <.>
$content = $content -replace '#define DUK_F_DLL_BUILD', '#undef DUK_F_DLL_BUILD' <.>
$content | Set-Content -Path "src\duk_config.h" <.>
----

<.> Read the content of `duk_config.h`
<.> Replace the `DUK_F_DLL_BUILD` macro with `#undef DUK_F_DLL_BUILD`
<.> Write the content back to the file
--

Unix Variants::
+
--
[source,bash]
----
sed -i 's/#define DUK_F_DLL_BUILD/#undef DUK_F_DLL_BUILD/g' "src/duk_config.h" <.>
----

<.> Disables the `DUK_F_DLL_BUILD` macro in the `duk_config.h` file to indicate we are statically building duktape.
--

MacOS::
+
--
[source,bash]
----
sed -i '' 's/#define DUK_F_DLL_BUILD/#undef DUK_F_DLL_BUILD/g' src/duk_config.h
----

<.> Disables the `DUK_F_DLL_BUILD` macro in the `duk_config.h` file to indicate we are statically building duktape.
--
====

And finally install the library with CMake:

[source,bash]
----
cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release <.>
cmake --build ./build --config Release <.>
cmake --install ./build --prefix ./install <.>
----

<.> Configures the `duktape` library with CMake.
<.> Builds the `duktape` library in the `build` directory.
<.> Installs the `duktape` library with CMake support in the `install` directory.

The scripts above download the `duktape` source code, extract it, and configure it with CMake.
The CMake scripts provided by MrDocs are copied to the `duktape-2.7.0` directory to facilitate the build process with CMake and provide CMake installation scripts for other projects.

=== Libxml2

MrDocs uses `libxml2` tools for tests.
Only developers need to install this dependency.
Users can skip this step.

From the `third-party` directory, you can clone the `libxml2` repository and install it with the following commands:

[source,bash]
----
git clone https://github.com/GNOME/libxml2 --branch v2.12.6 --depth 1 <.>
cd libxml2
cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release -DLIBXML2_WITH_PROGRAMS=ON -DLIBXML2_WITH_FTP=OFF -DLIBXML2_WITH_HTTP=OFF -DLIBXML2_WITH_ICONV=OFF -DLIBXML2_WITH_LEGACY=OFF -DLIBXML2_WITH_LZMA=OFF -DLIBXML2_WITH_ZLIB=OFF -DLIBXML2_WITH_ICU=OFF -DLIBXML2_WITH_TESTS=OFF -DLIBXML2_WITH_HTML=ON -DLIBXML2_WITH_C14N=ON -DLIBXML2_WITH_CATALOG=ON -DLIBXML2_WITH_DEBUG=ON -DLIBXML2_WITH_ISO8859X=ON -DLIBXML2_WITH_MEM_DEBUG=OFF -DLIBXML2_WITH_MODULES=ON -DLIBXML2_WITH_OUTPUT=ON -DLIBXML2_WITH_PATTERN=ON -DLIBXML2_WITH_PUSH=ON -DLIBXML2_WITH_PYTHON=OFF -DLIBXML2_WITH_READER=ON -DLIBXML2_WITH_REGEXPS=ON -DLIBXML2_WITH_SAX1=ON -DLIBXML2_WITH_SCHEMAS=ON -DLIBXML2_WITH_SCHEMATRON=ON -DLIBXML2_WITH_THREADS=ON -DLIBXML2_WITH_THREAD_ALLOC=OFF -DLIBXML2_WITH_TREE=ON -DLIBXML2_WITH_VALID=ON -DLIBXML2_WITH_WRITER=ON -DLIBXML2_WITH_XINCLUDE=ON -DLIBXML2_WITH_XPATH=ON -DLIBXML2_WITH_XPTR=ON <.>
cmake --build ./build --config Release <.>
cmake --install ./build --prefix ./install <.>
cd ..
----

<.> Shallow clones the libxml2 repository.
<.> Configure the libxml2 with CMake, excluding the documentation, tests, and unwanted dependencies.
<.> Builds libxml2 in the `build` directory.
<.> Installs libxml2 in the `install` directory.

=== LLVM

MrDocs uses LLVM to parse C++ code and extract documentation from it.
It depends on a recent version of LLVM: https://github.com/llvm/llvm-project/tree/dd7a3d4d798e30dfe53b5bbbbcd9a23c24ea1af9[dd7a3d4]

**Download**:

You can shallow-clone the project from the official repository.
From the `third-party` directory, run the following commands:

[source,bash]
----
mkdir -p llvm-project <.>
cd llvm-project
git init <.>
git remote add origin https://github.com/llvm/llvm-project.git <.>
git fetch --depth 1 origin dd7a3d4d798e30dfe53b5bbbbcd9a23c24ea1af9 <.>
git checkout FETCH_HEAD <.>
----

<.> Create a directory for the llvm-project instead of cloning it
<.> Initialize a git repository
<.> Add the official LLVM repository as a remote
<.> Fetch the commit we want to use: this allows us to shallow-clone the repository at this commit
<.> Checkout the commit we want to use

**Configure**:

The `mrdocs/third-party/llvm` directory provides https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html[CMake presets,window=_blank] to build LLVM.
We recommend using preset files as they contain a replicable set of CMake configuration values that can be used for a project.
From `third-party/llvm-project`, you can copy the `CMakePresets.json` and `CMakeUserPresets.json` files to the `llvm-project/llvm` directory.

[source,bash]
----
cp ../../mrdocs/third-party/llvm/CMakePresets.json ./llvm
cp ../../mrdocs/third-party/llvm/CMakeUserPresets.json ./llvm/CMakeUserPresets.json
----

Run a command such as the following to configure LLVM:

[tabs]
====
Windows PowerShell::
+
--
[source,bash]
----
cd llvm
cmake -S . -B ./build --preset=release-win -DLLVM_ENABLE_RUNTIMES=libcxx
----
--

Unix Variants::
+
--
[source,bash]
----
cd llvm
cmake -S . -B ./build --preset=release-unix -DLLVM_ENABLE_RUNTIMES=libcxx;libcxxabi;libunwind
----
--
====

In the example above, we configure a `Release` version of LLVM for MrDocs.
Choose one of the presets from `CMakePresets.json` or edit the variants in `CMakeUserPresets.json` to customize the configurations.

[NOTE]
====
Developers might also want to build a custom `Debug` LLVM configuration including optimizations, which allows for faster execution of tests.
The `relwithdebinfo` and `debwithopt` presets are provided for this purpose.
Or if you prefer using the command line, set `CMAKE_CONFIGURATION_TYPES` or `CMAKE_BUILD_TYPE` to `Debug` and manually include the optimization flags to `-D CMAKE_CXX_FLAGS="/O2 /Zi"` (MSVC) or `-D CMAKE_CXX_FLAGS="-Og -g"`.

This should give you an optimized build with all debug features and flags, such as an appropriate https://learn.microsoft.com/en-us/cpp/standard-library/iterator-debug-level[`_ITERATOR_DEBUG_LEVEL`] and the `/MDd` flag in MSVC.
In other platforms, this should give you a release somewhat equivalent to `RelWithDebInfo` optimized for debugging experience. `-Og` offers a reasonable level of optimization while maintaining fast compilation and a good debugging experience.
====

**Build**:

Build and install the configured version of LLVM with:

[source,bash]
----
cmake --build ./build --config Release --parallel 4
cmake --install ./build --prefix ../install
----

Replace 4 with the number of cores you want to use for building LLVM.

Return from `./third-party/llvm-project/llvm` to the LLVM project directory:

[source,bash]
----
cd ../..
----

=== MrDocs

Return to the parent directory of `third-party` (the one containing the `mrdocs` directory) to build and install MrDocs:

[source,bash]
----
cd ../..
----

**Configure**:

The MrDocs repository also includes a `CMakePresets.json` file that contains the parameters to configure MrDocs with CMake.

To specify the installation directories, you can use the `LLVM_ROOT`, `DUKTAPE_ROOT`, `FMT_ROOT`, and `LIBXML2_ROOT` environment variables.
To specify a generator (`-G`) and platform name (`-A`), you can use the `CMAKE_GENERATOR` and `CMAKE_GENERATOR_PLATFORM` environment variables.

You can also customize the presets by duplicating and editing the `CMakeUserPresets.json.example` file in the `mrdocs` directory.
This is typically more convenient than using environment variables.

For instance, to build MrDocs with the default `Release` preset, you can run the following command:

[tabs]
====
Windows PowerShell::
+
--
[source,bash]
----
cd mrdocs
cmake -S . --preset=release-win
----
--

Unix Variants::
+
--
[source,bash]
----
cd mrdocs
cmake -S . --preset=release-unix
----
--
====

To list the available presets, you can run:

[source,bash]
----
cmake --list-presets
----

**Build**:

Then build and install MrDocs with:

[source,bash]
----
cd build
cmake --build .
cmake --install .
----

To customize the installation directory, use the `CMAKE_INSTALL_PREFIX` option or use the `--prefix` option for the `cmake --install .` command.
To customize the C and C++ compilers, use the `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` options.

[NOTE]
====
Developers should also enable `-D BUILD_TESTING=ON`.
====

== Package layout

The MrDocs installation directory follows the "Filesystem Hierarchy Standard" (FHS) layout:

* `bin`: the MrDocs executable intended to be used by users or invoked from the command line.
* `share`: resource files installed by MrDocs
* `doc`: the MrDocs documentation
* `include`: the MrDocs headers
* `lib`: the MrDocs library

The FHS layout provides a directory structure that also serves as a widely accepted convention for organizing files and directories in Unix-like systems, but that can be used in any operating system.
