= Install

[#mrdocs-binaries]
== Binary Packages

Binary packages are available from our https://github.com/cppalliance/mrdocs/releases[Release Page,window="_blank"].
Most users should use these packages.

mrdocs-releases::[]

[#mrdocs-source]
== Install from Source

The following instructions assume we are at a parent directory that's going to contain both the MrDocs and the third-party dependencies directories.

[source]
----
+ <parent-directory>
  + mrdocs
  + third-party
----

Clone the MrDocs repository with:

[source,bash]
----
git clone https://github.com/cppalliance/mrdocs
----

Also create and go to the `third-party` directory, where we are going to download and install our dependencies:

[source,bash]
----
mkdir third-party
cd third-party
----

[NOTE]
====
These instructions assume all dependencies are installed in the `third-party` directory for simplicity.
Fell free to install them anywhere you want and adjust the main MrDocs configuration command later.
====

[#install-fmt]
=== Fmt

MrDocs uses the `fmt` library for formatting strings.
From the `third-party` directory, you can clone the `fmt` repository and install it with the following commands:

[source,bash]
----
git clone https://github.com/fmtlib/fmt --branch 10.2.1 --depth 1 <.>
cd fmt
cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release -D FMT_DOC=OFF -D FMT_TEST=OFF <.>
cmake --build ./build --config Release <.>
cmake --install ./build --prefix ./install <.>
cd ..
----

<.> Shallow clones the fmt repository.
<.> Configure the fmt library with CMake, excluding the documentation and tests.
<.> Builds the fmt library in the `build` directory.
<.> Installs the fmt library in the `install` directory.

[IMPORTANT]
====
All instructions in this document assume you are using a CMake version above 3.26.
Binaries are available at https://cmake.org/download/[CMake's official website,window="_blank"].
====

If you prefer using Vcpkg to install dependencies, you can install VcPkg and `fmt` with the following commands from the `third-party` directory:

:tabs-sync-option:

[tabs]
====
Windows PowerShell::
+
--
[source,bash]
----
git clone https://github.com/microsoft/vcpkg.git -b master <.>
cd vcpkg
bootstrap-vcpkg.bat <.>
vcpkg.exe install fmt --triplet x64-windows <.>
----

<.> Clones the Vcpkg repository.
<.> Bootstraps Vcpkg.
<.> Installs the `fmt` library.
--

Unix Variants::
+
--
[source,bash]
----
git clone https://github.com/microsoft/vcpkg.git -b master <.>
cd vcpkg
./bootstrap-vcpkg.sh <.>
./vcpkg install fmt <.>
----

<.> Clones the Vcpkg repository.
<.> Bootstraps Vcpkg.
<.> Installs the `fmt` library.
--
====

[NOTE]
====
You can also install `fmt` with Vcpkg in _Manifest mode_.
In https://learn.microsoft.com/en-us/vcpkg/users/manifests[manifest mode,windows=blank_], you declare your project's direct dependencies in a manifest file named `vcpkg.json`.
MrDocs includes a `vcpkg.json.example` file you can duplicate or create a symlink as `vcpkg.json` to use this mode.
This file includes all the dependencies MrDocs needs, except for LLVM.

In this mode, VcPkg will create separate installed trees for each project and configuration.
This is the recommended vcpkg mode for most users, according to the https://learn.microsoft.com/en-us/vcpkg/users/manifests[vcpkg documentation,window=blank_].
====

=== Duktape

MrDocs uses the `duktape` library for JavaScript parsing.
From the `third-party` directory, you can download the `duktape` source code from the official release:

[tabs]
====
Windows PowerShell::
+
--
[source,bash]
----
Invoke-WebRequest -Uri "https://github.com/svaarala/duktape/releases/download/v2.7.0/duktape-2.7.0.tar.xz" -OutFile "duktape-2.7.0.tar.xz" <.>
----

<.> Downloads the `duktape` source code.
--

Unix Variants::
+
--
[source,bash]
----
curl -LJO https://github.com/svaarala/duktape/releases/download/v2.7.0/duktape-2.7.0.tar.xz <.>
----

<.> Downloads the `duktape` source code.
--
====

Then patch the Duktape source code to provide CMake support.

[source,bash]
----
tar -xf duktape-2.7.0.tar.xz <.>
cp ../mrdocs/third-party/duktape/CMakeLists.txt ./duktape-2.7.0/CMakeLists.txt <.>
cp ../mrdocs/third-party/duktape/duktapeConfig.cmake.in ./duktape-2.7.0/duktapeConfig.cmake.in <.>
cd duktape-2.7.0
----

<.> Extracts the `duktape` source code.
<.> Patches the source code with a `CMakeLists.txt` file to the `duktape-2.7.0` directory so that we can build it with CMake.
<.> Copies the `duktapeConfig.cmake.in` file to the `duktape-2.7.0` directory so that we can install it with CMake and find it later from other CMake projects.

Now adjust the `duk_config.h` file to indicate we are statically building Duktape.

[tabs]
====
Windows PowerShell::
+
--
[source,bash]
----
$content = Get-Content -Path "src\duk_config.h" <.>
$content = $content -replace '#define DUK_F_DLL_BUILD', '#undef DUK_F_DLL_BUILD' <.>
$content | Set-Content -Path "src\duk_config.h" <.>
----

<.> Read the content of `duk_config.h`
<.> Replace the `DUK_F_DLL_BUILD` macro with `#undef DUK_F_DLL_BUILD`
<.> Write the content back to the file
--

Unix Variants::
+
--
[source,bash]
----
sed -i 's/#define DUK_F_DLL_BUILD/#undef DUK_F_DLL_BUILD/g' "src/duk_config.h" <.>
----

<.> Disables the `DUK_F_DLL_BUILD` macro in the `duk_config.h` file to indicate we are statically building duktape.
--
====

And finally install the library with CMake:

[source,bash]
----
cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release <.>
cmake --build ./build --config Release <.>
cmake --install ./build --prefix ./install <.>
----

<.> Configures the `duktape` library with CMake.
<.> Builds the `duktape` library in the `build` directory.
<.> Installs the `duktape` library with CMake support in the `install` directory.

The scripts above downloads the `duktape` source code, extracts it, and configures it with CMake.
The CMake scripts provided by MrDocs are copied to the `duktape-2.7.0` directory to facilitate the build process with CMake and provide CMake installation scripts for other projects.

If you prefer using Vcpkg to install dependencies, you can install `duktape` with the following commands from the `third-party` directory:

[tabs]
====
Windows PowerShell::
+
--
[source,bash]
----
cd vcpkg
vcpkg.exe install duktape --triplet x64-windows <.>
----

<.> Installs the `duktape` library.
--

Unix Variants::
+
--
[source,bash]
----
cd vcpkg
./vcpkg install duktape <.>
----

<.> Installs the `duktape` library.
--
====

NOTE: These examples assume VcPkg is already installed in the `third-party/vcpkg` directory (see the <<install-fmt>> section).

=== Libxml2

MrDocs uses `libxml2` tools for tests.
Only developers need to install this dependency.
Users can skip this step.

From the `third-party` directory, you can clone the `libxml2` repository and install it with the following commands:

[source,bash]
----
git clone https://github.com/GNOME/libxml2 --branch v2.12.6 --depth 1 <.>
cd libxml2
cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release -DLIBXML2_WITH_PROGRAMS=ON -DLIBXML2_WITH_FTP=OFF -DLIBXML2_WITH_HTTP=OFF -DLIBXML2_WITH_ICONV=OFF -DLIBXML2_WITH_LEGACY=OFF -DLIBXML2_WITH_LZMA=OFF -DLIBXML2_WITH_ZLIB=OFF -DLIBXML2_WITH_ICU=OFF -DLIBXML2_WITH_TESTS=OFF -DLIBXML2_WITH_HTML=ON -DLIBXML2_WITH_C14N=ON -DLIBXML2_WITH_CATALOG=ON -DLIBXML2_WITH_DEBUG=ON -DLIBXML2_WITH_ISO8859X=ON -DLIBXML2_WITH_MEM_DEBUG=OFF -DLIBXML2_WITH_MODULES=ON -DLIBXML2_WITH_OUTPUT=ON -DLIBXML2_WITH_PATTERN=ON -DLIBXML2_WITH_PUSH=ON -DLIBXML2_WITH_PYTHON=OFF -DLIBXML2_WITH_READER=ON -DLIBXML2_WITH_REGEXPS=ON -DLIBXML2_WITH_SAX1=ON -DLIBXML2_WITH_SCHEMAS=ON -DLIBXML2_WITH_SCHEMATRON=ON -DLIBXML2_WITH_THREADS=ON -DLIBXML2_WITH_THREAD_ALLOC=OFF -DLIBXML2_WITH_TREE=ON -DLIBXML2_WITH_VALID=ON -DLIBXML2_WITH_WRITER=ON -DLIBXML2_WITH_XINCLUDE=ON -DLIBXML2_WITH_XPATH=ON -DLIBXML2_WITH_XPTR=ON <.>
cmake --build ./build --config Release <.>
cmake --install ./build --prefix ./install <.>
cd ..
----

<.> Shallow clones the libxml2 repository.
<.> Configure the libxml2 with CMake, excluding the documentation, tests, and unwanted dependencies.
<.> Builds libxml2 in the `build` directory.
<.> Installs libxml2 in the `install` directory.

If you prefer using Vcpkg to install dependencies, you can install `libxml2` with the following commands from the `third-party` directory:

[tabs]
====
Windows PowerShell::
+
--
[source,bash]
----
cd vcpkg
vcpkg.exe install libxml2[tools] --triplet x64-windows <.>
----

<.> Installs `libxml2`.
--

Unix Variants::
+
--
[source,bash]
----
cd vcpkg
./vcpkg install libxml2[tools] <.>
----

<.> Installs `libxml2`.
--
====

NOTE: These examples assume VcPkg is already installed in the `third-party/vcpkg` directory (see the <<install-fmt>> section).

=== LLVM

MrDocs uses LLVM to parse C++ code and extract documentation from it.
It depends on a recent version of LLVM: https://github.com/llvm/llvm-project/tree/e1065370aaacb1b1cb48e77d37d376bf024f4a39[e1065370]

**Download**:

You can shallow-clone the project from the official repository.
From the `third-party` directory, run the following commands:

[source,bash]
----
mkdir -p llvm-project <.>
cd llvm-project
git init <.>
git remote add origin https://github.com/llvm/llvm-project.git <.>
git fetch --depth 1 origin e1065370aaacb1b1cb48e77d37d376bf024f4a39 <.>
git checkout FETCH_HEAD <.>
----

<.> Create a directory for the llvm-project instead of cloning it
<.> Initialize a git repository
<.> Add the official LLVM repository as a remote
<.> Fetch the commit we want to use: this allows us to shallow-clone the repository at this commit
<.> Checkout the commit we want to use

**Configure**:

The `mrdocs/third-party/llvm` directory provides https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html[CMake presets,window=_blank] to build LLVM.
We recommend using preset files as they contain a replicable set of CMake configuration values that can be used for a project.
From `third-party/llvm-project`, you can copy the `CMakePresets.json` and `CMakeUserPresets.json` files to the `llvm-project/llvm` directory.

[source,bash]
----
cp ../../mrdocs/third-party/llvm/CMakePresets.json ./llvm
cp ../../mrdocs/third-party/llvm/CMakeUserPresets.json ./llvm/CMakeUserPresets.json
----

Run a command such as the following to configure LLVM:

[tabs]
====
Windows PowerShell::
+
--
[source,bash]
----
cd llvm
cmake -S . -B ./build --preset=release-win
----
--

Unix Variants::
+
--
[source,bash]
----
cd llvm
cmake -S . -B ./build --preset=release-unix
----
--
====

In the example above, we configure a `Release` version of LLVM for MrDocs.
Choose one of the presets from `CMakePresets.json` or edit the variants in `CMakeUserPresets.json` to customize the configurations.

[NOTE]
====
Developers might also want to build a custom `Debug` LLVM configuration including optimizations, which allows for faster execution of tests.
The `relwithdebinfo` and `debwithopt` presets are provided for this purpose.
Or if you prefer using the command line, set `CMAKE_CONFIGURATION_TYPES` or `CMAKE_BUILD_TYPE` to `Debug` and manually include the optimization flags to `-D CMAKE_CXX_FLAGS="/O2 /Zi"` (MSVC) or `-D CMAKE_CXX_FLAGS="-Og -g"`.

This should give you an optimized build with all debug features and flags, such as an appropriate https://learn.microsoft.com/en-us/cpp/standard-library/iterator-debug-level[`_ITERATOR_DEBUG_LEVEL`] and the `/MDd` flag in MSVC.
In other platforms, this should give you a release somewhat equivalent to `RelWithDebInfo` optimized for debugging experience. `-Og` offers a reasonable level of optimization while maintaining fast compilation and a good debugging experience.
====

**Build**:

Build and install the configured version of LLVM with:

[source,bash]
----
cmake --build ./build --config Release --parallel 4
cmake --install ./build --prefix ../install
----

Replace 4 with the number of cores you want to use for building LLVM.

Return from `./third-party/llvm-project/llvm` to the LLVM project directory:

[source,bash]
----
cd ../..
----

=== LibC++

In addition to LLVM, MrDocs requires a deterministic version of the C++ standard library (LibC++) to ensure consistent behavior across various environments. This step is crucial for replicating specific compiler and library configurations.

**Download**:

Continue using the same LLVM project directory.

**Configure**:

Configure and build LibC++ using the existing structure:

[source,bash]
----
export CXX="./install/bin/clang++"
export CC="./install/bin/clang"
----

Run a command such as the following to configure LLVM:

[tabs]
====
Windows PowerShell::
+
--
[source,bash]
----
cmake -G Ninja \
  -S runtimes \
  -B build-libcxx \
  -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" \
  -DCMAKE_INSTALL_PREFIX="$(pwd)/install" \
  -DLIBCXXABI_USE_LLVM_UNWINDER=OFF \
  -DLIBCXXABI_ENABLE_SHARED=OFF \
  -DLIBCXXABI_ENABLE_STATIC=ON \
  -DLIBCXX_ENABLE_SHARED=OFF \
  -DLIBCXX_NO_VCRUNTIME=ON \
  -DCMAKE_CXX_FLAGS="-D__ORDER_LITTLE_ENDIAN__=1234 -D__ORDER_BIG_ENDIAN__=4321 -D__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__"
----
--

Unix Variants::
+
--
[source,bash]
----
cmake -G Ninja  \
  -S runtimes  \
  -B build-libcxx  \
  -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind"  \
  -DCMAKE_INSTALL_PREFIX="$(pwd)/install"
----
--
====

**Build**:

Build and install the configured version of LibC++ with:

[tabs]
====
Windows PowerShell::
+
--
[source,bash]
----
ninja -C build-libcxx cxx
ninja -C build-libcxx install-cxx
----
--

Unix Variants::
+
--
[source,bash]
----
ninja -C build-libcxx cxx cxxabi unwind
ninja -C build-libcxx install-cxx install-cxxabi install-unwind  
----
--
====

Return from `./third-party/llvm-project` to the parent directory to build and install MrDocs:

[source,bash]
----
cd ../..
----


=== MrDocs

Return from `./third-party/vcpkg` to the parent directory of `third-party` (the one containing the `mrdocs` directory) to build and install MrDocs:

[source,bash]
----
cd ../..
----

**Configure**:

You can also configure MrDocs with <<mrdocs-configure-cmd-line, command line arguments>> or <<mrdocs-configure-presets, CMake presets>>.

[#mrdocs-configure-cmd-line]
_Configure with Command Line Arguments_:

With the dependencies are available in `third-party`, you can configure MrDocs with:

[tabs]
====
Windows PowerShell::
+
--
[source,commandline]
----
cmake -S mrdocs -B build -G "Visual Studio 17 2022" -A x64 -D CMAKE_CONFIGURATION_TYPES="RelWithDebInfo" -D CMAKE_EXPORT_COMPILE_COMMANDS=ON -D LLVM_ROOT="%cd%/third-party/llvm+clang/RelWithDebInfo" -D DUKTAPE_SOURCE_ROOT="%cd%/third-party/duktape-2.7.0" -D CMAKE_TOOLCHAIN_FILE="%cd%/third-party/vcpkg/scripts/buildsystems/vcpkg.cmake"
----
--

Unix Variants::
+
--
[source,bash]
----
cmake -S mrdocs -B build -D CMAKE_BUILD_TYPE=RelWithDebInfo -D CMAKE_EXPORT_COMPILE_COMMANDS=ON -D LLVM_ROOT="$(pwd)/third-party/llvm+clang/RelWithDebInfo" -D DUKTAPE_SOURCE_ROOT="$(pwd)/third-party/duktape-2.7.0" -D CMAKE_TOOLCHAIN_FILE="$(pwd)/third-party/vcpkg/scripts/buildsystems/vcpkg.cmake"
----
--
====

[#mrdocs-configure-presets]
_Configure with CMake Presets_:

The MrDocs repository also includes a `CMakePresets.json` file that contains the parameters to configure MrDocs with CMake.

To specify the installation directories, you can use the `LLVM_ROOT`, `DUKTAPE_SOURCE_ROOT`, `CMAKE_TOOLCHAIN_FILE` environment variables.
To specify a generator (`-G`) and platform name (`-A`), you can use the `CMAKE_GENERATOR` and `CMAKE_GENERATOR_PLATFORM` environment variables.

You can also customize the presets by duplicating and editing the `CMakeUserPresets.json.example` file in the `mrdocs` directory.
This is typically more convenient than using environment variables.

**Build**:

Then build and install MrDocs with:

[source,bash]
----
cd build
cmake --build .
cmake --install .
----

To customize the installation directory, use the `CMAKE_INSTALL_PREFIX` option or use the `--prefix` option for the `cmake --install .` command.
To customize the C and C++ compilers, use the `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` options.

[NOTE]
====
Developers should also enable `-D BUILD_TESTING=ON`.
If any custom build of LLVM other than `RelWithDebInfo` is being used, the `LLVM_ROOT` variable should be set to the installation directory of that build.
====

== Package layout

The MrDocs installation directory follows the "Filesystem Hierarchy Standard" (FHS) layout:

* `bin`: the MrDocs executable intended to be used by users or invoked from the command line.
* `share`: resource files installed by MrDocs
* `doc`: the MrDocs documentation
* `include`: the MrDocs headers
* `lib`: the MrDocs library

The FHS layout provides a directory structure that also serves as a widely accepted convention for organizing files and directories in Unix-like systems, but that can be used in any operating system.
