= Reference
:mrdocs:

[#index]
== Global namespace


=== Namespaces

[cols=1]
|===
| Name 

| <<A,`A`>> 
|===
=== Types

[cols=1]
|===
| Name 

| <<F,`F`>> 
|===
=== Functions

[cols=2]
|===
| Name | Description 

| <<f0,`f0`>> 
| 

| <<f5,`f5`>> 
| See xref:#A-f1[A&colon;&colon;f1]



| <<f6,`f6`>> 
| See xref:#F-operator_bitnot[F&colon;&colon;operator&#126;]



|===

[#A]
== A


=== Types

[cols=2]
|===
| Name | Description 

| <<A-B,`B`>> 
| See xref:#A-f1[f1]



| <<A-C,`C`>> 
| 

| <<A-D,`D`>> 
| 

|===
=== Functions

[cols=2]
|===
| Name | Description 

| <<A-f1,`f1`>> 
| See xref:#f0[f0]



|===

[#A-B]
== <<A,A>>::B


See xref:#A-f1[f1]



=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename&gt;
struct B;
----

=== Member Functions

[cols=1]
|===
| Name 

| <<A-B-f2,`f2`>> 
|===



=== Description


See xref:#A-f1[A&colon;&colon;f1]

See xref:#A-f1[&colon;&colon;A&colon;&colon;f1] 



[#A-B-f2]
== <<A,A>>::<<A-B,B>>::f2


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f2();
----

[#A-C]
== <<A,A>>::C


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct C;
----

=== Member Functions

[cols=1]
|===
| Name 

| <<A-C-f3,`f3`>> 
| <<A-C-f4,`f4`>> 
|===



[#A-C-f3]
== <<A,A>>::<<A-C,C>>::f3


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f3();
----

[#A-C-f4]
== <<A,A>>::<<A-C,C>>::f4


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f4();
----

[#A-D]
== <<A,A>>::D


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct D
    : <<A-C,C>>;
----

=== Types

[cols=2]
|===
| Name | Description 

| <<A-D-E,`E`>> 
| See xref:#A-C-f3[f3]



|===
=== Member Functions

[cols=1]
|===
| Name 

| <<A-C-f3,`f3`>> 
| <<A-C-f4,`f4`>> 
|===



[#A-D-E]
== <<A,A>>::<<A-D,D>>::E


See xref:#A-C-f3[f3]



=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct E;
----




=== Description


See xref:#A-D-f4[f4]

See xref:#A-C-f4[C&colon;&colon;f4] 



[#A-D-f4]
== <<A,A>>::<<A-D,D>>::f4


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f4();
----

[#A-f1]
== <<A,A>>::f1


See xref:#f0[f0]



=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f1();
----

=== Description


See xref:#f0[&colon;&colon;f0] 



[#F]
== F


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct F;
----

=== Member Functions

[cols=1]
|===
| Name 

| <<F-operator_not,`operator!`>> 
| <<F-operator_not_eq,`operator!&equals;`>> 
| <<F-operator_mod,`operator%`>> 
| <<F-operator_mod_eq,`operator%&equals;`>> 
| <<F-operator_bitand,`operator&amp;`>> 
| <<F-operator_and,`operator&amp;&amp;`>> 
| <<F-operator_and_eq,`operator&amp;&equals;`>> 
| <<F-operator_call,`operator()`>> 
| <<F-operator_star,`operator&ast;`>> 
| <<F-operator_star_eq,`operator&ast;&equals;`>> 
| <<F-operator_plus,`operator&plus;`>> 
| <<F-operator_inc,`operator&plus;&plus;`>> 
| <<F-operator_plus_eq,`operator&plus;&equals;`>> 
| <<F-operator_comma,`operator,`>> 
| <<F-operator_minus,`operator&hyphen;`>> 
| <<F-operator_dec,`operator&hyphen;&hyphen;`>> 
| <<F-operator_minus_eq,`operator&hyphen;&equals;`>> 
| <<F-operator_ptr,`operator&hyphen;&gt;`>> 
| <<F-operator_ptrmem,`operator&hyphen;&gt;&ast;`>> 
| <<F-operator_slash,`operator&sol;`>> 
| <<F-operator_slash_eq,`operator&sol;&equals;`>> 
| <<F-operator_lt,`operator&lt;`>> 
| <<F-operator_lshift,`operator&lt;&lt;`>> 
| <<F-operator_lshift_eq,`operator&lt;&lt;&equals;`>> 
| <<F-operator_le,`operator&lt;&equals;`>> 
| <<F-operator_3way,`operator&lt;&equals;&gt;`>> 
| <<F-operator_assign,`operator&equals;`>> 
| <<F-operator_eq,`operator&equals;&equals;`>> 
| <<F-operator_gt,`operator&gt;`>> 
| <<F-operator_ge,`operator&gt;&equals;`>> 
| <<F-operator_rshift,`operator&gt;&gt;`>> 
| <<F-operator_rshift_eq,`operator&gt;&gt;&equals;`>> 
| <<F-operator_subs,`operator&lsqb;&rsqb;`>> 
| <<F-operator_xor,`operator&circ;`>> 
| <<F-operator_xor_eq,`operator&circ;&equals;`>> 
| <<F-operator_bitor,`operator&verbar;`>> 
| <<F-operator_or_eq,`operator&verbar;&equals;`>> 
| <<F-operator_or,`operator&verbar;&verbar;`>> 
| <<F-operator_bitnot,`operator&#126;`>> 
|===



[#F-operator_not]
== <<F,F>>::operator!


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator!();
----

[#F-operator_not_eq]
== <<F,F>>::operator!&equals;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator!&equals;(<<F,F>>&);
----

[#F-operator_mod]
== <<F,F>>::operator%


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator%(<<F,F>>&);
----

[#F-operator_mod_eq]
== <<F,F>>::operator%&equals;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator%&equals;(<<F,F>>&);
----

[#F-operator_bitand]
== <<F,F>>::operator&amp;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&amp;(<<F,F>>&);
----

[#F-operator_and]
== <<F,F>>::operator&amp;&amp;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&amp;&amp;(<<F,F>>&);
----

[#F-operator_and_eq]
== <<F,F>>::operator&amp;&equals;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&amp;&equals;(<<F,F>>&);
----

[#F-operator_call]
== <<F,F>>::operator()


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator()(<<F,F>>&);
----

[#F-operator_star]
== <<F,F>>::operator&ast;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&ast;(<<F,F>>&);
----

[#F-operator_star_eq]
== <<F,F>>::operator&ast;&equals;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&ast;&equals;(<<F,F>>&);
----

[#F-operator_plus]
== <<F,F>>::operator&plus;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&plus;(<<F,F>>&);
----

[#F-operator_inc]
== <<F,F>>::operator&plus;&plus;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&plus;&plus;();
----

[#F-operator_plus_eq]
== <<F,F>>::operator&plus;&equals;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&plus;&equals;(<<F,F>>&);
----

[#F-operator_comma]
== <<F,F>>::operator,


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator,(<<F,F>>&);
----

[#F-operator_minus]
== <<F,F>>::operator&hyphen;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&hyphen;(<<F,F>>&);
----

[#F-operator_dec]
== <<F,F>>::operator&hyphen;&hyphen;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&hyphen;&hyphen;();
----

[#F-operator_minus_eq]
== <<F,F>>::operator&hyphen;&equals;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&hyphen;&equals;(<<F,F>>&);
----

[#F-operator_ptr]
== <<F,F>>::operator&hyphen;&gt;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&hyphen;&gt;();
----

[#F-operator_ptrmem]
== <<F,F>>::operator&hyphen;&gt;&ast;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&hyphen;&gt;&ast;(<<F,F>>&);
----

[#F-operator_slash]
== <<F,F>>::operator&sol;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&sol;(<<F,F>>&);
----

[#F-operator_slash_eq]
== <<F,F>>::operator&sol;&equals;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&sol;&equals;(<<F,F>>&);
----

[#F-operator_lt]
== <<F,F>>::operator&lt;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&lt;(<<F,F>>&);
----

[#F-operator_lshift]
== <<F,F>>::operator&lt;&lt;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&lt;&lt;(<<F,F>>&);
----

[#F-operator_lshift_eq]
== <<F,F>>::operator&lt;&lt;&equals;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&lt;&lt;&equals;(<<F,F>>&);
----

[#F-operator_le]
== <<F,F>>::operator&lt;&equals;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&lt;&equals;(<<F,F>>&);
----

[#F-operator_3way]
== <<F,F>>::operator&lt;&equals;&gt;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&lt;&equals;&gt;(<<F,F>>&);
----

[#F-operator_assign]
== <<F,F>>::operator&equals;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&equals;(<<F,F>>&);
----

[#F-operator_eq]
== <<F,F>>::operator&equals;&equals;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&equals;&equals;(<<F,F>>&);
----

[#F-operator_gt]
== <<F,F>>::operator&gt;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&gt;(<<F,F>>&);
----

[#F-operator_ge]
== <<F,F>>::operator&gt;&equals;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&gt;&equals;(<<F,F>>&);
----

[#F-operator_rshift]
== <<F,F>>::operator&gt;&gt;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&gt;&gt;(<<F,F>>&);
----

[#F-operator_rshift_eq]
== <<F,F>>::operator&gt;&gt;&equals;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&gt;&gt;&equals;(<<F,F>>&);
----

[#F-operator_subs]
== <<F,F>>::operator&lsqb;&rsqb;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&lsqb;&rsqb;(<<F,F>>&);
----

[#F-operator_xor]
== <<F,F>>::operator&circ;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&circ;(<<F,F>>&);
----

[#F-operator_xor_eq]
== <<F,F>>::operator&circ;&equals;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&circ;&equals;(<<F,F>>&);
----

[#F-operator_bitor]
== <<F,F>>::operator&verbar;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&verbar;(<<F,F>>&);
----

[#F-operator_or_eq]
== <<F,F>>::operator&verbar;&equals;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&verbar;&equals;(<<F,F>>&);
----

[#F-operator_or]
== <<F,F>>::operator&verbar;&verbar;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&verbar;&verbar;(<<F,F>>&);
----

[#F-operator_bitnot]
== <<F,F>>::operator&#126;


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
operator&#126;();
----

[#f0]
== f0


=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f0();
----

[#f5]
== f5


See xref:#A-f1[A&colon;&colon;f1]



=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f5();
----

=== Description


See xref:#A-f1[&colon;&colon;A&colon;&colon;f1]



[#f6]
== f6


See xref:#F-operator_bitnot[F&colon;&colon;operator&#126;]



=== Synopsis


Declared in `&lt;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f6();
----

=== Description


See xref:#F-operator_comma[F&colon;&colon;operator,]

See xref:#F-operator_call[F&colon;&colon;operator()]

See xref:#F-operator_subs[F&colon;&colon;operator&lsqb;&rsqb;]

See xref:#F-operator_plus[F&colon;&colon;operator&plus;]

See xref:#F-operator_inc[F&colon;&colon;operator&plus;&plus;]

See xref:#F-operator_plus_eq[F&colon;&colon;operator&plus;&equals;]

See xref:#F-operator_bitand[F&colon;&colon;operator&amp;]

See xref:#F-operator_and[F&colon;&colon;operator&amp;&amp;]

See xref:#F-operator_and_eq[F&colon;&colon;operator&amp;&equals;]

See xref:#F-operator_bitor[F&colon;&colon;operator&verbar;]

See xref:#F-operator_or[F&colon;&colon;operator&verbar;&verbar;]

See xref:#F-operator_or_eq[F&colon;&colon;operator&verbar;&equals;]

See xref:#F-operator_minus[F&colon;&colon;operator&hyphen;]

See xref:#F-operator_dec[F&colon;&colon;operator&hyphen;&hyphen;]

See xref:#F-operator_minus_eq[F&colon;&colon;operator&hyphen;&equals;]

See xref:#F-operator_ptr[F&colon;&colon;operator&hyphen;&gt;]

See xref:#F-operator_ptrmem[F&colon;&colon;operator&hyphen;&gt;&ast;]

See xref:#F-operator_lt[F&colon;&colon;operator&lt;]

See xref:#F-operator_lshift[F&colon;&colon;operator&lt;&lt;]

See xref:#F-operator_lshift_eq[F&colon;&colon;operator&lt;&lt;&equals;]

See xref:#F-operator_le[F&colon;&colon;operator&lt;&equals;]

See xref:#F-operator_3way[F&colon;&colon;operator&lt;&equals;&gt;]

See xref:#F-operator_gt[F&colon;&colon;operator&gt;]

See xref:#F-operator_rshift[F&colon;&colon;operator&gt;&gt;]

See xref:#F-operator_rshift_eq[F&colon;&colon;operator&gt;&gt;&equals;]

See xref:#F-operator_ge[F&colon;&colon;operator&gt;&equals;]

See xref:#F-operator_star[F&colon;&colon;operator&ast;]

See xref:#F-operator_star_eq[F&colon;&colon;operator&ast;&equals;]

See xref:#F-operator_mod[F&colon;&colon;operator%]

See xref:#F-operator_mod_eq[F&colon;&colon;operator%&equals;]

See xref:#F-operator_slash[F&colon;&colon;operator&sol;]

See xref:#F-operator_slash_eq[F&colon;&colon;operator&sol;&equals;]

See xref:#F-operator_xor[F&colon;&colon;operator&circ;]

See xref:#F-operator_xor_eq[F&colon;&colon;operator&circ;&equals;]

See xref:#F-operator_assign[F&colon;&colon;operator&equals;]

See xref:#F-operator_eq[F&colon;&colon;operator&equals;&equals;]

See xref:#F-operator_not[F&colon;&colon;operator!]

See xref:#F-operator_not_eq[F&colon;&colon;operator!&equals;]





[.small]#Created with https://www.mrdocs.com[MrDocs]#
