#!/usr/bin/env python3
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# Copyright (c) 2026 Gennaro Prota (gennaro.prota@gmail.com)
#
# Official repository: https://github.com/cppalliance/mrdocs
#
"""Generate the `mrdocs.set` allowlist artifacts from JSON.

Reads `src/lib/Extensions/AllowedFields.json` and writes two outputs
from the single source of truth:

  - A C++ include (`AllowedFields.gen.hpp`) with a constexpr
    `kSettableFields[]` array, consumed by `SetMember.cpp` to gate
    `mrdocs.set` calls at runtime.

  - An AsciiDoc partial (`extensions-allowed-fields.adoc`) included
    by `extensions.adoc` to render the reference table for users.

The same JSON drives both, so the runtime allowlist and the rendered
docs cannot drift. Adding a new entry is one edit to the JSON.

Run automatically by CMake whenever the JSON or this script changes.
"""

import json
import sys
from pathlib import Path


def emit_cpp_include(fields: list[dict], output_path: Path) -> None:
    lines: list[str] = [
        "//",
        "// Licensed under the Apache License v2.0 with LLVM Exceptions.",
        "// See https://llvm.org/LICENSE.txt for license information.",
        "// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception",
        "//",
        "// Generated by util/generate_extension_allowed_fields.py from",
        "// src/lib/Extensions/AllowedFields.json. DO NOT EDIT - edit",
        "// the JSON and rebuild.",
        "//",
        "",
        "#ifndef MRDOCS_API_EXTENSIONS_ALLOWEDFIELDS_GEN_HPP",
        "#define MRDOCS_API_EXTENSIONS_ALLOWEDFIELDS_GEN_HPP",
        "",
        "#include <string_view>",
        "",
        "namespace mrdocs {",
        "",
        "/** Names of fields scripts may set through `mrdocs.set`.",
        "",
        "    Matched against the normalized member name (camelCase",
        "    first letter lowered). See",
        "    `src/lib/Extensions/AllowedFields.json` for the type",
        "    and human-facing description of each entry.",
        "*/",
        "inline constexpr std::string_view kSettableFields[] = {",
    ]
    for f in fields:
        lines.append(f'    "{f["name"]}",')
    lines.append("};")
    lines.append("")
    lines.append("} // mrdocs")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


def emit_adoc_table(fields: list[dict], output_path: Path) -> None:
    lines: list[str] = [
        "// Generated by util/generate_extension_allowed_fields.py from",
        "// src/lib/Extensions/AllowedFields.json. DO NOT EDIT - edit",
        "// the JSON and rebuild.",
        "",
        "|===",
        "|Field |Type |Description",
        "",
    ]
    for f in fields:
        lines.append(f"|`{f['name']}`")
        lines.append(f"|{f['type']}")
        lines.append(f"|{f['description']}")
        lines.append("")
    lines.append("|===")
    lines.append("")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    if len(sys.argv) != 4:
        print(
            "usage: generate_extension_allowed_fields.py "
            "<json-input> <cpp-output> <adoc-output>",
            file=sys.stderr,
        )
        return 2

    json_path = Path(sys.argv[1])
    cpp_path = Path(sys.argv[2])
    adoc_path = Path(sys.argv[3])

    data = json.loads(json_path.read_text(encoding="utf-8"))
    fields = data["fields"]
    if not fields:
        print(
            "generate_extension_allowed_fields.py: at least one field required",
            file=sys.stderr,
        )
        return 1

    emit_cpp_include(fields, cpp_path)
    emit_adoc_table(fields, adoc_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
