#!/usr/bin/env python3
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# Copyright (c) 2025 Alan de Freitas (alandefreitas@gmail.com)
#
# Official repository: https://github.com/cppalliance/mrdocs
#

"""
Debugger pretty printer configuration generation.

Generates .lldbinit and .gdbinit files pointing to the project's
pretty printer scripts.
"""

import os
from pathlib import Path
from typing import Optional

from ..core.filesystem import write_text
from ..core.ui import TextUI, get_default_ui

# Pretty printer scripts relative to the source directory
_GDB_SCRIPTS = [
    "data/gdb/mrdocs_printers.py",
]

_LLDB_SCRIPTS = [
    "data/gdb/mrdocs_printers.py",
]


def generate_pretty_printer_configs(
    source_dir: str,
    dry_run: bool = False,
    ui: Optional[TextUI] = None,
):
    """
    Generate debugger pretty printer configuration files.

    Creates .lldbinit and .gdbinit files that load MrDocs pretty
    printer scripts for GDB and LLDB.

    Args:
        source_dir: MrDocs source directory.
        dry_run: If True, only print what would be done.
        ui: TextUI instance for output.
    """
    if ui is None:
        ui = get_default_ui()

    def _resolve(rel_path: str) -> str:
        return os.path.abspath(os.path.join(source_dir, rel_path))

    # Generate .gdbinit
    gdb_scripts = [_resolve(s) for s in _GDB_SCRIPTS if os.path.exists(_resolve(s))]
    gdbinit_path = os.path.join(source_dir, ".gdbinit")
    if gdb_scripts:
        if not dry_run and os.path.exists(gdbinit_path):
            ui.info(f"GDB configuration already exists at '{gdbinit_path}', skipping.")
        else:
            gdb_lines = [
                "# GDB pretty printers for MrDocs",
                "# Generated by bootstrap.py",
                "python",
                "import sys",
            ]
            for script in gdb_scripts:
                script_dir = os.path.dirname(script)
                gdb_lines.append(f"sys.path.insert(0, '{script_dir.replace(os.sep, '/')}')")
                gdb_lines.extend([
                    "try:",
                    f"    import {Path(script).stem} as _bootstrap_pretty",
                    "    _bootstrap_pretty.register_pretty_printers(gdb)",
                    "except Exception as exc:",
                    "    print('warning: failed to register pretty printers:', exc)",
                ])
            gdb_lines.append("end")
            write_text(gdbinit_path, "\n".join(gdb_lines) + "\n", dry_run=dry_run, ui=ui)
            if not dry_run:
                ui.ok(f"Generated GDB configuration at '{gdbinit_path}'")

    # Generate .lldbinit
    lldb_scripts = [_resolve(s) for s in _LLDB_SCRIPTS if os.path.exists(_resolve(s))]
    lldbinit_path = os.path.join(source_dir, ".lldbinit")
    if lldb_scripts:
        if not dry_run and os.path.exists(lldbinit_path):
            ui.info(f"LLDB configuration already exists at '{lldbinit_path}', skipping.")
        else:
            lldb_lines = [
                "# LLDB pretty printers for MrDocs",
                "# Generated by bootstrap.py",
                "# Enable LLDB to load this file with: echo 'settings set target.load-cwd-lldbinit true' >> ~/.lldbinit",
            ]
            for script in lldb_scripts:
                lldb_lines.append(f"command script import {script.replace(os.sep, '/')}")
            write_text(lldbinit_path, "\n".join(lldb_lines) + "\n", dry_run=dry_run, ui=ui)
            if not dry_run:
                ui.ok(f"Generated LLDB configuration at '{lldbinit_path}'")
