#!/usr/bin/env python3
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# Copyright (c) 2025 Alan de Freitas (alandefreitas@gmail.com)
#
# Official repository: https://github.com/cppalliance/mrdocs
#

"""
Debugger pretty printer configuration generation.

Generates configuration files for debugger pretty printers (LLDB, GDB).
"""

import os
from pathlib import Path
from typing import Optional, List

from ..core.filesystem import write_text, load_json_file
from ..core.ui import TextUI, get_default_ui


def generate_pretty_printer_configs(
    source_dir: str,
    dry_run: bool = False,
    ui: Optional[TextUI] = None,
):
    """
    Generate debugger pretty printer configuration files.

    Loads configuration from share/pretty_printers.json and creates
    .lldbinit and/or .gdbinit files to load the specified pretty printers.

    Args:
        source_dir: MrDocs source directory.
        dry_run: If True, only print what would be done.
        ui: TextUI instance for output.
    """
    if ui is None:
        ui = get_default_ui()

    config_path = os.path.join(source_dir, "share", "pretty_printers.json")
    overrides = load_json_file(config_path) or {}

    if dry_run:
        if overrides:
            ui.info("dry-run: would generate debugger pretty printer configuration from share/pretty_printers.json")
        else:
            ui.info("dry-run: skipping debugger pretty printer generation (no config found)")
        return

    if not overrides:
        ui.info("No debugger pretty printer configuration found in share/pretty_printers.json; skipping generation.")
        return

    project_label = overrides.get("project", "MrDocs")

    def _resolve_paths(paths: List[str]) -> List[str]:
        resolved = []
        for p in paths:
            resolved.append(p if os.path.isabs(p) else os.path.abspath(os.path.join(source_dir, p)))
        return resolved

    lldb_scripts = _resolve_paths(overrides.get("lldb", []))
    gdb_scripts = _resolve_paths(overrides.get("gdb", []))

    if not lldb_scripts and not gdb_scripts:
        ui.info("No debugger pretty printer scripts listed in share/pretty_printers.json; skipping generation.")
        return

    # Generate .lldbinit
    lldbinit_path = os.path.join(source_dir, ".lldbinit")
    if lldb_scripts:
        if os.path.exists(lldbinit_path):
            ui.info(f"LLDB pretty printer configuration already exists at '{lldbinit_path}', skipping generation.")
        else:
            lldb_lines = [
                f"# LLDB pretty printers for {project_label}",
                "# Generated by bootstrap.py",
                "# Enable LLDB to load this file with: echo 'settings set target.load-cwd-lldbinit true' >> ~/.lldbinit",
            ]
            for script in lldb_scripts:
                lldb_lines.append(f"command script import {script.replace(os.sep, '/')}")
            write_text(lldbinit_path, "\n".join(lldb_lines) + "\n", dry_run=False, ui=ui)
            ui.ok(f"Generated LLDB pretty printer configuration at '{lldbinit_path}'")
    else:
        ui.info("No LLDB pretty printer scripts provided; skipping LLDB configuration.")

    # Generate .gdbinit
    gdbinit_path = os.path.join(source_dir, ".gdbinit")
    if gdb_scripts:
        if os.path.exists(gdbinit_path):
            ui.info(f"GDB pretty printer configuration already exists at '{gdbinit_path}', skipping generation.")
        else:
            gdb_lines = [
                f"# GDB pretty printers for {project_label}",
                "# Generated by bootstrap.py",
                "python",
                "import sys",
            ]
            for script in gdb_scripts:
                script_dir = os.path.dirname(script)
                gdb_lines.append(f"sys.path.insert(0, '{script_dir.replace(os.sep, '/')}')")
                gdb_lines.extend([
                    "try:",
                    f"    import {Path(script).stem} as _bootstrap_pretty",
                    "    _bootstrap_pretty.register_pretty_printers(gdb)",
                    "except Exception as exc:",
                    "    print('warning: failed to register pretty printers:', exc)",
                ])
            gdb_lines.append("end")
            write_text(gdbinit_path, "\n".join(gdb_lines) + "\n", dry_run=False, ui=ui)
            ui.ok(f"Generated GDB pretty printer configuration at '{gdbinit_path}'")
    else:
        ui.info("No GDB pretty printer scripts provided; skipping GDB configuration.")
