#ifndef STORAGE_GEN_MESSAGES_HPP
#define STORAGE_GEN_MESSAGES_HPP
// tag::body[]

// Generated by the build (protoc, gRPC, OpenAPI, …); do not edit by
// hand. Every component in this project keeps its generated headers
// next to the hand-written ones under a `_generated/` subdirectory,
// so `exclude-patterns: '**/_generated/**'` drops them all at once.

namespace storage::gen {
struct PutRequest {};
struct PutResponse {};
}
// end::body[]
#endif
