= cond

== Syntax
@cond [(section-label)]

== Description
Starts a conditional section that ends with a corresponding xref:commands/endcond.adoc[@endcond] command, which is typically found in another comment block. The main purpose of this pair of commands is to (conditionally) exclude part of a file from processing (in older version of MrDocs this could only be achieved using C preprocessor commands).

The section between `@cond` and xref:commands/endcond.adoc[@endcond] can be included by adding its section label to the ENABLED_SECTIONS configuration option. If the section label is omitted, the section will be excluded from processing unconditionally. The section label can be a logical expression build of section labels, round brackets, && (AND), || (OR) and ! (NOT). If you use an expression you need to wrap it in round brackets, i.e `@cond (!LABEL1 && LABEL2)`.

For conditional sections within a comment block one should use a xref:commands/if.adoc[@if] ... xref:commands/endif.adoc[@endif] block. When using `@cond` and the condition is not satisfied the current comment block is ended and everything until the matching xref:commands/endcond.adoc[@endcond] is removed and a new command block is started there.

Conditional sections can be nested. In this case a nested section will only be shown if it and its containing section are included.

Here is an example showing the commands in action:

```
/** An interface */
class Intf
{
  public:
    /** A method */
    virtual void func() = 0;

    /// @cond TEST

    /** A method used for testing */
    virtual void test() = 0;

    /// @endcond
};

/// @cond DEV
/*
 *  The implementation of the interface
 */
class Implementation : public Intf
{
  public:
    void func();

    /// @cond TEST
    void test();
    /// @endcond

    /// @cond
    /** This method is obsolete and does
     *  not show up in the documentation.
     */
    void obsolete();
    /// @endcond
};

/// @endcond

```
// [CODE_END]
The output will be different depending on whether or not ENABLED_SECTIONS contains `TEST`, or `DEV` 



*Note:* Due to the moment of parsing the `@cond` and xref:commands/endcond.adoc[@endcond] commands cannot be used in ALIASES.

== See Also
sections xref:commands/if.adoc[@if], xref:commands/ifnot.adoc[@ifnot], xref:commands/else.adoc[@else], xref:commands/elseif.adoc[@elseif], xref:commands/endif.adoc[@endif], xref:commands/endcond.adoc[@endcond], and ENABLED_SECTIONS.