= diafile

== Syntax
@diafile &lt;file&gt; ["caption"] [&lt;sizeindication&gt;=&lt;size&gt;]

== Description
Inserts an image made in dia from <file> into the documentation.

The first argument specifies the file name of the image. MrDocs will look for files in the paths (or files) that you specified after the DIAFILE_DIRS tag. If the dia file is found it will be used as an input file dia. The resulting image will be put into the correct output directory. If the dia file name contains spaces you'll have to put quotes ("...") around it.

The second argument is optional and can be used to specify the caption that is displayed below the image. This argument has to be specified between quotes even if it does not contain any spaces. The quotes are stripped before the caption is displayed.

The third argument is also optional and can be used to specify the width or height of the image. For a description of the possibilities see the paragraph Size indication with the xref:commands/image.adoc[@image] command.