= fn

== Syntax
@fn (function declaration)

== Description
Indicates that a comment block contains documentation for a function (either global or as a member of a class). This command is only needed if a comment block is not placed in front (or behind) the function declaration or definition.

If your comment block is in front of the function declaration or definition this command can (and to avoid redundancy should) be omitted.

A full function declaration including arguments should be specified after the `@fn` command on a single line, since the argument ends at the end of the line!

This command is equivalent to xref:commands/var.adoc[@var], xref:commands/typedef.adoc[@typedef], and xref:commands/property.adoc[@property].



*Warning:* Do not use this command if it is not absolutely needed, since it will lead to duplication of information and thus to errors.

== Example
```
class Fn_Test
{
  public:
    const char *member(char,int) throw(std::out_of_range);
};
 
const char *Fn_Test::member(char c,int n) throw(std::out_of_range) {}
 
/*! @class Fn_Test
 * @brief Fn_Test class.
 *
 * Details about Fn_Test.
 */
 
/*! @fn const char *Fn_Test::member(char c,int n) 
 *  @brief A member function.
 *  @param c a character.
 *  @param n an integer.
 *  @exception std::out_of_range parameter is out of range.
 *  @return a character pointer.
 */

```
// [CODE_END]


== See Also
sections xref:commands/var.adoc[@var], xref:commands/property.adoc[@property], and xref:commands/typedef.adoc[@typedef].