= snippet

== Syntax
@snippet['{'option'}'] &lt;file-name&gt; ( block_id )

== Description
Where the xref:commands/include.adoc[@include] command can be used to include a complete file as source code, this command can be used to quote only a fragment of a source file. In case `this` is used as <file-name> the current file is taken as file to take the snippet from.

For example, the putting the following command in the documentation, references a snippet in file `example.cpp` residing in a subdirectory which should be pointed to by EXAMPLE_PATH.

```
  @snippet snippets/example.cpp Adding a resource

```
// [CODE_END]
The text following the file name is the unique identifier for the snippet. This is used to delimit the quoted code in the relevant snippet file as shown in the following example that corresponds to the above `@snippet` command:

```
    QImage image(64, 64, QImage::Format_RGB32);
    image.fill(qRgb(255, 160, 128));
 
//! [Adding a resource]
    document->addResource(QTextDocument::ImageResource,
        QUrl("mydata://image.png"), QVariant(image));
//! [Adding a resource]
    ...

```
// [CODE_END]
Note that the lines containing the block markers will not be included, so the output will be:

```
document->addResource(QTextDocument::ImageResource,
    QUrl("mydata://image.png"), QVariant(image));

```
// [CODE_END]
Note also that the [block_id] markers should appear exactly twice in the source file.

The `option` can either be `lineno`, `trimleft` or `doc`, and additionally `local` can be specified.

The `option` `lineno` can be used to enable line numbers for the included code if desired.
The `option` `trimleft` can be used to remove the common spacing in front of all lines (also taking in account the setting of the TAB_SIZE tag).
The `option` `doc` can be used to treat the file as documentation rather than code.
The `option` `local` can be used make MrDocs interpret the code as if it was in the class or namespace in which the include command appears, rather than the global namespace.
The `option` `strip` can be used to always hide any special comments from the included code, overruling the STRIP_CODE_COMMENTS setting, and option `nostrip` can be used to always show the special comments. These options have no effect in combination with the `option` `doc`.

When using option `doc`, there is also the option `raise` that can be specified to raise all sections found in the referenced file by a certain amount. For example

```
 @snippet{doc,raise=1} file.dox XXX

```
// [CODE_END]
will treat any level 1 `@section` found the snippet as a level 2 `@subsection`, and any level 2 `@subsection` into a level 3 `@subsubsection`, etc.

Furthermore, there is the option `prefix` that can be used to add a prefix to each label of the included sections, so that they remain unique. For example:

```
 @include{doc,prefix=fn_} file.dox

```
// [CODE_END]
will treat e.g. `@section s1` found in `file.dox` as if it was specified as `@section fn_s1`.

see section xref:commands/dontinclude.adoc[@dontinclude] for an alternative way to include fragments of a source file that does not require markers.



*Note:* The included documentation should not have comment signs in it as they will appear in the documentation as well.