= subpage

== Syntax
@subpage &lt;name&gt; ["(text)"]

== Description
This command can be used to create a hierarchy of pages. The same structure can be made using the xref:commands/defgroup.adoc[@defgroup] and xref:commands/ingroup.adoc[@ingroup] commands, but for pages the `@subpage` command is often more convenient. The main page (see xref:commands/mainpage.adoc[@mainpage]) is typically the root of hierarchy.

This command behaves similar as xref:commands/ref.adoc[@ref] in the sense that it creates a reference to a page labeled <name> with the optional link text as specified in the second argument.

It differs from the xref:commands/ref.adoc[@ref] command in that it only works for pages, and creates a parent-child relation between pages, where the child page (or sub page) is identified by label <name>.

See the xref:commands/section.adoc[@section] and xref:commands/subsection.adoc[@subsection] commands if you want to add structure without creating multiple pages.

Here is an example:

```
/*! @mainpage A simple manual

Some general info.

This manual is divided in the following sections:
- @subpage intro
- @subpage advanced "Advanced usage"
*/

//-----------------------------------------------------------

/*! @page intro Introduction
This page introduces the user to the topic.
Now you can proceed to the @ref advanced "advanced section".
*/

//-----------------------------------------------------------

/*! @page advanced Advanced Usage
This page is for advanced users.
Make sure you have first read @ref intro "the introduction".
*/

```
// [CODE_END]


*Note:* Each page can be the sub page of only one other page and no cyclic relations are allowed, i.e. the page hierarchy must have a tree structure.