= Reference
:mrdocs:

[#index]
== Global namespace

=== Types

[cols=1]
|===
| Name
| link:#A[`A`] 
|===

[#A]
== A

=== Synopsis

Declared in `&lt;qualifiers&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct A;
----

=== Types

[cols=1]
|===
| Name
| link:#A-const_iterator[`const&lowbar;iterator`] 
| link:#A-iterator[`iterator`] 
|===

=== Member Functions

[cols="1,4"]
|===
| Name| Description
| link:#A-begin-03[`begin`] 
| `begin` overloads
| link:#A-cbegin[`cbegin`] 
| Return a const iterator to the beginning
| link:#A-crvalue[`crvalue`] 
| An const rvalue reference to A
| link:#A-ref-05f[`ref`] 
| `ref` overloads
| link:#A-rvalue[`rvalue`] 
| An rvalue reference to A
|===

[#A-const_iterator]
== link:#A[A]::const&lowbar;iterator

=== Synopsis

Declared in `&lt;qualifiers&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
class const&lowbar;iterator;
----

[#A-iterator]
== link:#A[A]::iterator

=== Synopsis

Declared in `&lt;qualifiers&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
class iterator;
----

[#A-begin-03]
== link:#A[A]::begin

`begin` overloads

=== Synopses

Declared in `&lt;qualifiers&period;cpp&gt;`

Returns an iterator to the beginning


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-iterator[iterator]
link:#A-begin-06[begin]();
----

[.small]#link:#A-begin-06[_» more&period;&period;&period;_]#

Return a const iterator to the beginning


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-const_iterator[const&lowbar;iterator]
link:#A-begin-0c[begin]() const;
----

[.small]#link:#A-begin-0c[_» more&period;&period;&period;_]#

=== Return Value

* Iterator to the first element&period;
* Const iterator to the first element&period;

[#A-begin-06]
== link:#A[A]::begin

Returns an iterator to the beginning

=== Synopsis

Declared in `&lt;qualifiers&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-iterator[iterator]
begin();
----

=== Description

Returns an iterator to the first element of the vector&period;

=== Return Value

Iterator to the first element&period;

[#A-begin-0c]
== link:#A[A]::begin

Return a const iterator to the beginning

=== Synopsis

Declared in `&lt;qualifiers&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-const_iterator[const&lowbar;iterator]
begin() const;
----

=== Description

Returns a const iterator to the first element of the vector&period;

=== Return Value

Const iterator to the first element&period;

[#A-cbegin]
== link:#A[A]::cbegin

Return a const iterator to the beginning

=== Synopsis

Declared in `&lt;qualifiers&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A-const_iterator[const&lowbar;iterator]
cbegin() const;
----

=== Description

Returns a const iterator to the first element of the vector&period;

=== Return Value

Const iterator to the first element&period;

[#A-crvalue]
== link:#A[A]::crvalue

An const rvalue reference to A

=== Synopsis

Declared in `&lt;qualifiers&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A[A]&&
crvalue() const &amp;&amp;;
----

=== Return Value

A reference to A

[#A-ref-05f]
== link:#A[A]::ref

`ref` overloads

=== Synopses

Declared in `&lt;qualifiers&period;cpp&gt;`

An lvalue reference to A


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A[A]&
link:#A-ref-051[ref]() &amp;;
----

[.small]#link:#A-ref-051[_» more&period;&period;&period;_]#

An rvalue reference to A


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A[A]&&
link:#A-ref-0e[ref]() &amp;&amp;;
----

[.small]#link:#A-ref-0e[_» more&period;&period;&period;_]#

An const lvalue reference to A


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A[A] const&
link:#A-ref-04[ref]() const &amp;;
----

[.small]#link:#A-ref-04[_» more&period;&period;&period;_]#

An const rvalue reference to A


[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A[A] const&&
link:#A-ref-07[ref]() const &amp;&amp;;
----

[.small]#link:#A-ref-07[_» more&period;&period;&period;_]#

=== Return Value

A reference to A

[#A-ref-051]
== link:#A[A]::ref

An lvalue reference to A

=== Synopsis

Declared in `&lt;qualifiers&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A[A]&
ref() &amp;;
----

=== Return Value

A reference to A

[#A-ref-0e]
== link:#A[A]::ref

An rvalue reference to A

=== Synopsis

Declared in `&lt;qualifiers&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A[A]&&
ref() &amp;&amp;;
----

=== Return Value

A reference to A

[#A-ref-04]
== link:#A[A]::ref

An const lvalue reference to A

=== Synopsis

Declared in `&lt;qualifiers&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A[A] const&
ref() const &amp;;
----

=== Return Value

A reference to A

[#A-ref-07]
== link:#A[A]::ref

An const rvalue reference to A

=== Synopsis

Declared in `&lt;qualifiers&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A[A] const&&
ref() const &amp;&amp;;
----

=== Return Value

A reference to A

[#A-rvalue]
== link:#A[A]::rvalue

An rvalue reference to A

=== Synopsis

Declared in `&lt;qualifiers&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
link:#A[A]&&
rvalue() &amp;&amp;;
----

=== Return Value

A reference to A


[.small]#Created with https://www.mrdocs.com[MrDocs]#
