= Reference
:mrdocs:

[#index]
== Global namespace

===  Types
[cols=2]
|===
| Name | Description 

| <<#R0,`R0`>> 
| 
    
| <<#R1,`R1`>> 
| 
    
| <<#R10,`R10`>> 
| 
    
| <<#R11,`R11`>> 
| 
    
| <<#R12,`R12`>> 
| 
    
| <<#R13,`R13`>> 
| 
    
| <<#R14,`R14`>> 
| 
    
| <<#R15,`R15`>> 
| 
    
| <<#R16,`R16`>> 
| 
    
| <<#R17,`R17`>> 
| 
    
| <<#R18,`R18`>> 
| 
    
| <<#R19,`R19`>> 
| 
    
| <<#R2,`R2`>> 
| 
    
| <<#R20,`R20`>> 
| 
    
| <<#R21,`R21`>> 
| 
    
| <<#R22,`R22`>> 
| 
    
| <<#R23,`R23`>> 
| 
    
| <<#R24,`R24`>> 
| 
    
| <<#R25,`R25`>> 
| 
    
| <<#R26,`R26`>> 
| 
    
| <<#R27,`R27`>> 
| 
    
| <<#R28,`R28`>> 
| 
    
| <<#R29,`R29`>> 
| 
    
| <<#R3,`R3`>> 
| 
    
| <<#R30,`R30`>> 
| 
    
| <<#R31,`R31`>> 
| 
    
| <<#R32,`R32`>> 
| 
    
| <<#R33,`R33`>> 
| 
    
| <<#R34,`R34`>> 
| 
    
| <<#R35,`R35`>> 
| 
    
| <<#R36,`R36`>> 
| 
    
| <<#R37,`R37`>> 
| 
    
| <<#R38,`R38`>> 
| 
    
| <<#R39,`R39`>> 
| 
    
| <<#R4,`R4`>> 
| 
    
| <<#R40,`R40`>> 
| 
    
| <<#R41,`R41`>> 
| 
    
| <<#R42,`R42`>> 
| 
    
| <<#R43,`R43`>> 
| 
    
| <<#R44,`R44`>> 
| 
    
| <<#R45,`R45`>> 
| 
    
| <<#R46,`R46`>> 
| 
    
| <<#R47,`R47`>> 
| 
    
| <<#R48,`R48`>> 
| 
    
| <<#R5,`R5`>> 
| 
    
| <<#R6,`R6`>> 
| 
    
| <<#R7,`R7`>> 
| 
    
| <<#R8,`R8`>> 
| 
    
| <<#R9,`R9`>> 
| 
    
| <<#S0-02,`S0<1, int*>`>> 
| 
    
| <<#S0-0c4,`S0<1, T*>`>> 
| 
    
| <<#S0-0be,`S0<0>`>> 
| 
    
| <<#S0-0cf,`S0`>> 
| 
    
|===

[#S0-0cf]
== S0



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int I,
    typename T = void>
struct S0;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1,`S1`>> 
| 
    
| <<#S0-0cf-S5,`S5`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-f0,`f0`>> 
| 
    
|===



[#S0-0cf-f0]
== <<#S0-0cf,S0>>::f0



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f0();
----








[#S0-0cf-S1]
== <<#S0-0cf,S0>>::S1



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct S1;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2,`S2`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-f1,`f1`>> 
| 
    
|===



[#S0-0cf-S1-f1]
== <<#S0-0cf,S0>>::<<#S0-0cf-S1,S1>>::f1



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f1();
----








[#S0-0cf-S1-S2]
== <<#S0-0cf,S0>>::<<#S0-0cf-S1,S1>>::S2



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int J,
    typename U = void>
struct S2;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S3,`S3`>> 
| 
    
| <<#S0-0cf-S1-S2-S4,`S4`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-f2,`f2`>> 
| 
    
|===



[#S0-0cf-S1-S2-f2]
== <<#S0-0cf,S0>>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>::f2



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f2();
----








[#S0-0cf-S1-S2-S3]
== <<#S0-0cf,S0>>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>::S3



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct S3;
----

===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S3-f3,`f3`>> 
| 
    
|===



[#S0-0cf-S1-S2-S3-f3]
== <<#S0-0cf,S0>>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>::<<#S0-0cf-S1-S2-S3,S3>>::f3



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f3();
----








[#S0-0cf-S1-S2-S4]
== <<#S0-0cf,S0>>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>::S4



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int K,
    typename V = void>
struct S4;
----

===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S4-f4,`f4`>> 
| 
    
|===



[#S0-0cf-S1-S2-S4-f4]
== <<#S0-0cf,S0>>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>::<<#S0-0cf-S1-S2-S4,S4>>::f4



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f4();
----








[#S0-0cf-S5]
== <<#S0-0cf,S0>>::S5



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int J,
    typename U = void>
struct S5;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6,`S6`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-f5,`f5`>> 
| 
    
|===



[#S0-0cf-S5-f5]
== <<#S0-0cf,S0>>::<<#S0-0cf-S5,S5>>::f5



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f5();
----








[#S0-0cf-S5-S6]
== <<#S0-0cf,S0>>::<<#S0-0cf-S5,S5>>::S6



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct S6;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7,`S7`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-f6,`f6`>> 
| 
    
|===



[#S0-0cf-S5-S6-f6]
== <<#S0-0cf,S0>>::<<#S0-0cf-S5,S5>>::<<#S0-0cf-S5-S6,S6>>::f6



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f6();
----








[#S0-0cf-S5-S6-S7]
== <<#S0-0cf,S0>>::<<#S0-0cf-S5,S5>>::<<#S0-0cf-S5-S6,S6>>::S7



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int K,
    typename V = void>
struct S7;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S8,`S8`>> 
| 
    
| <<#S0-0cf-S5-S6-S7-S9,`S9`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-f7,`f7`>> 
| 
    
|===



[#S0-0cf-S5-S6-S7-f7]
== <<#S0-0cf,S0>>::<<#S0-0cf-S5,S5>>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>::f7



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f7();
----








[#S0-0cf-S5-S6-S7-S8]
== <<#S0-0cf,S0>>::<<#S0-0cf-S5,S5>>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>::S8



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct S8;
----

===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S8-f8,`f8`>> 
| 
    
|===



[#S0-0cf-S5-S6-S7-S8-f8]
== <<#S0-0cf,S0>>::<<#S0-0cf-S5,S5>>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>::<<#S0-0cf-S5-S6-S7-S8,S8>>::f8



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f8();
----








[#S0-0cf-S5-S6-S7-S9]
== <<#S0-0cf,S0>>::<<#S0-0cf-S5,S5>>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>::S9



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int L,
    typename W = void>
struct S9;
----

===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S9-f9,`f9`>> 
| 
    
|===



[#S0-0cf-S5-S6-S7-S9-f9]
== <<#S0-0cf,S0>>::<<#S0-0cf-S5,S5>>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>::<<#S0-0cf-S5-S6-S7-S9,S9>>::f9



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f9();
----








[#S0-0be]
== S0



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<>
struct <<#S0-0cf,S0>><0>;
----




[#S0-0c4]
== S0



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<typename T>
struct <<#S0-0cf,S0>><1, T*>;
----




[#S0-02]
== S0



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<>
struct <<#S0-0cf,S0>><1, int*>;
----




[#R0]
== R0



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R0
    : <<#S0-0cf,S0>><pass:[-1]>;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1,`S1`>> 
| 
    
| <<#S0-0cf-S5,`S5`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-f0,`f0`>> 
| 
    
|===



[#R1]
== R1



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R1
    : <<#S0-0be,S0>><0>;
----




[#R2]
== R2



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R2
    : <<#S0-0c4,S0>><1, void*>;
----




[#R3]
== R3



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R3
    : <<#S0-02,S0>><1, int*>;
----




[#R4]
== R4



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R4
    : <<#S0-0cf,S0>><2>::<<#S0-09c-S1,S1>>;
----




[#R5]
== R5



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R5
    : <<#S0-0cf,S0>><3>::<<#S0-0cf-S1,S1>>::<<#S0-073-S1-S2,S2>><pass:[-1]>;
----




[#R6]
== R6



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R6
    : <<#S0-0cf,S0>><4>::<<#S0-0cf-S1,S1>>::<<#S0-0a1-S1-S2,S2>><5>;
----




[#R7]
== R7



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R7
    : <<#S0-0cf,S0>><6>::<<#S0-0cf-S1,S1>>::<<#S0-07e-S1-S2-06,S2>><7, void*>;
----




[#R8]
== R8



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R8
    : <<#S0-0cf,S0>><6>::<<#S0-0cf-S1,S1>>::<<#S0-07e-S1-S2-07,S2>><7, int*>;
----




[#R9]
== R9



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R9
    : <<#S0-0cf,S0>><8>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>><9>::<<#S0-0a3-S1-S2-S3,S3>>;
----




[#R10]
== R10



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R10
    : <<#S0-0cf,S0>><10>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>><11>::<<#S0-08-S1-S2-S4,S4>><pass:[-1]>;
----




[#R11]
== R11



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R11
    : <<#S0-0cf,S0>><12>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>><13>::<<#S0-0e-S1-S2-S4,S4>><14>;
----




[#R12]
== R12



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R12
    : <<#S0-0cf,S0>><15>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>><16>::<<#S0-09e4-S1-S2-S4-07,S4>><17, void*>;
----




[#R13]
== R13



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R13
    : <<#S0-0cf,S0>><15>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>><16>::<<#S0-09e4-S1-S2-S4-02,S4>><17, int*>;
----




[#R14]
== R14



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R14
    : <<#S0-0cf,S0>><18>::<<#S0-07a-S5,S5>><pass:[-1]>;
----




[#R15]
== R15



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R15
    : <<#S0-0cf,S0>><19>::<<#S0-0a7-S5,S5>><20>;
----




[#R16]
== R16



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R16
    : <<#S0-0cf,S0>><21>::<<#S0-031-S5-0b,S5>><22, void*>;
----




[#R17]
== R17



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R17
    : <<#S0-0cf,S0>><21>::<<#S0-031-S5-03,S5>><22, int*>;
----




[#R18]
== R18



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R18
    : <<#S0-0cf,S0>><23>::<<#S0-0cf-S5,S5>><24>::<<#S0-05-S5-S6,S6>>;
----




[#R19]
== R19



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R19
    : <<#S0-0cf,S0>><25>::<<#S0-0cf-S5,S5>><26>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0a2-S5-S6-S7,S7>><pass:[-1]>;
----




[#R20]
== R20



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R20
    : <<#S0-0cf,S0>><27>::<<#S0-0cf-S5,S5>><28>::<<#S0-0cf-S5-S6,S6>>::<<#S0-09e2-S5-S6-S7-0a,S7>><29, void*>;
----




[#R21]
== R21



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R21
    : <<#S0-0cf,S0>><27>::<<#S0-0cf-S5,S5>><28>::<<#S0-0cf-S5-S6,S6>>::<<#S0-09e2-S5-S6-S7-0d,S7>><29, int*>;
----




[#R22]
== R22



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R22
    : <<#S0-0cf,S0>><30>::<<#S0-0cf-S5,S5>><31>::<<#S0-0cf-S5-S6,S6>>::<<#S0-01-S5-S6-S7,S7>><32>;
----




[#R23]
== R23



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R23
    : <<#S0-0cf,S0>><33>::<<#S0-0cf-S5,S5>><34>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>><35>::<<#S0-09ee-S5-S6-S7-S8,S8>>;
----




[#R24]
== R24



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R24
    : <<#S0-0cf,S0>><36>::<<#S0-0cf-S5,S5>><37>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>><38>::<<#S0-033-S5-S6-S7-S9,S9>><pass:[-1]>;
----




[#R25]
== R25



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R25
    : <<#S0-0cf,S0>><39>::<<#S0-0cf-S5,S5>><40>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>><41>::<<#S0-06-S5-S6-S7-S9-00,S9>><42, void*>;
----




[#R26]
== R26



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R26
    : <<#S0-0cf,S0>><39>::<<#S0-0cf-S5,S5>><40>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>><41>::<<#S0-06-S5-S6-S7-S9-08,S9>><42, int*>;
----




[#R27]
== R27



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R27
    : <<#S0-0cf,S0>><43>::<<#S0-0cf-S5,S5>><44>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>><45>::<<#S0-0ba-S5-S6-S7-S9,S9>><46>;
----




[#R28]
== R28



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R28
    : <<#S0-0cf,S0>><0, bool>;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1,`S1`>> 
| 
    
| <<#S0-0cf-S5,`S5`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-f0,`f0`>> 
| 
    
|===



[#R29]
== R29



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R29
    : <<#S0-0cf,S0>><1, int>;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1,`S1`>> 
| 
    
| <<#S0-0cf-S5,`S5`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-f0,`f0`>> 
| 
    
|===



[#R30]
== R30



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R30
    : <<#S0-0cf,S0>><2, bool>::<<#S0-0cf-S1,S1>>;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2,`S2`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-f1,`f1`>> 
| 
    
|===



[#R31]
== R31



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int I,
    typename T>
struct R31
    : <<#S0-0cf,S0>><3, bool>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>><I, T>;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S3,`S3`>> 
| 
    
| <<#S0-0cf-S1-S2-S4,`S4`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-f2,`f2`>> 
| 
    
|===



[#R32]
== R32



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R32
    : <<#S0-0cf,S0>><4, bool>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>><5, bool>;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S3,`S3`>> 
| 
    
| <<#S0-0cf-S1-S2-S4,`S4`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-f2,`f2`>> 
| 
    
|===



[#R33]
== R33



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R33
    : <<#S0-0cf,S0>><6, bool>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>><7, int>;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S3,`S3`>> 
| 
    
| <<#S0-0cf-S1-S2-S4,`S4`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-f2,`f2`>> 
| 
    
|===



[#R34]
== R34



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R34
    : <<#S0-0cf,S0>><8, bool>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>><9, bool>::<<#S0-0cf-S1-S2-S3,S3>>;
----

===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S3-f3,`f3`>> 
| 
    
|===



[#R35]
== R35



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int I,
    typename T>
struct R35
    : <<#S0-0cf,S0>><10, bool>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>><11, bool>::<<#S0-0cf-S1-S2-S4,S4>><I, T>;
----

===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S4-f4,`f4`>> 
| 
    
|===



[#R36]
== R36



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R36
    : <<#S0-0cf,S0>><12, bool>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>><13, bool>::<<#S0-0cf-S1-S2-S4,S4>><14, bool>;
----

===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S4-f4,`f4`>> 
| 
    
|===



[#R37]
== R37



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R37
    : <<#S0-0cf,S0>><15, bool>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>><16, bool>::<<#S0-0cf-S1-S2-S4,S4>><17, int>;
----

===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S4-f4,`f4`>> 
| 
    
|===



[#R38]
== R38



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int I,
    typename T>
struct R38
    : <<#S0-0cf,S0>><18, bool>::<<#S0-0cf-S5,S5>><I, T>;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6,`S6`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-f5,`f5`>> 
| 
    
|===



[#R39]
== R39



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R39
    : <<#S0-0cf,S0>><19, bool>::<<#S0-0cf-S5,S5>><20, bool>;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6,`S6`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-f5,`f5`>> 
| 
    
|===



[#R40]
== R40



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R40
    : <<#S0-0cf,S0>><21, bool>::<<#S0-0cf-S5,S5>><22, int>;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6,`S6`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-f5,`f5`>> 
| 
    
|===



[#R41]
== R41



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R41
    : <<#S0-0cf,S0>><23, bool>::<<#S0-0cf-S5,S5>><24, bool>::<<#S0-0cf-S5-S6,S6>>;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7,`S7`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-f6,`f6`>> 
| 
    
|===



[#R42]
== R42



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int I,
    typename T>
struct R42
    : <<#S0-0cf,S0>><25, bool>::<<#S0-0cf-S5,S5>><26, bool>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>><I, T>;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S8,`S8`>> 
| 
    
| <<#S0-0cf-S5-S6-S7-S9,`S9`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-f7,`f7`>> 
| 
    
|===



[#R43]
== R43



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R43
    : <<#S0-0cf,S0>><27, bool>::<<#S0-0cf-S5,S5>><28, bool>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>><29, int>;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S8,`S8`>> 
| 
    
| <<#S0-0cf-S5-S6-S7-S9,`S9`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-f7,`f7`>> 
| 
    
|===



[#R44]
== R44



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R44
    : <<#S0-0cf,S0>><30, bool>::<<#S0-0cf-S5,S5>><31, bool>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>><32, bool>;
----

===  Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S8,`S8`>> 
| 
    
| <<#S0-0cf-S5-S6-S7-S9,`S9`>> 
| 
    
|===
===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-f7,`f7`>> 
| 
    
|===



[#R45]
== R45



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R45
    : <<#S0-0cf,S0>><33, bool>::<<#S0-0cf-S5,S5>><34, bool>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>><35, bool>::<<#S0-0cf-S5-S6-S7-S8,S8>>;
----

===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S8-f8,`f8`>> 
| 
    
|===



[#R46]
== R46



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int I,
    typename T>
struct R46
    : <<#S0-0cf,S0>><36, bool>::<<#S0-0cf-S5,S5>><37, bool>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>><38, bool>::<<#S0-0cf-S5-S6-S7-S9,S9>><I, T>;
----

===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S9-f9,`f9`>> 
| 
    
|===



[#R47]
== R47



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R47
    : <<#S0-0cf,S0>><39, bool>::<<#S0-0cf-S5,S5>><40, bool>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>><41, bool>::<<#S0-0cf-S5-S6-S7-S9,S9>><42, int>;
----

===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S9-f9,`f9`>> 
| 
    
|===



[#R48]
== R48



=== Synopsis

Declared in `<pass:[class-template-specializations-1.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R48
    : <<#S0-0cf,S0>><43, bool>::<<#S0-0cf-S5,S5>><44, bool>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>><45, bool>::<<#S0-0cf-S5-S6-S7-S9,S9>><46, bool>;
----

===  Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S9-f9,`f9`>> 
| 
    
|===





[.small]#Created with https://www.mrdocs.com[MrDocs]#
