= Reference
:mrdocs:

[#index]

== Global namespace

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:R0.adoc[`R0`]  ¦

¦xref:R1.adoc[`R1`]  ¦

¦xref:R10.adoc[`R10`]  ¦

¦xref:R11.adoc[`R11`]  ¦

¦xref:R12.adoc[`R12`]  ¦

¦xref:R13.adoc[`R13`]  ¦

¦xref:R14.adoc[`R14`]  ¦

¦xref:R15.adoc[`R15`]  ¦

¦xref:R16.adoc[`R16`]  ¦

¦xref:R17.adoc[`R17`]  ¦

¦xref:R18.adoc[`R18`]  ¦

¦xref:R19.adoc[`R19`]  ¦

¦xref:R2.adoc[`R2`]  ¦

¦xref:R20.adoc[`R20`]  ¦

¦xref:R21.adoc[`R21`]  ¦

¦xref:R22.adoc[`R22`]  ¦

¦xref:R23.adoc[`R23`]  ¦

¦xref:R24.adoc[`R24`]  ¦

¦xref:R25.adoc[`R25`]  ¦

¦xref:R26.adoc[`R26`]  ¦

¦xref:R27.adoc[`R27`]  ¦

¦xref:R28.adoc[`R28`]  ¦

¦xref:R29.adoc[`R29`]  ¦

¦xref:R3.adoc[`R3`]  ¦

¦xref:R30.adoc[`R30`]  ¦

¦xref:R31.adoc[`R31`]  ¦

¦xref:R32.adoc[`R32`]  ¦

¦xref:R33.adoc[`R33`]  ¦

¦xref:R34.adoc[`R34`]  ¦

¦xref:R35.adoc[`R35`]  ¦

¦xref:R36.adoc[`R36`]  ¦

¦xref:R37.adoc[`R37`]  ¦

¦xref:R38.adoc[`R38`]  ¦

¦xref:R39.adoc[`R39`]  ¦

¦xref:R4.adoc[`R4`]  ¦

¦xref:R40.adoc[`R40`]  ¦

¦xref:R41.adoc[`R41`]  ¦

¦xref:R42.adoc[`R42`]  ¦

¦xref:R43.adoc[`R43`]  ¦

¦xref:R44.adoc[`R44`]  ¦

¦xref:R45.adoc[`R45`]  ¦

¦xref:R46.adoc[`R46`]  ¦

¦xref:R47.adoc[`R47`]  ¦

¦xref:R48.adoc[`R48`]  ¦

¦xref:R5.adoc[`R5`]  ¦

¦xref:R6.adoc[`R6`]  ¦

¦xref:R7.adoc[`R7`]  ¦

¦xref:R8.adoc[`R8`]  ¦

¦xref:R9.adoc[`R9`]  ¦

¦xref:S0-02.adoc[`S0<1, int*>`]  ¦

¦xref:S0-0c4.adoc[`S0<1, T*>`]  ¦

¦xref:S0-0be.adoc[`S0<0>`]  ¦

¦xref:S0-0cf.adoc[`S0`]  ¦

|===


[#S0-0cf]

== S0



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int I,
    typename T = void>
struct S0;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1.adoc[`S1`]  ¦

¦xref:S0-0cf/S5.adoc[`S5`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/f0.adoc[`f0`]  ¦

|===



:relfileprefix: ../
[#S0-0cf-f0]

== xref:S0-0cf.adoc[pass:[S0]]::f0



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f0();
----








:relfileprefix: ../
[#S0-0cf-S1]

== xref:S0-0cf.adoc[pass:[S0]]::S1



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct S1;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1/S2.adoc[`S2`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1/f1.adoc[`f1`]  ¦

|===



:relfileprefix: ../../
[#S0-0cf-S1-f1]

== xref:S0-0cf.adoc[pass:[S0]]::xref:S0-0cf/S1.adoc[pass:[S1]]::f1



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f1();
----








:relfileprefix: ../../
[#S0-0cf-S1-S2]

== xref:S0-0cf.adoc[pass:[S0]]::xref:S0-0cf/S1.adoc[pass:[S1]]::S2



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int J,
    typename U = void>
struct S2;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1/S2/S3.adoc[`S3`]  ¦

¦xref:S0-0cf/S1/S2/S4.adoc[`S4`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1/S2/f2.adoc[`f2`]  ¦

|===



:relfileprefix: ../../../
[#S0-0cf-S1-S2-f2]

== xref:S0-0cf.adoc[pass:[S0]]::xref:S0-0cf/S1.adoc[pass:[S1]]::xref:S0-0cf/S1/S2.adoc[pass:[S2]]::f2



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f2();
----








:relfileprefix: ../../../
[#S0-0cf-S1-S2-S3]

== xref:S0-0cf.adoc[pass:[S0]]::xref:S0-0cf/S1.adoc[pass:[S1]]::xref:S0-0cf/S1/S2.adoc[pass:[S2]]::S3



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct S3;
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1/S2/S3/f3.adoc[`f3`]  ¦

|===



:relfileprefix: ../../../../
[#S0-0cf-S1-S2-S3-f3]

== xref:S0-0cf.adoc[pass:[S0]]::xref:S0-0cf/S1.adoc[pass:[S1]]::xref:S0-0cf/S1/S2.adoc[pass:[S2]]::xref:S0-0cf/S1/S2/S3.adoc[pass:[S3]]::f3



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f3();
----








:relfileprefix: ../../../
[#S0-0cf-S1-S2-S4]

== xref:S0-0cf.adoc[pass:[S0]]::xref:S0-0cf/S1.adoc[pass:[S1]]::xref:S0-0cf/S1/S2.adoc[pass:[S2]]::S4



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int K,
    typename V = void>
struct S4;
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1/S2/S4/f4.adoc[`f4`]  ¦

|===



:relfileprefix: ../../../../
[#S0-0cf-S1-S2-S4-f4]

== xref:S0-0cf.adoc[pass:[S0]]::xref:S0-0cf/S1.adoc[pass:[S1]]::xref:S0-0cf/S1/S2.adoc[pass:[S2]]::xref:S0-0cf/S1/S2/S4.adoc[pass:[S4]]::f4



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f4();
----








:relfileprefix: ../
[#S0-0cf-S5]

== xref:S0-0cf.adoc[pass:[S0]]::S5



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int J,
    typename U = void>
struct S5;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6.adoc[`S6`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/f5.adoc[`f5`]  ¦

|===



:relfileprefix: ../../
[#S0-0cf-S5-f5]

== xref:S0-0cf.adoc[pass:[S0]]::xref:S0-0cf/S5.adoc[pass:[S5]]::f5



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f5();
----








:relfileprefix: ../../
[#S0-0cf-S5-S6]

== xref:S0-0cf.adoc[pass:[S0]]::xref:S0-0cf/S5.adoc[pass:[S5]]::S6



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct S6;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6/S7.adoc[`S7`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6/f6.adoc[`f6`]  ¦

|===



:relfileprefix: ../../../
[#S0-0cf-S5-S6-f6]

== xref:S0-0cf.adoc[pass:[S0]]::xref:S0-0cf/S5.adoc[pass:[S5]]::xref:S0-0cf/S5/S6.adoc[pass:[S6]]::f6



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f6();
----








:relfileprefix: ../../../
[#S0-0cf-S5-S6-S7]

== xref:S0-0cf.adoc[pass:[S0]]::xref:S0-0cf/S5.adoc[pass:[S5]]::xref:S0-0cf/S5/S6.adoc[pass:[S6]]::S7



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int K,
    typename V = void>
struct S7;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6/S7/S8.adoc[`S8`]  ¦

¦xref:S0-0cf/S5/S6/S7/S9.adoc[`S9`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6/S7/f7.adoc[`f7`]  ¦

|===



:relfileprefix: ../../../../
[#S0-0cf-S5-S6-S7-f7]

== xref:S0-0cf.adoc[pass:[S0]]::xref:S0-0cf/S5.adoc[pass:[S5]]::xref:S0-0cf/S5/S6.adoc[pass:[S6]]::xref:S0-0cf/S5/S6/S7.adoc[pass:[S7]]::f7



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f7();
----








:relfileprefix: ../../../../
[#S0-0cf-S5-S6-S7-S8]

== xref:S0-0cf.adoc[pass:[S0]]::xref:S0-0cf/S5.adoc[pass:[S5]]::xref:S0-0cf/S5/S6.adoc[pass:[S6]]::xref:S0-0cf/S5/S6/S7.adoc[pass:[S7]]::S8



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct S8;
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6/S7/S8/f8.adoc[`f8`]  ¦

|===



:relfileprefix: ../../../../../
[#S0-0cf-S5-S6-S7-S8-f8]

== xref:S0-0cf.adoc[pass:[S0]]::xref:S0-0cf/S5.adoc[pass:[S5]]::xref:S0-0cf/S5/S6.adoc[pass:[S6]]::xref:S0-0cf/S5/S6/S7.adoc[pass:[S7]]::xref:S0-0cf/S5/S6/S7/S8.adoc[pass:[S8]]::f8



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f8();
----








:relfileprefix: ../../../../
[#S0-0cf-S5-S6-S7-S9]

== xref:S0-0cf.adoc[pass:[S0]]::xref:S0-0cf/S5.adoc[pass:[S5]]::xref:S0-0cf/S5/S6.adoc[pass:[S6]]::xref:S0-0cf/S5/S6/S7.adoc[pass:[S7]]::S9



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int L,
    typename W = void>
struct S9;
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6/S7/S9/f9.adoc[`f9`]  ¦

|===



:relfileprefix: ../../../../../
[#S0-0cf-S5-S6-S7-S9-f9]

== xref:S0-0cf.adoc[pass:[S0]]::xref:S0-0cf/S5.adoc[pass:[S5]]::xref:S0-0cf/S5/S6.adoc[pass:[S6]]::xref:S0-0cf/S5/S6/S7.adoc[pass:[S7]]::xref:S0-0cf/S5/S6/S7/S9.adoc[pass:[S9]]::f9



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f9();
----









[#S0-0be]

== S0



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<>
struct xref:S0-0cf.adoc[pass:[S0]]<0>;
----





[#S0-0c4]

== S0



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<typename T>
struct xref:S0-0cf.adoc[pass:[S0]]<1, T*>;
----





[#S0-02]

== S0



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<>
struct xref:S0-0cf.adoc[pass:[S0]]<1, int*>;
----





[#S0-09c]


[#S0-073]


[#S0-0a1]


[#S0-07e]


[#S0-0a3]


[#S0-08]


[#S0-0e]


[#S0-09e4]


[#S0-07a]


[#S0-0a7]


[#S0-031]


[#S0-05]


[#S0-0a2]


[#S0-09e2]


[#S0-01]


[#S0-09ee]


[#S0-033]


[#S0-06]


[#S0-0ba]


[#R0]

== R0



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R0
    : xref:S0-0cf.adoc[S0]<-1>;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1.adoc[`S1`]  ¦

¦xref:S0-0cf/S5.adoc[`S5`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/f0.adoc[`f0`]  ¦

|===




[#R1]

== R1



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R1
    : xref:S0-0be.adoc[S0]<0>;
----





[#R2]

== R2



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R2
    : xref:S0-0c4.adoc[S0]<1, void*>;
----





[#R3]

== R3



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R3
    : xref:S0-02.adoc[S0]<1, int*>;
----





[#R4]

== R4



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R4
    : xref:S0-0cf.adoc[S0]<2>::xref:S0-09c/S1.adoc[S1];
----





[#R5]

== R5



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R5
    : xref:S0-0cf.adoc[S0]<3>::xref:S0-0cf/S1.adoc[S1]::xref:S0-073/S1/S2.adoc[S2]<-1>;
----





[#R6]

== R6



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R6
    : xref:S0-0cf.adoc[S0]<4>::xref:S0-0cf/S1.adoc[S1]::xref:S0-0a1/S1/S2.adoc[S2]<5>;
----





[#R7]

== R7



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R7
    : xref:S0-0cf.adoc[S0]<6>::xref:S0-0cf/S1.adoc[S1]::xref:S0-07e/S1/S2-06.adoc[S2]<7, void*>;
----





[#R8]

== R8



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R8
    : xref:S0-0cf.adoc[S0]<6>::xref:S0-0cf/S1.adoc[S1]::xref:S0-07e/S1/S2-07.adoc[S2]<7, int*>;
----





[#R9]

== R9



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R9
    : xref:S0-0cf.adoc[S0]<8>::xref:S0-0cf/S1.adoc[S1]::xref:S0-0cf/S1/S2.adoc[S2]<9>::xref:S0-0a3/S1/S2/S3.adoc[S3];
----





[#R10]

== R10



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R10
    : xref:S0-0cf.adoc[S0]<10>::xref:S0-0cf/S1.adoc[S1]::xref:S0-0cf/S1/S2.adoc[S2]<11>::xref:S0-08/S1/S2/S4.adoc[S4]<-1>;
----





[#R11]

== R11



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R11
    : xref:S0-0cf.adoc[S0]<12>::xref:S0-0cf/S1.adoc[S1]::xref:S0-0cf/S1/S2.adoc[S2]<13>::xref:S0-0e/S1/S2/S4.adoc[S4]<14>;
----





[#R12]

== R12



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R12
    : xref:S0-0cf.adoc[S0]<15>::xref:S0-0cf/S1.adoc[S1]::xref:S0-0cf/S1/S2.adoc[S2]<16>::xref:S0-09e4/S1/S2/S4-07.adoc[S4]<17, void*>;
----





[#R13]

== R13



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R13
    : xref:S0-0cf.adoc[S0]<15>::xref:S0-0cf/S1.adoc[S1]::xref:S0-0cf/S1/S2.adoc[S2]<16>::xref:S0-09e4/S1/S2/S4-02.adoc[S4]<17, int*>;
----





[#R14]

== R14



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R14
    : xref:S0-0cf.adoc[S0]<18>::xref:S0-07a/S5.adoc[S5]<-1>;
----





[#R15]

== R15



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R15
    : xref:S0-0cf.adoc[S0]<19>::xref:S0-0a7/S5.adoc[S5]<20>;
----





[#R16]

== R16



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R16
    : xref:S0-0cf.adoc[S0]<21>::xref:S0-031/S5-0b.adoc[S5]<22, void*>;
----





[#R17]

== R17



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R17
    : xref:S0-0cf.adoc[S0]<21>::xref:S0-031/S5-03.adoc[S5]<22, int*>;
----





[#R18]

== R18



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R18
    : xref:S0-0cf.adoc[S0]<23>::xref:S0-0cf/S5.adoc[S5]<24>::xref:S0-05/S5/S6.adoc[S6];
----





[#R19]

== R19



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R19
    : xref:S0-0cf.adoc[S0]<25>::xref:S0-0cf/S5.adoc[S5]<26>::xref:S0-0cf/S5/S6.adoc[S6]::xref:S0-0a2/S5/S6/S7.adoc[S7]<-1>;
----





[#R20]

== R20



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R20
    : xref:S0-0cf.adoc[S0]<27>::xref:S0-0cf/S5.adoc[S5]<28>::xref:S0-0cf/S5/S6.adoc[S6]::xref:S0-09e2/S5/S6/S7-0a.adoc[S7]<29, void*>;
----





[#R21]

== R21



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R21
    : xref:S0-0cf.adoc[S0]<27>::xref:S0-0cf/S5.adoc[S5]<28>::xref:S0-0cf/S5/S6.adoc[S6]::xref:S0-09e2/S5/S6/S7-0d.adoc[S7]<29, int*>;
----





[#R22]

== R22



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R22
    : xref:S0-0cf.adoc[S0]<30>::xref:S0-0cf/S5.adoc[S5]<31>::xref:S0-0cf/S5/S6.adoc[S6]::xref:S0-01/S5/S6/S7.adoc[S7]<32>;
----





[#R23]

== R23



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R23
    : xref:S0-0cf.adoc[S0]<33>::xref:S0-0cf/S5.adoc[S5]<34>::xref:S0-0cf/S5/S6.adoc[S6]::xref:S0-0cf/S5/S6/S7.adoc[S7]<35>::xref:S0-09ee/S5/S6/S7/S8.adoc[S8];
----





[#R24]

== R24



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R24
    : xref:S0-0cf.adoc[S0]<36>::xref:S0-0cf/S5.adoc[S5]<37>::xref:S0-0cf/S5/S6.adoc[S6]::xref:S0-0cf/S5/S6/S7.adoc[S7]<38>::xref:S0-033/S5/S6/S7/S9.adoc[S9]<-1>;
----





[#R25]

== R25



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R25
    : xref:S0-0cf.adoc[S0]<39>::xref:S0-0cf/S5.adoc[S5]<40>::xref:S0-0cf/S5/S6.adoc[S6]::xref:S0-0cf/S5/S6/S7.adoc[S7]<41>::xref:S0-06/S5/S6/S7/S9-00.adoc[S9]<42, void*>;
----





[#R26]

== R26



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R26
    : xref:S0-0cf.adoc[S0]<39>::xref:S0-0cf/S5.adoc[S5]<40>::xref:S0-0cf/S5/S6.adoc[S6]::xref:S0-0cf/S5/S6/S7.adoc[S7]<41>::xref:S0-06/S5/S6/S7/S9-08.adoc[S9]<42, int*>;
----





[#R27]

== R27



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R27
    : xref:S0-0cf.adoc[S0]<43>::xref:S0-0cf/S5.adoc[S5]<44>::xref:S0-0cf/S5/S6.adoc[S6]::xref:S0-0cf/S5/S6/S7.adoc[S7]<45>::xref:S0-0ba/S5/S6/S7/S9.adoc[S9]<46>;
----





[#R28]

== R28



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R28
    : xref:S0-0cf.adoc[S0]<0, bool>;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1.adoc[`S1`]  ¦

¦xref:S0-0cf/S5.adoc[`S5`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/f0.adoc[`f0`]  ¦

|===




[#R29]

== R29



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R29
    : xref:S0-0cf.adoc[S0]<1, int>;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1.adoc[`S1`]  ¦

¦xref:S0-0cf/S5.adoc[`S5`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/f0.adoc[`f0`]  ¦

|===




[#R30]

== R30



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R30
    : xref:S0-0cf.adoc[S0]<2, bool>::xref:S0-0cf/S1.adoc[S1];
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1/S2.adoc[`S2`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1/f1.adoc[`f1`]  ¦

|===




[#R31]

== R31



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int I,
    typename T>
struct R31
    : xref:S0-0cf.adoc[S0]<3, bool>::xref:S0-0cf/S1.adoc[S1]::xref:S0-0cf/S1/S2.adoc[S2]<I, T>;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1/S2/S3.adoc[`S3`]  ¦

¦xref:S0-0cf/S1/S2/S4.adoc[`S4`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1/S2/f2.adoc[`f2`]  ¦

|===




[#R32]

== R32



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R32
    : xref:S0-0cf.adoc[S0]<4, bool>::xref:S0-0cf/S1.adoc[S1]::xref:S0-0cf/S1/S2.adoc[S2]<5, bool>;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1/S2/S3.adoc[`S3`]  ¦

¦xref:S0-0cf/S1/S2/S4.adoc[`S4`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1/S2/f2.adoc[`f2`]  ¦

|===




[#R33]

== R33



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R33
    : xref:S0-0cf.adoc[S0]<6, bool>::xref:S0-0cf/S1.adoc[S1]::xref:S0-0cf/S1/S2.adoc[S2]<7, int>;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1/S2/S3.adoc[`S3`]  ¦

¦xref:S0-0cf/S1/S2/S4.adoc[`S4`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1/S2/f2.adoc[`f2`]  ¦

|===




[#R34]

== R34



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R34
    : xref:S0-0cf.adoc[S0]<8, bool>::xref:S0-0cf/S1.adoc[S1]::xref:S0-0cf/S1/S2.adoc[S2]<9, bool>::xref:S0-0cf/S1/S2/S3.adoc[S3];
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1/S2/S3/f3.adoc[`f3`]  ¦

|===




[#R35]

== R35



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int I,
    typename T>
struct R35
    : xref:S0-0cf.adoc[S0]<10, bool>::xref:S0-0cf/S1.adoc[S1]::xref:S0-0cf/S1/S2.adoc[S2]<11, bool>::xref:S0-0cf/S1/S2/S4.adoc[S4]<I, T>;
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1/S2/S4/f4.adoc[`f4`]  ¦

|===




[#R36]

== R36



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R36
    : xref:S0-0cf.adoc[S0]<12, bool>::xref:S0-0cf/S1.adoc[S1]::xref:S0-0cf/S1/S2.adoc[S2]<13, bool>::xref:S0-0cf/S1/S2/S4.adoc[S4]<14, bool>;
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1/S2/S4/f4.adoc[`f4`]  ¦

|===




[#R37]

== R37



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R37
    : xref:S0-0cf.adoc[S0]<15, bool>::xref:S0-0cf/S1.adoc[S1]::xref:S0-0cf/S1/S2.adoc[S2]<16, bool>::xref:S0-0cf/S1/S2/S4.adoc[S4]<17, int>;
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S1/S2/S4/f4.adoc[`f4`]  ¦

|===




[#R38]

== R38



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int I,
    typename T>
struct R38
    : xref:S0-0cf.adoc[S0]<18, bool>::xref:S0-0cf/S5.adoc[S5]<I, T>;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6.adoc[`S6`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/f5.adoc[`f5`]  ¦

|===




[#R39]

== R39



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R39
    : xref:S0-0cf.adoc[S0]<19, bool>::xref:S0-0cf/S5.adoc[S5]<20, bool>;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6.adoc[`S6`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/f5.adoc[`f5`]  ¦

|===




[#R40]

== R40



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R40
    : xref:S0-0cf.adoc[S0]<21, bool>::xref:S0-0cf/S5.adoc[S5]<22, int>;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6.adoc[`S6`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/f5.adoc[`f5`]  ¦

|===




[#R41]

== R41



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R41
    : xref:S0-0cf.adoc[S0]<23, bool>::xref:S0-0cf/S5.adoc[S5]<24, bool>::xref:S0-0cf/S5/S6.adoc[S6];
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6/S7.adoc[`S7`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6/f6.adoc[`f6`]  ¦

|===




[#R42]

== R42



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int I,
    typename T>
struct R42
    : xref:S0-0cf.adoc[S0]<25, bool>::xref:S0-0cf/S5.adoc[S5]<26, bool>::xref:S0-0cf/S5/S6.adoc[S6]::xref:S0-0cf/S5/S6/S7.adoc[S7]<I, T>;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6/S7/S8.adoc[`S8`]  ¦

¦xref:S0-0cf/S5/S6/S7/S9.adoc[`S9`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6/S7/f7.adoc[`f7`]  ¦

|===




[#R43]

== R43



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R43
    : xref:S0-0cf.adoc[S0]<27, bool>::xref:S0-0cf/S5.adoc[S5]<28, bool>::xref:S0-0cf/S5/S6.adoc[S6]::xref:S0-0cf/S5/S6/S7.adoc[S7]<29, int>;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6/S7/S8.adoc[`S8`]  ¦

¦xref:S0-0cf/S5/S6/S7/S9.adoc[`S9`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6/S7/f7.adoc[`f7`]  ¦

|===




[#R44]

== R44



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R44
    : xref:S0-0cf.adoc[S0]<30, bool>::xref:S0-0cf/S5.adoc[S5]<31, bool>::xref:S0-0cf/S5/S6.adoc[S6]::xref:S0-0cf/S5/S6/S7.adoc[S7]<32, bool>;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6/S7/S8.adoc[`S8`]  ¦

¦xref:S0-0cf/S5/S6/S7/S9.adoc[`S9`]  ¦

|===
===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6/S7/f7.adoc[`f7`]  ¦

|===




[#R45]

== R45



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R45
    : xref:S0-0cf.adoc[S0]<33, bool>::xref:S0-0cf/S5.adoc[S5]<34, bool>::xref:S0-0cf/S5/S6.adoc[S6]::xref:S0-0cf/S5/S6/S7.adoc[S7]<35, bool>::xref:S0-0cf/S5/S6/S7/S8.adoc[S8];
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6/S7/S8/f8.adoc[`f8`]  ¦

|===




[#R46]

== R46



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    int I,
    typename T>
struct R46
    : xref:S0-0cf.adoc[S0]<36, bool>::xref:S0-0cf/S5.adoc[S5]<37, bool>::xref:S0-0cf/S5/S6.adoc[S6]::xref:S0-0cf/S5/S6/S7.adoc[S7]<38, bool>::xref:S0-0cf/S5/S6/S7/S9.adoc[S9]<I, T>;
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6/S7/S9/f9.adoc[`f9`]  ¦

|===




[#R47]

== R47



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R47
    : xref:S0-0cf.adoc[S0]<39, bool>::xref:S0-0cf/S5.adoc[S5]<40, bool>::xref:S0-0cf/S5/S6.adoc[S6]::xref:S0-0cf/S5/S6/S7.adoc[S7]<41, bool>::xref:S0-0cf/S5/S6/S7/S9.adoc[S9]<42, int>;
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6/S7/S9/f9.adoc[`f9`]  ¦

|===




[#R48]

== R48



=== Synopsis

Declared in `<class-template-specializations-1.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct R48
    : xref:S0-0cf.adoc[S0]<43, bool>::xref:S0-0cf/S5.adoc[S5]<44, bool>::xref:S0-0cf/S5/S6.adoc[S6]::xref:S0-0cf/S5/S6/S7.adoc[S7]<45, bool>::xref:S0-0cf/S5/S6/S7/S9.adoc[S9]<46, bool>;
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:S0-0cf/S5/S6/S7/S9/f9.adoc[`f9`]  ¦

|===




Created with MrDocs
