= Reference
:mrdocs:

[#index]
== Global namespace

=== Types
[cols=2]
|===
| Name | Description 

| <<#R0,`R0`>> 
| 

| <<#R1,`R1`>> 
| 

| <<#R10,`R10`>> 
| 

| <<#R11,`R11`>> 
| 

| <<#R12,`R12`>> 
| 

| <<#R13,`R13`>> 
| 

| <<#R14,`R14`>> 
| 

| <<#R15,`R15`>> 
| 

| <<#R16,`R16`>> 
| 

| <<#R17,`R17`>> 
| 

| <<#R18,`R18`>> 
| 

| <<#R19,`R19`>> 
| 

| <<#R2,`R2`>> 
| 

| <<#R20,`R20`>> 
| 

| <<#R21,`R21`>> 
| 

| <<#R22,`R22`>> 
| 

| <<#R23,`R23`>> 
| 

| <<#R24,`R24`>> 
| 

| <<#R25,`R25`>> 
| 

| <<#R26,`R26`>> 
| 

| <<#R27,`R27`>> 
| 

| <<#R28,`R28`>> 
| 

| <<#R29,`R29`>> 
| 

| <<#R3,`R3`>> 
| 

| <<#R30,`R30`>> 
| 

| <<#R31,`R31`>> 
| 

| <<#R32,`R32`>> 
| 

| <<#R33,`R33`>> 
| 

| <<#R34,`R34`>> 
| 

| <<#R35,`R35`>> 
| 

| <<#R36,`R36`>> 
| 

| <<#R37,`R37`>> 
| 

| <<#R38,`R38`>> 
| 

| <<#R39,`R39`>> 
| 

| <<#R4,`R4`>> 
| 

| <<#R40,`R40`>> 
| 

| <<#R41,`R41`>> 
| 

| <<#R42,`R42`>> 
| 

| <<#R43,`R43`>> 
| 

| <<#R44,`R44`>> 
| 

| <<#R45,`R45`>> 
| 

| <<#R46,`R46`>> 
| 

| <<#R47,`R47`>> 
| 

| <<#R48,`R48`>> 
| 

| <<#R5,`R5`>> 
| 

| <<#R6,`R6`>> 
| 

| <<#R7,`R7`>> 
| 

| <<#R8,`R8`>> 
| 

| <<#R9,`R9`>> 
| 

| <<#S0-02,`S0&lt;1, int*&gt;`>> 
| 

| <<#S0-0c4,`S0&lt;1, T*&gt;`>> 
| 

| <<#S0-0be,`S0&lt;0&gt;`>> 
| 

| <<#S0-0cf,`S0`>> 
| 

|===

[#S0-0cf]
== S0

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    int I,
    typename T = void&gt;
struct S0;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1,`S1`>> 
| 

| <<#S0-0cf-S5,`S5`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-f0,`f0`>> 
| 

|===



[#S0-0cf-f0]
== <<#S0-0cf,S0>>::f0

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f0();
----

[#S0-0cf-S1]
== <<#S0-0cf,S0>>::S1

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct S1;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2,`S2`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-f1,`f1`>> 
| 

|===



[#S0-0cf-S1-f1]
== <<#S0-0cf,S0>>::<<#S0-0cf-S1,S1>>::f1

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f1();
----

[#S0-0cf-S1-S2]
== <<#S0-0cf,S0>>::<<#S0-0cf-S1,S1>>::S2

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    int J,
    typename U = void&gt;
struct S2;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S3,`S3`>> 
| 

| <<#S0-0cf-S1-S2-S4,`S4`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-f2,`f2`>> 
| 

|===



[#S0-0cf-S1-S2-f2]
== <<#S0-0cf,S0>>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>::f2

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f2();
----

[#S0-0cf-S1-S2-S3]
== <<#S0-0cf,S0>>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>::S3

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct S3;
----

=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S3-f3,`f3`>> 
| 

|===



[#S0-0cf-S1-S2-S3-f3]
== <<#S0-0cf,S0>>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>::<<#S0-0cf-S1-S2-S3,S3>>::f3

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f3();
----

[#S0-0cf-S1-S2-S4]
== <<#S0-0cf,S0>>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>::S4

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    int K,
    typename V = void&gt;
struct S4;
----

=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S4-f4,`f4`>> 
| 

|===



[#S0-0cf-S1-S2-S4-f4]
== <<#S0-0cf,S0>>::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>::<<#S0-0cf-S1-S2-S4,S4>>::f4

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f4();
----

[#S0-0cf-S5]
== <<#S0-0cf,S0>>::S5

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    int J,
    typename U = void&gt;
struct S5;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6,`S6`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-f5,`f5`>> 
| 

|===



[#S0-0cf-S5-f5]
== <<#S0-0cf,S0>>::<<#S0-0cf-S5,S5>>::f5

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f5();
----

[#S0-0cf-S5-S6]
== <<#S0-0cf,S0>>::<<#S0-0cf-S5,S5>>::S6

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct S6;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7,`S7`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-f6,`f6`>> 
| 

|===



[#S0-0cf-S5-S6-f6]
== <<#S0-0cf,S0>>::<<#S0-0cf-S5,S5>>::<<#S0-0cf-S5-S6,S6>>::f6

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f6();
----

[#S0-0cf-S5-S6-S7]
== <<#S0-0cf,S0>>::<<#S0-0cf-S5,S5>>::<<#S0-0cf-S5-S6,S6>>::S7

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    int K,
    typename V = void&gt;
struct S7;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S8,`S8`>> 
| 

| <<#S0-0cf-S5-S6-S7-S9,`S9`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-f7,`f7`>> 
| 

|===



[#S0-0cf-S5-S6-S7-f7]
== <<#S0-0cf,S0>>::<<#S0-0cf-S5,S5>>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>::f7

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f7();
----

[#S0-0cf-S5-S6-S7-S8]
== <<#S0-0cf,S0>>::<<#S0-0cf-S5,S5>>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>::S8

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct S8;
----

=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S8-f8,`f8`>> 
| 

|===



[#S0-0cf-S5-S6-S7-S8-f8]
== <<#S0-0cf,S0>>::<<#S0-0cf-S5,S5>>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>::<<#S0-0cf-S5-S6-S7-S8,S8>>::f8

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f8();
----

[#S0-0cf-S5-S6-S7-S9]
== <<#S0-0cf,S0>>::<<#S0-0cf-S5,S5>>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>::S9

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    int L,
    typename W = void&gt;
struct S9;
----

=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S9-f9,`f9`>> 
| 

|===



[#S0-0cf-S5-S6-S7-S9-f9]
== <<#S0-0cf,S0>>::<<#S0-0cf-S5,S5>>::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>::<<#S0-0cf-S5-S6-S7-S9,S9>>::f9

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
void
f9();
----

[#S0-0be]
== S0&lt;0&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#S0-0cf,S0>>&lt;0&gt;;
----




[#S0-0c4]
== S0&lt;1, T*&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
struct <<#S0-0cf,S0>>&lt;1, T*&gt;;
----




[#S0-02]
== S0&lt;1, int*&gt;

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;&gt;
struct <<#S0-0cf,S0>>&lt;1, int*&gt;;
----




[#R0]
== R0

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R0
    : <<#S0-0cf,S0>>&lt;&hyphen;1&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1,`S1`>> 
| 

| <<#S0-0cf-S5,`S5`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-f0,`f0`>> 
| 

|===



[#R1]
== R1

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R1
    : <<#S0-0be,S0>>&lt;0&gt;;
----




[#R2]
== R2

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R2
    : <<#S0-0c4,S0>>&lt;1, void*&gt;;
----




[#R3]
== R3

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R3
    : <<#S0-02,S0>>&lt;1, int*&gt;;
----




[#R4]
== R4

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R4
    : <<#S0-0cf,S0>>&lt;2&gt;::<<#S0-09c-S1,S1>>;
----




[#R5]
== R5

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R5
    : <<#S0-0cf,S0>>&lt;3&gt;::<<#S0-0cf-S1,S1>>::<<#S0-073-S1-S2,S2>>&lt;&hyphen;1&gt;;
----




[#R6]
== R6

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R6
    : <<#S0-0cf,S0>>&lt;4&gt;::<<#S0-0cf-S1,S1>>::<<#S0-0a1-S1-S2,S2>>&lt;5&gt;;
----




[#R7]
== R7

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R7
    : <<#S0-0cf,S0>>&lt;6&gt;::<<#S0-0cf-S1,S1>>::<<#S0-07e-S1-S2-06,S2>>&lt;7, void*&gt;;
----




[#R8]
== R8

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R8
    : <<#S0-0cf,S0>>&lt;6&gt;::<<#S0-0cf-S1,S1>>::<<#S0-07e-S1-S2-07,S2>>&lt;7, int*&gt;;
----




[#R9]
== R9

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R9
    : <<#S0-0cf,S0>>&lt;8&gt;::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>&lt;9&gt;::<<#S0-0a3-S1-S2-S3,S3>>;
----




[#R10]
== R10

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R10
    : <<#S0-0cf,S0>>&lt;10&gt;::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>&lt;11&gt;::<<#S0-08-S1-S2-S4,S4>>&lt;&hyphen;1&gt;;
----




[#R11]
== R11

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R11
    : <<#S0-0cf,S0>>&lt;12&gt;::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>&lt;13&gt;::<<#S0-0e-S1-S2-S4,S4>>&lt;14&gt;;
----




[#R12]
== R12

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R12
    : <<#S0-0cf,S0>>&lt;15&gt;::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>&lt;16&gt;::<<#S0-09e4-S1-S2-S4-07,S4>>&lt;17, void*&gt;;
----




[#R13]
== R13

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R13
    : <<#S0-0cf,S0>>&lt;15&gt;::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>&lt;16&gt;::<<#S0-09e4-S1-S2-S4-02,S4>>&lt;17, int*&gt;;
----




[#R14]
== R14

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R14
    : <<#S0-0cf,S0>>&lt;18&gt;::<<#S0-07a-S5,S5>>&lt;&hyphen;1&gt;;
----




[#R15]
== R15

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R15
    : <<#S0-0cf,S0>>&lt;19&gt;::<<#S0-0a7-S5,S5>>&lt;20&gt;;
----




[#R16]
== R16

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R16
    : <<#S0-0cf,S0>>&lt;21&gt;::<<#S0-031-S5-0b,S5>>&lt;22, void*&gt;;
----




[#R17]
== R17

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R17
    : <<#S0-0cf,S0>>&lt;21&gt;::<<#S0-031-S5-03,S5>>&lt;22, int*&gt;;
----




[#R18]
== R18

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R18
    : <<#S0-0cf,S0>>&lt;23&gt;::<<#S0-0cf-S5,S5>>&lt;24&gt;::<<#S0-05-S5-S6,S6>>;
----




[#R19]
== R19

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R19
    : <<#S0-0cf,S0>>&lt;25&gt;::<<#S0-0cf-S5,S5>>&lt;26&gt;::<<#S0-0cf-S5-S6,S6>>::<<#S0-0a2-S5-S6-S7,S7>>&lt;&hyphen;1&gt;;
----




[#R20]
== R20

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R20
    : <<#S0-0cf,S0>>&lt;27&gt;::<<#S0-0cf-S5,S5>>&lt;28&gt;::<<#S0-0cf-S5-S6,S6>>::<<#S0-09e2-S5-S6-S7-0a,S7>>&lt;29, void*&gt;;
----




[#R21]
== R21

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R21
    : <<#S0-0cf,S0>>&lt;27&gt;::<<#S0-0cf-S5,S5>>&lt;28&gt;::<<#S0-0cf-S5-S6,S6>>::<<#S0-09e2-S5-S6-S7-0d,S7>>&lt;29, int*&gt;;
----




[#R22]
== R22

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R22
    : <<#S0-0cf,S0>>&lt;30&gt;::<<#S0-0cf-S5,S5>>&lt;31&gt;::<<#S0-0cf-S5-S6,S6>>::<<#S0-01-S5-S6-S7,S7>>&lt;32&gt;;
----




[#R23]
== R23

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R23
    : <<#S0-0cf,S0>>&lt;33&gt;::<<#S0-0cf-S5,S5>>&lt;34&gt;::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>&lt;35&gt;::<<#S0-09ee-S5-S6-S7-S8,S8>>;
----




[#R24]
== R24

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R24
    : <<#S0-0cf,S0>>&lt;36&gt;::<<#S0-0cf-S5,S5>>&lt;37&gt;::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>&lt;38&gt;::<<#S0-033-S5-S6-S7-S9,S9>>&lt;&hyphen;1&gt;;
----




[#R25]
== R25

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R25
    : <<#S0-0cf,S0>>&lt;39&gt;::<<#S0-0cf-S5,S5>>&lt;40&gt;::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>&lt;41&gt;::<<#S0-06-S5-S6-S7-S9-00,S9>>&lt;42, void*&gt;;
----




[#R26]
== R26

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R26
    : <<#S0-0cf,S0>>&lt;39&gt;::<<#S0-0cf-S5,S5>>&lt;40&gt;::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>&lt;41&gt;::<<#S0-06-S5-S6-S7-S9-08,S9>>&lt;42, int*&gt;;
----




[#R27]
== R27

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R27
    : <<#S0-0cf,S0>>&lt;43&gt;::<<#S0-0cf-S5,S5>>&lt;44&gt;::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>&lt;45&gt;::<<#S0-0ba-S5-S6-S7-S9,S9>>&lt;46&gt;;
----




[#R28]
== R28

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R28
    : <<#S0-0cf,S0>>&lt;0, bool&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1,`S1`>> 
| 

| <<#S0-0cf-S5,`S5`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-f0,`f0`>> 
| 

|===



[#R29]
== R29

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R29
    : <<#S0-0cf,S0>>&lt;1, int&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1,`S1`>> 
| 

| <<#S0-0cf-S5,`S5`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-f0,`f0`>> 
| 

|===



[#R30]
== R30

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R30
    : <<#S0-0cf,S0>>&lt;2, bool&gt;::<<#S0-0cf-S1,S1>>;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2,`S2`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-f1,`f1`>> 
| 

|===



[#R31]
== R31

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    int I,
    typename T&gt;
struct R31
    : <<#S0-0cf,S0>>&lt;3, bool&gt;::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>&lt;I, T&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S3,`S3`>> 
| 

| <<#S0-0cf-S1-S2-S4,`S4`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-f2,`f2`>> 
| 

|===



[#R32]
== R32

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R32
    : <<#S0-0cf,S0>>&lt;4, bool&gt;::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>&lt;5, bool&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S3,`S3`>> 
| 

| <<#S0-0cf-S1-S2-S4,`S4`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-f2,`f2`>> 
| 

|===



[#R33]
== R33

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R33
    : <<#S0-0cf,S0>>&lt;6, bool&gt;::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>&lt;7, int&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S3,`S3`>> 
| 

| <<#S0-0cf-S1-S2-S4,`S4`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-f2,`f2`>> 
| 

|===



[#R34]
== R34

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R34
    : <<#S0-0cf,S0>>&lt;8, bool&gt;::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>&lt;9, bool&gt;::<<#S0-0cf-S1-S2-S3,S3>>;
----

=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S3-f3,`f3`>> 
| 

|===



[#R35]
== R35

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    int I,
    typename T&gt;
struct R35
    : <<#S0-0cf,S0>>&lt;10, bool&gt;::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>&lt;11, bool&gt;::<<#S0-0cf-S1-S2-S4,S4>>&lt;I, T&gt;;
----

=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S4-f4,`f4`>> 
| 

|===



[#R36]
== R36

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R36
    : <<#S0-0cf,S0>>&lt;12, bool&gt;::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>&lt;13, bool&gt;::<<#S0-0cf-S1-S2-S4,S4>>&lt;14, bool&gt;;
----

=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S4-f4,`f4`>> 
| 

|===



[#R37]
== R37

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R37
    : <<#S0-0cf,S0>>&lt;15, bool&gt;::<<#S0-0cf-S1,S1>>::<<#S0-0cf-S1-S2,S2>>&lt;16, bool&gt;::<<#S0-0cf-S1-S2-S4,S4>>&lt;17, int&gt;;
----

=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S1-S2-S4-f4,`f4`>> 
| 

|===



[#R38]
== R38

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    int I,
    typename T&gt;
struct R38
    : <<#S0-0cf,S0>>&lt;18, bool&gt;::<<#S0-0cf-S5,S5>>&lt;I, T&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6,`S6`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-f5,`f5`>> 
| 

|===



[#R39]
== R39

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R39
    : <<#S0-0cf,S0>>&lt;19, bool&gt;::<<#S0-0cf-S5,S5>>&lt;20, bool&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6,`S6`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-f5,`f5`>> 
| 

|===



[#R40]
== R40

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R40
    : <<#S0-0cf,S0>>&lt;21, bool&gt;::<<#S0-0cf-S5,S5>>&lt;22, int&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6,`S6`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-f5,`f5`>> 
| 

|===



[#R41]
== R41

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R41
    : <<#S0-0cf,S0>>&lt;23, bool&gt;::<<#S0-0cf-S5,S5>>&lt;24, bool&gt;::<<#S0-0cf-S5-S6,S6>>;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7,`S7`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-f6,`f6`>> 
| 

|===



[#R42]
== R42

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    int I,
    typename T&gt;
struct R42
    : <<#S0-0cf,S0>>&lt;25, bool&gt;::<<#S0-0cf-S5,S5>>&lt;26, bool&gt;::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>&lt;I, T&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S8,`S8`>> 
| 

| <<#S0-0cf-S5-S6-S7-S9,`S9`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-f7,`f7`>> 
| 

|===



[#R43]
== R43

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R43
    : <<#S0-0cf,S0>>&lt;27, bool&gt;::<<#S0-0cf-S5,S5>>&lt;28, bool&gt;::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>&lt;29, int&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S8,`S8`>> 
| 

| <<#S0-0cf-S5-S6-S7-S9,`S9`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-f7,`f7`>> 
| 

|===



[#R44]
== R44

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R44
    : <<#S0-0cf,S0>>&lt;30, bool&gt;::<<#S0-0cf-S5,S5>>&lt;31, bool&gt;::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>&lt;32, bool&gt;;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S8,`S8`>> 
| 

| <<#S0-0cf-S5-S6-S7-S9,`S9`>> 
| 

|===
=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-f7,`f7`>> 
| 

|===



[#R45]
== R45

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R45
    : <<#S0-0cf,S0>>&lt;33, bool&gt;::<<#S0-0cf-S5,S5>>&lt;34, bool&gt;::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>&lt;35, bool&gt;::<<#S0-0cf-S5-S6-S7-S8,S8>>;
----

=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S8-f8,`f8`>> 
| 

|===



[#R46]
== R46

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;
    int I,
    typename T&gt;
struct R46
    : <<#S0-0cf,S0>>&lt;36, bool&gt;::<<#S0-0cf-S5,S5>>&lt;37, bool&gt;::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>&lt;38, bool&gt;::<<#S0-0cf-S5-S6-S7-S9,S9>>&lt;I, T&gt;;
----

=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S9-f9,`f9`>> 
| 

|===



[#R47]
== R47

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R47
    : <<#S0-0cf,S0>>&lt;39, bool&gt;::<<#S0-0cf-S5,S5>>&lt;40, bool&gt;::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>&lt;41, bool&gt;::<<#S0-0cf-S5-S6-S7-S9,S9>>&lt;42, int&gt;;
----

=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S9-f9,`f9`>> 
| 

|===



[#R48]
== R48

=== Synopsis

Declared in `&lt;class&hyphen;template&hyphen;specializations&hyphen;1&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct R48
    : <<#S0-0cf,S0>>&lt;43, bool&gt;::<<#S0-0cf-S5,S5>>&lt;44, bool&gt;::<<#S0-0cf-S5-S6,S6>>::<<#S0-0cf-S5-S6-S7,S7>>&lt;45, bool&gt;::<<#S0-0cf-S5-S6-S7-S9,S9>>&lt;46, bool&gt;;
----

=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#S0-0cf-S5-S6-S7-S9-f9,`f9`>> 
| 

|===





[.small]#Created with https://www.mrdocs.com[MrDocs]#
