= Reference
:mrdocs:


[#index]
== Global namespace

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:#A-0e[`A`]  ¦

¦xref:#E[`E`]  ¦

|===



[#A-0e]
== A



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<typename T>
struct A;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:#A-0e-B-07[`B`]  ¦

¦xref:#A-0e-B-00[`B<double>`]  ¦

|===





[#A-0e-B-07]
== xref:#A-0e[pass:[A]]::B



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<typename U>
struct B;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:#A-0e-B-07-C[`C`]  ¦

¦xref:#A-0e-B-07-D-09[`D`]  ¦

¦xref:#A-0e-B-07-D-0f[`D<bool>`]  ¦

|===





[#A-0e-B-07-C]
== xref:#A-0e[pass:[A]]::xref:#A-0e-B-07[pass:[B]]::C



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct C;
----






[#A-0e-B-07-D-09]
== xref:#A-0e[pass:[A]]::xref:#A-0e-B-07[pass:[B]]::D



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<typename V>
struct D;
----






[#A-0e-B-07-D-0f]
== xref:#A-0e[pass:[A]]::xref:#A-0e-B-07[pass:[B]]::D



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<>
struct xref:#A-0e-B-07-D-09[pass:[D]]<bool>;
----






[#A-0e-B-00]
== xref:#A-0e[pass:[A]]::B



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<>
struct xref:#A-0e-B-07[pass:[B]]<double>;
----

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:#A-0e-B-00-C[`C`]  ¦

¦xref:#A-0e-B-00-D-09[`D`]  ¦

¦xref:#A-0e-B-00-D-0d[`D<bool>`]  ¦

|===





[#A-0e-B-00-C]
== xref:#A-0e[pass:[A]]::xref:#A-0e-B-00[pass:[B]]<double>::C



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct C;
----






[#A-0e-B-00-D-09]
== xref:#A-0e[pass:[A]]::xref:#A-0e-B-00[pass:[B]]<double>::D



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<typename V>
struct D;
----






[#A-0e-B-00-D-0d]
== xref:#A-0e[pass:[A]]::xref:#A-0e-B-00[pass:[B]]<double>::D



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<>
struct xref:#A-0e-B-00-D-09[pass:[D]]<bool>;
----






[#A-0c]


[#A-00]


[#E]
== E



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct E;
----

===  Data Members
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:#E-m0[`m0`]  ¦

¦xref:#E-m1[`m1`]  ¦

¦xref:#E-m10[`m10`]  ¦

¦xref:#E-m11[`m11`]  ¦

¦xref:#E-m12[`m12`]  ¦

¦xref:#E-m13[`m13`]  ¦

¦xref:#E-m14[`m14`]  ¦

¦xref:#E-m2[`m2`]  ¦

¦xref:#E-m3[`m3`]  ¦

¦xref:#E-m4[`m4`]  ¦

¦xref:#E-m5[`m5`]  ¦

¦xref:#E-m6[`m6`]  ¦

¦xref:#E-m7[`m7`]  ¦

¦xref:#E-m8[`m8`]  ¦

¦xref:#E-m9[`m9`]  ¦

|===





[#E-m0]
== xref:#E[pass:[E]]::m0



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
xref:#A-0e[A]<float>::xref:#A-0e-B-00[B]<double> m0;
----




[#E-m1]
== xref:#E[pass:[E]]::m1



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
xref:#A-0e[A]<long>::xref:#A-0e-B-00[B]<double> m1;
----




[#E-m2]
== xref:#E[pass:[E]]::m2



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
xref:#A-0e[A]<long>::xref:#A-0c-B[B]<float> m2;
----




[#E-m3]
== xref:#E[pass:[E]]::m3



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
xref:#A-0e[A]<unsigned int>::xref:#A-0e-B-07[B]<float> m3;
----




[#E-m4]
== xref:#E[pass:[E]]::m4



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
xref:#A-0e[A]<short>::xref:#A-00-B[B]<void> m4;
----




[#E-m5]
== xref:#E[pass:[E]]::m5



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
xref:#A-0e[A]<float>::xref:#A-0e-B-00[B]<double>::xref:#A-0e-B-00-C[C] m5;
----




[#E-m6]
== xref:#E[pass:[E]]::m6



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
xref:#A-0e[A]<long>::xref:#A-0e-B-00[B]<double>::xref:#A-0e-B-00-C[C] m6;
----




[#E-m7]
== xref:#E[pass:[E]]::m7



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
xref:#A-0e[A]<long>::xref:#A-0c-B[B]<float>::xref:#A-0c-B-C[C] m7;
----




[#E-m8]
== xref:#E[pass:[E]]::m8



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
xref:#A-0e[A]<unsigned int>::xref:#A-0e-B-07[B]<float>::xref:#A-0e-B-07-C[C] m8;
----




[#E-m9]
== xref:#E[pass:[E]]::m9



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
xref:#A-0e[A]<short>::xref:#A-00-B[B]<void>::xref:#A-00-B-C[C] m9;
----




[#E-m10]
== xref:#E[pass:[E]]::m10



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
xref:#A-0e[A]<float>::xref:#A-0e-B-00[B]<double>::xref:#A-0e-B-00-D-0d[D]<bool> m10;
----




[#E-m11]
== xref:#E[pass:[E]]::m11



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
xref:#A-0e[A]<long>::xref:#A-0e-B-00[B]<double>::xref:#A-0e-B-00-D-0d[D]<bool> m11;
----




[#E-m12]
== xref:#E[pass:[E]]::m12



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
xref:#A-0e[A]<long>::xref:#A-0c-B[B]<float>::xref:#A-0c-B-D-0b[D]<bool> m12;
----




[#E-m13]
== xref:#E[pass:[E]]::m13



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
xref:#A-0e[A]<unsigned int>::xref:#A-0e-B-07[B]<float>::xref:#A-0e-B-07-D-0f[D]<bool> m13;
----




[#E-m14]
== xref:#E[pass:[E]]::m14



=== Synopsis

Declared in `<class-template-specializations-3.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
xref:#A-0e[A]<short>::xref:#A-00-B[B]<void>::xref:#A-00-B-D-07[D]<bool> m14;
----




[.small]#Created with https://www.mrdocs.com[MrDocs]#
