= Reference
:mrdocs:


[#index]
== Global namespace

===  Types
[cols=2]
|===
| Name | Description 

| xref:#Explicit[`Explicit`] 
| 
    
| xref:#ExplicitExpression[`ExplicitExpression`] 
| 
    
| xref:#ExplicitFalse[`ExplicitFalse`] 
| 
    
| xref:#ExplicitTrue[`ExplicitTrue`] 
| 
    
|===



[#Explicit]
== Explicit



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct Explicit;
----

===  Member Functions
[cols=2]
|===
| Name | Description 

| xref:Explicit-2constructor[`Explicit`]         [.small]#[constructor]#
| 
|===




[#pass:[Explicit-2constructor]]

== xref:#Explicit[Explicit]::Explicit

  

=== Synopsis
  

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
xref:#Explicit-2constructor-02[Explicit]();
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
xref:#Explicit-2constructor-00[Explicit](xref:#Explicit[Explicit] const&);
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
xref:#Explicit-2constructor-0b[Explicit](xref:#Explicit[Explicit]&&) noexcept;
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
xref:#Explicit-2constructor-03[Explicit](
    int,
    int);
----
  









[#Explicit-2constructor-02]
== xref:#Explicit[Explicit]::Explicit



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
Explicit();
----










[#Explicit-2constructor-00]
== xref:#Explicit[Explicit]::Explicit



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
Explicit(xref:#Explicit[Explicit] const&);
----










[#Explicit-2constructor-0b]
== xref:#Explicit[Explicit]::Explicit



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
Explicit(xref:#Explicit[Explicit]&&) noexcept;
----










[#Explicit-2constructor-03]
== xref:#Explicit[Explicit]::Explicit



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
Explicit(
    int,
    int);
----










[#ExplicitTrue]
== ExplicitTrue



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct ExplicitTrue;
----

===  Member Functions
[cols=2]
|===
| Name | Description 

| xref:ExplicitTrue-2constructor[`ExplicitTrue`]         [.small]#[constructor]#
| 
|===




[#pass:[ExplicitTrue-2constructor]]

== xref:#ExplicitTrue[ExplicitTrue]::ExplicitTrue

  

=== Synopsis
  

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(true)]
xref:#ExplicitTrue-2constructor-0d[ExplicitTrue]();
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(true)]
xref:#ExplicitTrue-2constructor-04[ExplicitTrue](xref:#ExplicitTrue[ExplicitTrue] const&);
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(true)]
xref:#ExplicitTrue-2constructor-08[ExplicitTrue](xref:#ExplicitTrue[ExplicitTrue]&&) noexcept;
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(true)]
xref:#ExplicitTrue-2constructor-05[ExplicitTrue](
    int,
    int);
----
  









[#ExplicitTrue-2constructor-0d]
== xref:#ExplicitTrue[ExplicitTrue]::ExplicitTrue



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(true)]
ExplicitTrue();
----










[#ExplicitTrue-2constructor-04]
== xref:#ExplicitTrue[ExplicitTrue]::ExplicitTrue



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(true)]
ExplicitTrue(xref:#ExplicitTrue[ExplicitTrue] const&);
----










[#ExplicitTrue-2constructor-08]
== xref:#ExplicitTrue[ExplicitTrue]::ExplicitTrue



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(true)]
ExplicitTrue(xref:#ExplicitTrue[ExplicitTrue]&&) noexcept;
----










[#ExplicitTrue-2constructor-05]
== xref:#ExplicitTrue[ExplicitTrue]::ExplicitTrue



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(true)]
ExplicitTrue(
    int,
    int);
----










[#ExplicitFalse]
== ExplicitFalse



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct ExplicitFalse;
----

===  Member Functions
[cols=2]
|===
| Name | Description 

| xref:ExplicitFalse-2constructor[`ExplicitFalse`]         [.small]#[constructor]#
| 
|===




[#pass:[ExplicitFalse-2constructor]]

== xref:#ExplicitFalse[ExplicitFalse]::ExplicitFalse

  

=== Synopsis
  

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(false)]
xref:#ExplicitFalse-2constructor-01[ExplicitFalse]();
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(false)]
xref:#ExplicitFalse-2constructor-08[ExplicitFalse](xref:#ExplicitFalse[ExplicitFalse] const&);
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(false)]
xref:#ExplicitFalse-2constructor-0a[ExplicitFalse](xref:#ExplicitFalse[ExplicitFalse]&&) noexcept;
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(false)]
xref:#ExplicitFalse-2constructor-04[ExplicitFalse](
    int,
    int);
----
  









[#ExplicitFalse-2constructor-01]
== xref:#ExplicitFalse[ExplicitFalse]::ExplicitFalse



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(false)]
ExplicitFalse();
----










[#ExplicitFalse-2constructor-08]
== xref:#ExplicitFalse[ExplicitFalse]::ExplicitFalse



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(false)]
ExplicitFalse(xref:#ExplicitFalse[ExplicitFalse] const&);
----










[#ExplicitFalse-2constructor-0a]
== xref:#ExplicitFalse[ExplicitFalse]::ExplicitFalse



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(false)]
ExplicitFalse(xref:#ExplicitFalse[ExplicitFalse]&&) noexcept;
----










[#ExplicitFalse-2constructor-04]
== xref:#ExplicitFalse[ExplicitFalse]::ExplicitFalse



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(false)]
ExplicitFalse(
    int,
    int);
----










[#ExplicitExpression]
== ExplicitExpression



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<bool B>
struct ExplicitExpression;
----

===  Member Functions
[cols=2]
|===
| Name | Description 

| xref:ExplicitExpression-2constructor[`ExplicitExpression`]         [.small]#[constructor]#
| 
|===




[#pass:[ExplicitExpression-2constructor]]

== xref:#ExplicitExpression[ExplicitExpression]::ExplicitExpression

  

=== Synopsis
  

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(B)]
xref:#ExplicitExpression-2constructor-0b[ExplicitExpression]();
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(B)]
xref:#ExplicitExpression-2constructor-04[ExplicitExpression](xref:#ExplicitExpression[ExplicitExpression] const&);
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(B)]
xref:#ExplicitExpression-2constructor-08[ExplicitExpression](xref:#ExplicitExpression[ExplicitExpression]&&) noexcept;
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(B)]
xref:#ExplicitExpression-2constructor-02[ExplicitExpression](
    int,
    int);
----
  









[#ExplicitExpression-2constructor-0b]
== xref:#ExplicitExpression[ExplicitExpression]::ExplicitExpression



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(B)]
ExplicitExpression();
----










[#ExplicitExpression-2constructor-04]
== xref:#ExplicitExpression[ExplicitExpression]::ExplicitExpression



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(B)]
ExplicitExpression(xref:#ExplicitExpression[ExplicitExpression] const&);
----










[#ExplicitExpression-2constructor-08]
== xref:#ExplicitExpression[ExplicitExpression]::ExplicitExpression



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(B)]
ExplicitExpression(xref:#ExplicitExpression[ExplicitExpression]&&) noexcept;
----










[#ExplicitExpression-2constructor-02]
== xref:#ExplicitExpression[ExplicitExpression]::ExplicitExpression



=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(B)]
ExplicitExpression(
    int,
    int);
----










[.small]#Created with https://www.mrdocs.com[MrDocs]#
