= Reference
:mrdocs:

[#index]

== Global namespace

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:Explicit.adoc[`Explicit`]  ¦

¦xref:ExplicitExpression.adoc[`ExplicitExpression`]  ¦

¦xref:ExplicitFalse.adoc[`ExplicitFalse`]  ¦

¦xref:ExplicitTrue.adoc[`ExplicitTrue`]  ¦

|===


[#Explicit]

== Explicit



=== Synopsis

Declared in header `<explicit-conv-operator.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct Explicit;
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:Explicit/2conversion.adoc[`operator bool`]  ¦

|===



:relfileprefix: ../
[#Explicit-2conversion]

== xref:Explicit.adoc[pass:[Explicit]]::operator bool



=== Synopsis

Declared in header `<explicit-conv-operator.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
operator bool();
----









[#ExplicitFalse]

== ExplicitFalse



=== Synopsis

Declared in header `<explicit-conv-operator.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct ExplicitFalse;
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:ExplicitFalse/2conversion.adoc[`operator bool`]  ¦

|===



:relfileprefix: ../
[#ExplicitFalse-2conversion]

== xref:ExplicitFalse.adoc[pass:[ExplicitFalse]]::operator bool



=== Synopsis

Declared in header `<explicit-conv-operator.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(false)
operator bool();
----









[#ExplicitTrue]

== ExplicitTrue



=== Synopsis

Declared in header `<explicit-conv-operator.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct ExplicitTrue;
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:ExplicitTrue/2conversion.adoc[`operator bool`]  ¦

|===



:relfileprefix: ../
[#ExplicitTrue-2conversion]

== xref:ExplicitTrue.adoc[pass:[ExplicitTrue]]::operator bool



=== Synopsis

Declared in header `<explicit-conv-operator.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(true)
operator bool();
----









[#ExplicitExpression]

== ExplicitExpression



=== Synopsis

Declared in header `<explicit-conv-operator.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<bool B>
struct ExplicitExpression;
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:ExplicitExpression/2conversion.adoc[`operator bool`]  ¦

|===



:relfileprefix: ../
[#ExplicitExpression-2conversion]

== xref:ExplicitExpression.adoc[pass:[ExplicitExpression]]::operator bool



=== Synopsis

Declared in header `<explicit-conv-operator.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(B)
operator bool();
----









Created with MrDocs
