= Reference
:mrdocs:


[#index]
== Global namespace

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:#Explicit[`Explicit`]  ¦

¦xref:#ExplicitExpression[`ExplicitExpression`]  ¦

¦xref:#ExplicitFalse[`ExplicitFalse`]  ¦

¦xref:#ExplicitTrue[`ExplicitTrue`]  ¦

|===



[#Explicit]
== Explicit



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct Explicit;
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:Explicit-2constructor[`Explicit`] [.small]#[constructor]# ¦
|===




[#Explicit-2constructor]

== xref:#Explicit[pass:[Explicit]]::Explicit

  

=== Synopsis
  

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
xref:#Explicit-2constructor-02[pass:[Explicit]]();
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
xref:#Explicit-2constructor-00[pass:[Explicit]](xref:#Explicit[Explicit] const&);
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
xref:#Explicit-2constructor-0b[pass:[Explicit]](xref:#Explicit[Explicit]&&) noexcept;
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
xref:#Explicit-2constructor-03[pass:[Explicit]](
    int,
    int);
----
  









[#Explicit-2constructor-02]
== xref:#Explicit[pass:[Explicit]]::Explicit



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
Explicit();
----










[#Explicit-2constructor-00]
== xref:#Explicit[pass:[Explicit]]::Explicit



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
Explicit(xref:#Explicit[Explicit] const&);
----










[#Explicit-2constructor-0b]
== xref:#Explicit[pass:[Explicit]]::Explicit



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
Explicit(xref:#Explicit[Explicit]&&) noexcept;
----










[#Explicit-2constructor-03]
== xref:#Explicit[pass:[Explicit]]::Explicit



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
Explicit(
    int,
    int);
----










[#ExplicitTrue]
== ExplicitTrue



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct ExplicitTrue;
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:ExplicitTrue-2constructor[`ExplicitTrue`] [.small]#[constructor]# ¦
|===




[#ExplicitTrue-2constructor]

== xref:#ExplicitTrue[pass:[ExplicitTrue]]::ExplicitTrue

  

=== Synopsis
  

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(true)
xref:#ExplicitTrue-2constructor-0d[pass:[ExplicitTrue]]();
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(true)
xref:#ExplicitTrue-2constructor-04[pass:[ExplicitTrue]](xref:#ExplicitTrue[ExplicitTrue] const&);
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(true)
xref:#ExplicitTrue-2constructor-08[pass:[ExplicitTrue]](xref:#ExplicitTrue[ExplicitTrue]&&) noexcept;
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(true)
xref:#ExplicitTrue-2constructor-05[pass:[ExplicitTrue]](
    int,
    int);
----
  









[#ExplicitTrue-2constructor-0d]
== xref:#ExplicitTrue[pass:[ExplicitTrue]]::ExplicitTrue



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(true)
ExplicitTrue();
----










[#ExplicitTrue-2constructor-04]
== xref:#ExplicitTrue[pass:[ExplicitTrue]]::ExplicitTrue



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(true)
ExplicitTrue(xref:#ExplicitTrue[ExplicitTrue] const&);
----










[#ExplicitTrue-2constructor-08]
== xref:#ExplicitTrue[pass:[ExplicitTrue]]::ExplicitTrue



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(true)
ExplicitTrue(xref:#ExplicitTrue[ExplicitTrue]&&) noexcept;
----










[#ExplicitTrue-2constructor-05]
== xref:#ExplicitTrue[pass:[ExplicitTrue]]::ExplicitTrue



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(true)
ExplicitTrue(
    int,
    int);
----










[#ExplicitFalse]
== ExplicitFalse



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct ExplicitFalse;
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:ExplicitFalse-2constructor[`ExplicitFalse`] [.small]#[constructor]# ¦
|===




[#ExplicitFalse-2constructor]

== xref:#ExplicitFalse[pass:[ExplicitFalse]]::ExplicitFalse

  

=== Synopsis
  

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(false)
xref:#ExplicitFalse-2constructor-01[pass:[ExplicitFalse]]();
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(false)
xref:#ExplicitFalse-2constructor-08[pass:[ExplicitFalse]](xref:#ExplicitFalse[ExplicitFalse] const&);
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(false)
xref:#ExplicitFalse-2constructor-0a[pass:[ExplicitFalse]](xref:#ExplicitFalse[ExplicitFalse]&&) noexcept;
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(false)
xref:#ExplicitFalse-2constructor-04[pass:[ExplicitFalse]](
    int,
    int);
----
  









[#ExplicitFalse-2constructor-01]
== xref:#ExplicitFalse[pass:[ExplicitFalse]]::ExplicitFalse



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(false)
ExplicitFalse();
----










[#ExplicitFalse-2constructor-08]
== xref:#ExplicitFalse[pass:[ExplicitFalse]]::ExplicitFalse



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(false)
ExplicitFalse(xref:#ExplicitFalse[ExplicitFalse] const&);
----










[#ExplicitFalse-2constructor-0a]
== xref:#ExplicitFalse[pass:[ExplicitFalse]]::ExplicitFalse



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(false)
ExplicitFalse(xref:#ExplicitFalse[ExplicitFalse]&&) noexcept;
----










[#ExplicitFalse-2constructor-04]
== xref:#ExplicitFalse[pass:[ExplicitFalse]]::ExplicitFalse



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(false)
ExplicitFalse(
    int,
    int);
----










[#ExplicitExpression]
== ExplicitExpression



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<bool B>
struct ExplicitExpression;
----

===  Member Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:ExplicitExpression-2constructor[`ExplicitExpression`] [.small]#[constructor]# ¦
|===




[#ExplicitExpression-2constructor]

== xref:#ExplicitExpression[pass:[ExplicitExpression]]::ExplicitExpression

  

=== Synopsis
  

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(B)
xref:#ExplicitExpression-2constructor-0b[pass:[ExplicitExpression]]();
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(B)
xref:#ExplicitExpression-2constructor-04[pass:[ExplicitExpression]](xref:#ExplicitExpression[ExplicitExpression] const&);
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(B)
xref:#ExplicitExpression-2constructor-08[pass:[ExplicitExpression]](xref:#ExplicitExpression[ExplicitExpression]&&) noexcept;
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(B)
xref:#ExplicitExpression-2constructor-02[pass:[ExplicitExpression]](
    int,
    int);
----
  









[#ExplicitExpression-2constructor-0b]
== xref:#ExplicitExpression[pass:[ExplicitExpression]]::ExplicitExpression



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(B)
ExplicitExpression();
----










[#ExplicitExpression-2constructor-04]
== xref:#ExplicitExpression[pass:[ExplicitExpression]]::ExplicitExpression



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(B)
ExplicitExpression(xref:#ExplicitExpression[ExplicitExpression] const&);
----










[#ExplicitExpression-2constructor-08]
== xref:#ExplicitExpression[pass:[ExplicitExpression]]::ExplicitExpression



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(B)
ExplicitExpression(xref:#ExplicitExpression[ExplicitExpression]&&) noexcept;
----










[#ExplicitExpression-2constructor-02]
== xref:#ExplicitExpression[pass:[ExplicitExpression]]::ExplicitExpression



=== Synopsis

Declared in `<explicit-ctor.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit(B)
ExplicitExpression(
    int,
    int);
----










[.small]#Created with https://www.mrdocs.com[MrDocs]#
