= Reference
:mrdocs:

[#index]
== Global namespace

=== Types
[cols=2]
|===
| Name | Description 

| <<#Explicit,`Explicit`>> 
| 

| <<#ExplicitExpression,`ExplicitExpression`>> 
| 

| <<#ExplicitFalse,`ExplicitFalse`>> 
| 

| <<#ExplicitTrue,`ExplicitTrue`>> 
| 

|===

[#Explicit]
== Explicit

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
struct Explicit;
----

=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#Explicit-2constructor,`Explicit`>>         [.small]#[constructor]#
| 
|===



[#Explicit-2constructor]
== <<#Explicit,Explicit>>::Explicit

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
<<#Explicit-2constructor-02,Explicit>>();
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
<<#Explicit-2constructor-00,Explicit>>(<<#Explicit,Explicit>> const&);
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
<<#Explicit-2constructor-0b,Explicit>>(<<#Explicit,Explicit>>&&) noexcept;
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
<<#Explicit-2constructor-03,Explicit>>(
    int,
    int);
----

[#Explicit-2constructor-02]
== <<#Explicit,Explicit>>::Explicit

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
Explicit();
----

[#Explicit-2constructor-00]
== <<#Explicit,Explicit>>::Explicit

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
Explicit(<<#Explicit,Explicit>> const&);
----

[#Explicit-2constructor-0b]
== <<#Explicit,Explicit>>::Explicit

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
Explicit(<<#Explicit,Explicit>>&&) noexcept;
----

[#Explicit-2constructor-03]
== <<#Explicit,Explicit>>::Explicit

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
explicit
Explicit(
    int,
    int);
----

[#ExplicitTrue]
== ExplicitTrue

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
struct ExplicitTrue;
----

=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#ExplicitTrue-2constructor,`ExplicitTrue`>>         [.small]#[constructor]#
| 
|===



[#ExplicitTrue-2constructor]
== <<#ExplicitTrue,ExplicitTrue>>::ExplicitTrue

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(true)]
<<#ExplicitTrue-2constructor-0d,ExplicitTrue>>();
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(true)]
<<#ExplicitTrue-2constructor-04,ExplicitTrue>>(<<#ExplicitTrue,ExplicitTrue>> const&);
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(true)]
<<#ExplicitTrue-2constructor-08,ExplicitTrue>>(<<#ExplicitTrue,ExplicitTrue>>&&) noexcept;
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(true)]
<<#ExplicitTrue-2constructor-05,ExplicitTrue>>(
    int,
    int);
----

[#ExplicitTrue-2constructor-0d]
== <<#ExplicitTrue,ExplicitTrue>>::ExplicitTrue

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(true)]
ExplicitTrue();
----

[#ExplicitTrue-2constructor-04]
== <<#ExplicitTrue,ExplicitTrue>>::ExplicitTrue

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(true)]
ExplicitTrue(<<#ExplicitTrue,ExplicitTrue>> const&);
----

[#ExplicitTrue-2constructor-08]
== <<#ExplicitTrue,ExplicitTrue>>::ExplicitTrue

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(true)]
ExplicitTrue(<<#ExplicitTrue,ExplicitTrue>>&&) noexcept;
----

[#ExplicitTrue-2constructor-05]
== <<#ExplicitTrue,ExplicitTrue>>::ExplicitTrue

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(true)]
ExplicitTrue(
    int,
    int);
----

[#ExplicitFalse]
== ExplicitFalse

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
struct ExplicitFalse;
----

=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#ExplicitFalse-2constructor,`ExplicitFalse`>>         [.small]#[constructor]#
| 
|===



[#ExplicitFalse-2constructor]
== <<#ExplicitFalse,ExplicitFalse>>::ExplicitFalse

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(false)]
<<#ExplicitFalse-2constructor-01,ExplicitFalse>>();
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(false)]
<<#ExplicitFalse-2constructor-08,ExplicitFalse>>(<<#ExplicitFalse,ExplicitFalse>> const&);
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(false)]
<<#ExplicitFalse-2constructor-0a,ExplicitFalse>>(<<#ExplicitFalse,ExplicitFalse>>&&) noexcept;
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(false)]
<<#ExplicitFalse-2constructor-04,ExplicitFalse>>(
    int,
    int);
----

[#ExplicitFalse-2constructor-01]
== <<#ExplicitFalse,ExplicitFalse>>::ExplicitFalse

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(false)]
ExplicitFalse();
----

[#ExplicitFalse-2constructor-08]
== <<#ExplicitFalse,ExplicitFalse>>::ExplicitFalse

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(false)]
ExplicitFalse(<<#ExplicitFalse,ExplicitFalse>> const&);
----

[#ExplicitFalse-2constructor-0a]
== <<#ExplicitFalse,ExplicitFalse>>::ExplicitFalse

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(false)]
ExplicitFalse(<<#ExplicitFalse,ExplicitFalse>>&&) noexcept;
----

[#ExplicitFalse-2constructor-04]
== <<#ExplicitFalse,ExplicitFalse>>::ExplicitFalse

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(false)]
ExplicitFalse(
    int,
    int);
----

[#ExplicitExpression]
== ExplicitExpression

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
template<bool B>
struct ExplicitExpression;
----

=== Member Functions
[cols=2]
|===
| Name | Description 

| <<#ExplicitExpression-2constructor,`ExplicitExpression`>>         [.small]#[constructor]#
| 
|===



[#ExplicitExpression-2constructor]
== <<#ExplicitExpression,ExplicitExpression>>::ExplicitExpression

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(B)]
<<#ExplicitExpression-2constructor-0b,ExplicitExpression>>();
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(B)]
<<#ExplicitExpression-2constructor-04,ExplicitExpression>>(<<#ExplicitExpression,ExplicitExpression>> const&);
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(B)]
<<#ExplicitExpression-2constructor-08,ExplicitExpression>>(<<#ExplicitExpression,ExplicitExpression>>&&) noexcept;
----

[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(B)]
<<#ExplicitExpression-2constructor-02,ExplicitExpression>>(
    int,
    int);
----

[#ExplicitExpression-2constructor-0b]
== <<#ExplicitExpression,ExplicitExpression>>::ExplicitExpression

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(B)]
ExplicitExpression();
----

[#ExplicitExpression-2constructor-04]
== <<#ExplicitExpression,ExplicitExpression>>::ExplicitExpression

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(B)]
ExplicitExpression(<<#ExplicitExpression,ExplicitExpression>> const&);
----

[#ExplicitExpression-2constructor-08]
== <<#ExplicitExpression,ExplicitExpression>>::ExplicitExpression

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(B)]
ExplicitExpression(<<#ExplicitExpression,ExplicitExpression>>&&) noexcept;
----

[#ExplicitExpression-2constructor-02]
== <<#ExplicitExpression,ExplicitExpression>>::ExplicitExpression

=== Synopsis

Declared in `<pass:[explicit-ctor.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
pass:[explicit(B)]
ExplicitExpression(
    int,
    int);
----



[.small]#Created with https://www.mrdocs.com[MrDocs]#
