= Reference
:mrdocs:


[#index]
== Global namespace

===  Types
[cols=2]
|===
| Name | Description 

| xref:#A0[`A0`] 
| 
    
| xref:#A1[`A1`] 
| 
    
| xref:#A10[`A10`] 
| 
    
| xref:#A2[`A2`] 
| 
    
| xref:#A3[`A3`] 
| 
    
| xref:#A4[`A4`] 
| 
    
| xref:#A5[`A5`] 
| 
    
| xref:#A6[`A6`] 
| 
    
| xref:#A7[`A7`] 
| 
    
| xref:#A8[`A8`] 
| 
    
| xref:#A9[`A9`] 
| 
    
| xref:#S0[`S0`] 
| 
    
|===



[#S0]
== S0



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<typename T>
struct S0;
----

===  Types
[cols=2]
|===
| Name | Description 

| xref:#S0-M0[`M0`] 
| 
    
| xref:#S0-M1[`M1`] 
| 
    
| xref:#S0-S1[`S1`] 
| 
    
| xref:#S0-S2[`S2`] 
| 
    
|===





[#S0-M0]
== xref:#S0[S0]::M0



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
using M0 = T;
----




[#S0-S1]
== xref:#S0[S0]::S1



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct S1;
----






[#S0-M1]
== xref:#S0[S0]::M1



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<typename U>
using M1 = xref:#S0[S0]<U>;
----




[#S0-S2]
== xref:#S0[S0]::S2



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<typename U>
struct S2;
----

===  Types
[cols=2]
|===
| Name | Description 

| xref:#S0-S2-M2[`M2`] 
| 
    
| xref:#S0-S2-M3[`M3`] 
| 
    
| xref:#S0-S2-S3[`S3`] 
| 
    
| xref:#S0-S2-S4[`S4`] 
| 
    
|===





[#S0-S2-M2]
== xref:#S0[S0]::xref:#S0-S2[S2]::M2



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
using M2 = U;
----




[#S0-S2-S3]
== xref:#S0[S0]::xref:#S0-S2[S2]::S3



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct S3;
----






[#S0-S2-M3]
== xref:#S0[S0]::xref:#S0-S2[S2]::M3



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<typename V>
using M3 = xref:#S0-S2[S2]<U>;
----




[#S0-S2-S4]
== xref:#S0[S0]::xref:#S0-S2[S2]::S4



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<typename V>
struct S4;
----

===  Types
[cols=2]
|===
| Name | Description 

| xref:#S0-S2-S4-M4[`M4`] 
| 
    
|===





[#S0-S2-S4-M4]
== xref:#S0[S0]::xref:#S0-S2[S2]::xref:#S0-S2-S4[S4]::M4



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
using M4 = V;
----




[#A0]
== A0



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
using A0 = xref:#S0[S0]<int>;
----




[#A1]
== A1



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
using A1 = xref:#A0[A0]::xref:#S0-M0[M0];
----




[#A2]
== A2



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
using A2 = xref:#A0[A0]::xref:#S0-S1[S1];
----




[#A3]
== A3



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
using A3 = xref:#S0[S0]<long>::xref:#S0-M0[M0];
----




[#A4]
== A4



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
using A4 = xref:#S0[S0]<long long>::xref:#S0-S1[S1];
----




[#A5]
== A5



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
using A5 = xref:#S0[S0]<void>;
----




[#A6]
== A6



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
using A6 = xref:#A5[A5]::xref:#S0-M1[M1]<short>::xref:#S0-M0[M0];
----




[#A7]
== A7



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
using A7 = xref:#A5[A5]::xref:#S0-S2[S2]<bool>::xref:#S0-S2-M2[M2];
----




[#A8]
== A8



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
using A8 = xref:#A5[A5]::xref:#S0-S2[S2]<int>::xref:#S0-S2-S3[S3];
----




[#A9]
== A9



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
using A9 = xref:#A5[A5]::xref:#S0-S2[S2]<char>::xref:#S0-S2-M3[M3]<int>::xref:#S0-S2-M3[M3]<unsigned int>::xref:#S0-S2-M2[M2];
----




[#A10]
== A10



=== Synopsis

Declared in `<pass:[implicit-instantiation-member-ref.cpp]>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
using A10 = xref:#A5[A5]::xref:#S0-S2[S2]<float>::xref:#S0-S2-M3[M3]<double>::xref:#S0-S2-M3[M3]<long double>::xref:#S0-S2-S4[S4]<void>::xref:#S0-S2-S4-M4[M4];
----




[.small]#Created with https://www.mrdocs.com[MrDocs]#
