= Reference
:mrdocs:

[#index]
== Global namespace

=== Types
[cols=2]
|===
| Name | Description 

| <<#A0,`A0`>> 
| 

| <<#A1,`A1`>> 
| 

| <<#A10,`A10`>> 
| 

| <<#A2,`A2`>> 
| 

| <<#A3,`A3`>> 
| 

| <<#A4,`A4`>> 
| 

| <<#A5,`A5`>> 
| 

| <<#A6,`A6`>> 
| 

| <<#A7,`A7`>> 
| 

| <<#A8,`A8`>> 
| 

| <<#A9,`A9`>> 
| 

| <<#S0,`S0`>> 
| 

|===

[#S0]
== S0

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename T&gt;
struct S0;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-M0,`M0`>> 
| 

| <<#S0-M1,`M1`>> 
| 

| <<#S0-S1,`S1`>> 
| 

| <<#S0-S2,`S2`>> 
| 

|===



[#S0-M0]
== <<#S0,S0>>::M0

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using M0 = T;
----

[#S0-S1]
== <<#S0,S0>>::S1

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct S1;
----




[#S0-M1]
== <<#S0,S0>>::M1

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
using M1 = <<#S0,S0>>&lt;U&gt;;
----

[#S0-S2]
== <<#S0,S0>>::S2

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename U&gt;
struct S2;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-S2-M2,`M2`>> 
| 

| <<#S0-S2-M3,`M3`>> 
| 

| <<#S0-S2-S3,`S3`>> 
| 

| <<#S0-S2-S4,`S4`>> 
| 

|===



[#S0-S2-M2]
== <<#S0,S0>>::<<#S0-S2,S2>>::M2

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using M2 = U;
----

[#S0-S2-S3]
== <<#S0,S0>>::<<#S0-S2,S2>>::S3

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
struct S3;
----




[#S0-S2-M3]
== <<#S0,S0>>::<<#S0-S2,S2>>::M3

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
using M3 = <<#S0-S2,S2>>&lt;U&gt;;
----

[#S0-S2-S4]
== <<#S0,S0>>::<<#S0-S2,S2>>::S4

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
template&lt;typename V&gt;
struct S4;
----

=== Types
[cols=2]
|===
| Name | Description 

| <<#S0-S2-S4-M4,`M4`>> 
| 

|===



[#S0-S2-S4-M4]
== <<#S0,S0>>::<<#S0-S2,S2>>::<<#S0-S2-S4,S4>>::M4

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using M4 = V;
----

[#A0]
== A0

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using A0 = <<#S0,S0>>&lt;int&gt;;
----

[#A1]
== A1

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using A1 = <<#A0,A0>>::<<#S0-M0,M0>>;
----

[#A2]
== A2

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using A2 = <<#A0,A0>>::<<#S0-S1,S1>>;
----

[#A3]
== A3

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using A3 = <<#S0,S0>>&lt;long&gt;::<<#S0-M0,M0>>;
----

[#A4]
== A4

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using A4 = <<#S0,S0>>&lt;long long&gt;::<<#S0-S1,S1>>;
----

[#A5]
== A5

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using A5 = <<#S0,S0>>&lt;void&gt;;
----

[#A6]
== A6

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using A6 = <<#A5,A5>>::<<#S0-M1,M1>>&lt;short&gt;::<<#S0-M0,M0>>;
----

[#A7]
== A7

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using A7 = <<#A5,A5>>::<<#S0-S2,S2>>&lt;bool&gt;::<<#S0-S2-M2,M2>>;
----

[#A8]
== A8

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using A8 = <<#A5,A5>>::<<#S0-S2,S2>>&lt;int&gt;::<<#S0-S2-S3,S3>>;
----

[#A9]
== A9

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using A9 = <<#A5,A5>>::<<#S0-S2,S2>>&lt;char&gt;::<<#S0-S2-M3,M3>>&lt;int&gt;::<<#S0-S2-M3,M3>>&lt;unsigned int&gt;::<<#S0-S2-M2,M2>>;
----

[#A10]
== A10

=== Synopsis

Declared in `&lt;implicit&hyphen;instantiation&hyphen;member&hyphen;ref&period;cpp&gt;`

[source,cpp,subs="verbatim,replacements,macros,-callouts"]
----
using A10 = <<#A5,A5>>::<<#S0-S2,S2>>&lt;float&gt;::<<#S0-S2-M3,M3>>&lt;double&gt;::<<#S0-S2-M3,M3>>&lt;long double&gt;::<<#S0-S2-S4,S4>>&lt;void&gt;::<<#S0-S2-S4-M4,M4>>;
----



[.small]#Created with https://www.mrdocs.com[MrDocs]#
