= Reference
:mrdocs:

[#index]

== Global namespace

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:C0.adoc[`C0`]  ¦

¦xref:C1.adoc[`C1`]  ¦

¦xref:C2.adoc[`C2`]  ¦

¦xref:C3.adoc[`C3`]  ¦

¦xref:C4.adoc[`C4`]  ¦

¦xref:C5.adoc[`C5`]  ¦

¦xref:C6.adoc[`C6`]  ¦

¦xref:C7.adoc[`C7`]  ¦

¦xref:S0.adoc[`S0`]  ¦

¦xref:S1.adoc[`S1`]  ¦

¦xref:S2.adoc[`S2`]  ¦

¦xref:S3.adoc[`S3`]  ¦

¦xref:S4.adoc[`S4`]  ¦

¦xref:S5.adoc[`S5`]  ¦

¦xref:S6.adoc[`S6`]  ¦

¦xref:U0.adoc[`U0`]  ¦

|===


[#S0]

== S0



=== Synopsis

Declared in header `<record-inheritance.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct S0;
----





[#C0]

== C0



=== Synopsis

Declared in header `<record-inheritance.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
class C0;
----





[#U0]

== U0



=== Synopsis

Declared in header `<record-inheritance.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
union U0;
----





[#S1]

== S1



=== Synopsis

Declared in header `<record-inheritance.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct S1;
----





[#S2]

== S2



=== Synopsis

Declared in header `<record-inheritance.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct S2
    : xref:S0.adoc[S0];
----





[#S3]

== S3



=== Synopsis

Declared in header `<record-inheritance.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct S3
    : xref:S1.adoc[S1];
----





[#S4]

== S4



=== Synopsis

Declared in header `<record-inheritance.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct S4
    : xref:S2.adoc[S2]
    , xref:S3.adoc[S3];
----





[#C1]

== C1



=== Synopsis

Declared in header `<record-inheritance.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
class C1
    : xref:C0.adoc[C0];
----





[#C2]

== C2



=== Synopsis

Declared in header `<record-inheritance.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
class C2
    : public xref:C0.adoc[C0];
----





[#C3]

== C3



=== Synopsis

Declared in header `<record-inheritance.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
class C3
    : protected xref:C0.adoc[C0];
----





[#C4]

== C4



=== Synopsis

Declared in header `<record-inheritance.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
class C4
    : xref:C0.adoc[C0];
----





[#C5]

== C5



=== Synopsis

Declared in header `<record-inheritance.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
class C5
    : virtual xref:C0.adoc[C0];
----





[#C6]

== C6



=== Synopsis

Declared in header `<record-inheritance.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
class C6
    : virtual xref:C1.adoc[C1];
----





[#C7]

== C7



=== Synopsis

Declared in header `<record-inheritance.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
class C7
    : public xref:C5.adoc[C5]
    , public xref:C6.adoc[C6];
----





[#S5]

== S5



=== Synopsis

Declared in header `<record-inheritance.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct S5
    : private xref:S0.adoc[S0]
    , protected xref:S1.adoc[S1];
----





[#S6]

== S6



=== Synopsis

Declared in header `<record-inheritance.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<typename... Ts>
struct S6
    : Ts...;
----





Created with MrDocs
