= Reference
:mrdocs:


[#index]
== Global namespace

===  Types
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:#A[`A`]  ¦

¦xref:#B[`B`]  ¦

¦xref:#C[`C`]  ¦

¦xref:#D[`D`]  ¦

¦xref:#E[`E`]  ¦

|===
=== Functions
[cols=2,separator=¦]
|===
¦Name ¦Description
¦xref:#f0[`f0`]  ¦

¦xref:#f1[`f1`]  ¦

¦xref:#f2[`f2`]  ¦

¦xref:#f3[`f3`]  ¦

¦xref:#f4[`f4`]  ¦

¦xref:#f5[`f5`]  ¦

¦xref:#f6[`f6`]  ¦

¦xref:#f7[`f7`]  ¦

¦xref:#f8[`f8`]  ¦

¦xref:#g0[`g0`]  ¦

¦xref:#g1[`g1`]  ¦

¦xref:#g2[`g2`]  ¦

¦xref:#g3[`g3`]  ¦

¦xref:#g4[`g4`]  ¦

¦xref:#g5[`g5`]  ¦

¦xref:#g6[`g6`]  ¦

¦xref:#g7[`g7`]  ¦

¦xref:#g8[`g8`]  ¦

¦xref:#h0[`h0`]  ¦

¦xref:#h1[`h1`]  ¦

¦xref:#h2[`h2`]  ¦

¦xref:#h3[`h3`]  ¦

¦xref:#h4[`h4`]  ¦

¦xref:#h5[`h5`]  ¦

¦xref:#h6[`h6`]  ¦

¦xref:#h7[`h7`]  ¦

¦xref:#h8[`h8`]  ¦

¦xref:#i0[`i0`]  ¦

¦xref:#i1[`i1`]  ¦

¦xref:#i2[`i2`]  ¦

¦xref:#i3[`i3`]  ¦

¦xref:#i4[`i4`]  ¦

¦xref:#i5[`i5`]  ¦

¦xref:#i6[`i6`]  ¦

¦xref:#i7[`i7`]  ¦

¦xref:#i8[`i8`]  ¦

¦xref:#j0[`j0`]  ¦

¦xref:#j1[`j1`]  ¦

¦xref:#j2[`j2`]  ¦

¦xref:#j3[`j3`]  ¦

¦xref:#j4[`j4`]  ¦

¦xref:#j5[`j5`]  ¦

¦xref:#j6[`j6`]  ¦

¦xref:#j7[`j7`]  ¦

¦xref:#j8[`j8`]  ¦

|===



[#A]
== A



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
struct A;
----






[#B]
== B



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<
    typename T,
    typename U>
struct B;
----






[#C]
== C



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
using C = xref:#A[A];
----




[#D]
== D



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
using D = xref:#B[B]<short, long>;
----




[#E]
== E



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<typename T>
using E = xref:#B[B]<T, long>;
----




[#f0]
== f0



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f0(xref:#A[A]);
----










[#f1]
== f1



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f1(xref:#A[A] const);
----










[#f2]
== f2



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f2(xref:#A[A]&);
----










[#f3]
== f3



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f3(xref:#A[A] const&);
----










[#f4]
== f4



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f4(xref:#A[A]*);
----










[#f5]
== f5



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f5(xref:#A[A] const*);
----










[#f6]
== f6



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f6(xref:#A[A]**);
----










[#f7]
== f7



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f7(xref:#A[A] const**);
----










[#f8]
== f8



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
f8(xref:#A[A] const const**);
----










[#g0]
== g0



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
g0(xref:#C[C]);
----










[#g1]
== g1



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
g1(xref:#C[C] const);
----










[#g2]
== g2



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
g2(xref:#C[C]&);
----










[#g3]
== g3



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
g3(xref:#C[C] const&);
----










[#g4]
== g4



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
g4(xref:#C[C]*);
----










[#g5]
== g5



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
g5(xref:#C[C] const*);
----










[#g6]
== g6



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
g6(xref:#C[C]**);
----










[#g7]
== g7



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
g7(xref:#C[C] const**);
----










[#g8]
== g8



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
g8(xref:#C[C] const const**);
----










[#h0]
== h0



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
h0(xref:#B[B]<short, long>);
----










[#h1]
== h1



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
h1(xref:#B[B]<short, long> const);
----










[#h2]
== h2



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
h2(xref:#B[B]<short, long>&);
----










[#h3]
== h3



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
h3(xref:#B[B]<short, long> const&);
----










[#h4]
== h4



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
h4(xref:#B[B]<short, long>*);
----










[#h5]
== h5



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
h5(xref:#B[B]<short, long> const*);
----










[#h6]
== h6



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
h6(xref:#B[B]<short, long>**);
----










[#h7]
== h7



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
h7(xref:#B[B]<short, long> const**);
----










[#h8]
== h8



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
h8(xref:#B[B]<short, long> const const**);
----










[#i0]
== i0



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
i0(xref:#D[D]);
----










[#i1]
== i1



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
i1(xref:#D[D] const);
----










[#i2]
== i2



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
i2(xref:#D[D]&);
----










[#i3]
== i3



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
i3(xref:#D[D] const&);
----










[#i4]
== i4



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
i4(xref:#D[D]*);
----










[#i5]
== i5



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
i5(xref:#D[D] const*);
----










[#i6]
== i6



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
i6(xref:#D[D]**);
----










[#i7]
== i7



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
i7(xref:#D[D] const**);
----










[#i8]
== i8



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
i8(xref:#D[D] const const**);
----










[#j0]
== j0



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
j0(xref:#E[E]<short>);
----










[#j1]
== j1



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
j1(xref:#E[E]<short> const);
----










[#j2]
== j2



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
j2(xref:#E[E]<short>&);
----










[#j3]
== j3



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
j3(xref:#E[E]<short> const&);
----










[#j4]
== j4



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
j4(xref:#E[E]<short>*);
----










[#j5]
== j5



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
j5(xref:#E[E]<short> const*);
----










[#j6]
== j6



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
j6(xref:#E[E]<short>**);
----










[#j7]
== j7



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
j7(xref:#E[E]<short> const**);
----










[#j8]
== j8



=== Synopsis

Declared in `<type-resolution.cpp>`

[source,cpp,subs="verbatim,macros,-callouts"]
----
void
j8(xref:#E[E]<short> const const**);
----










[.small]#Created with https://www.mrdocs.com[MrDocs]#
