# npm install
# npx antora --fetch local-antora-playbook.yml
site:
  title: MrDocs
  url: https://cppalliance.github.io/mrdocs/
  start_page: mrdocs::index.adoc
  robots: allow
  keys:
    repo_url: 'https://github.com/cppalliance/mrdocs'

content:
  sources:
    - url: ..
      start_path: docs
      edit_url: 'https://github.com/cppalliance/mrdocs/edit/{refname}/{path}'

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: css/vendor/tabs.css
      contents: ./node_modules/@asciidoctor/tabs/dist/css/tabs.css
    - path: js/vendor/tabs.js
      contents: ./node_modules/@asciidoctor/tabs/dist/js/tabs.js
    - path: partials/footer-scripts.hbs
      contents: |
        <script id="site-script" src="{{{uiRootPath}}}/js/site.js" data-ui-root-path="{{{uiRootPath}}}"></script>
        <script async src="{{{uiRootPath}}}/js/vendor/highlight.js"></script>
        <script async src="{{{uiRootPath}}}/js/vendor/tabs.js"></script>
        {{#if env.SITE_SEARCH_PROVIDER}}
        {{> search-scripts}}
        {{/if}}
    - path: partials/head-styles.hbs
      contents: |
        <link rel="stylesheet" href="{{{uiRootPath}}}/css/site.css">
        <link rel="stylesheet" href="{{{uiRootPath}}}/css/vendor/tabs.css">

asciidoc:
  extensions:
    - '@asciidoctor/tabs'



antora:
  extensions:
    - require: '@antora/lunr-extension' # https://gitlab.com/antora/antora-lunr-extension
      index_latest_only: true

