# npm install
# npx antora --fetch local-antora-playbook.yml
site:
  title: MrDocs
  url: https://cppalliance.github.io/mrdocs/
  start_page: mrdocs::index.adoc
  robots: allow
  keys:
    repo_url: 'https://github.com/cppalliance/mrdocs'

content:
  sources:
    - url: ..
      start_path: docs
      edit_url: 'https://github.com/cppalliance/mrdocs/edit/{refname}/{path}'

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

antora:
  extensions:
    - require: '@antora/lunr-extension' # https://gitlab.com/antora/antora-lunr-extension
      index_latest_only: true

