/*
 * This file is generated automatically from the json file
 * `src/lib/Lib/ConfigOptions.json`. Do not edit this file
 * manually. Instead, edit the json file and run the script
 * `util/generate-config-info.py` to regenerate this file.
 */

#ifndef MRDOCS_PUBLIC_TOOLARGS_HPP
#define MRDOCS_PUBLIC_TOOLARGS_HPP

#include <mrdocs/Config.hpp>
#include <mrdocs/Config/ReferenceDirectories.hpp>
#include <llvm/Support/CommandLine.h>
#include <string>

namespace clang {
namespace mrdocs {

struct PublicToolArgs {

    /// Construct the PublicToolArgs object
    PublicToolArgs();

    /// Override settings with unnormalized values from the command line
    Expected<void>
    apply(
        PublicSettings& s,
        ReferenceDirectories const& dirs,
        char const** argv);

    //--------------------------------------------
    // Option Categories
    //--------------------------------------------
    /** Options that can only be provided via the command line

        The following options can be used to control the general behavior of Mr.Docs
        and can only be provided via the command line. These include options to
        specify inputs and the configuration file, which cannot be set on the
        configuration file itself.
     */
    llvm::cl::OptionCategory commandLineOptionsCat;

    /** Paths to the source code and output directories
     */
    llvm::cl::OptionCategory pathsCat;

    /** Filters to include or exclude files and symbols from the documentation
     */
    llvm::cl::OptionCategory filtersCat;

    /** Options to control how comments are parsed

        Mr.Docs extracts metadata from the comments in the source code. The
        following options control how comments are parsed.
     */
    llvm::cl::OptionCategory commentParsingCat;

    /** Metadata and C++ semantic constructs to extract

        MrDocs extracts metadata and C++ semantic constructs from the source code to
        create the documentation. Semantic constructs are patterns not directly
        represented in the source code AST but can be inferred from the corpus, such
        as SFINAE. The following options control the extraction of metadata and C++
        semantic constructs.
     */
    llvm::cl::OptionCategory metadataExtractionCat;

    /** C++ semantic constructs to extract

        Semantic constructs are patterns not directly represented in the source code
        AST but can be inferred from the corpus, such as SFINAE.
     */
    llvm::cl::OptionCategory semanticConstructsCat;

    /** Generators to create the documentation and their options
     */
    llvm::cl::OptionCategory generatorsCat;

    /** Options for building the source code

        When MrDocs is responsible to running the build scripts and generating the
        compilation database, these options are used to build the source code.
     */
    llvm::cl::OptionCategory buildOptionsCat;

    /** Warnings and progress messages
     */
    llvm::cl::OptionCategory warningsCat;

    /** Miscellaneous options
     */
    llvm::cl::OptionCategory miscellaneousCat;


    //--------------------------------------------
    // Command Line Options
    // 
    // Options that can only be provided via the command line
    //--------------------------------------------

    /** Configuration or compilation database files
    
        The inputs are configuration files or compilation database files that
        used to generate the documentation.
        
        When the input ends with `mrdocs.yml`, it is interpreted as a
        configuration file, the file is read and the options are used to
        generate the documentation as if it was provided to the `config`
        option.
        
        When the input ends with `compilation_database.json` or
        `CMakeLists.txt`, it is interpreted as a compilation database file,
        the file is read and the compiler flags are used to generate the
        documentation as if it was provided to the `compilation-database`
        option.
     */
    llvm::cl::list<std::string> cmdLineInputs;

    /** Mr.Docs configuration file
    
        The configuration file is a YAML file that contains the options used
        to generate the documentation.
        
        The configuration file is read and the options are used to generate
        the documentation.
        
        The configuration file can be used to specify the source code, the
        output directory, the compilation database, the generator, and the
        filters.
     */
    llvm::cl::opt<std::string> config;

    //--------------------------------------------
    // Paths
    // 
    // Paths to the source code and output directories
    //--------------------------------------------

    /** Path to the root directory of the source code
    
        Path to the root directory of the source code.
        
        This path is used as a default for input files and a base for relative
        paths formed from absolute paths.
        
        This should typically be the root directory of the git project, as
        relative paths formed from it can be used to create links to these
        source files in the repository.
        
        Templates use the `base-url` option to create links to the source
        code.
     */
    llvm::cl::opt<std::string> sourceRoot;

    /** Directory or file for generating output
    
        Multipage generators expect a directory.
        
        Single page generators expect a file or a directory where the file
        will be created.
        
        If the directory does not exist, it will be created.
     */
    llvm::cl::opt<std::string> output;

    /** Path to the compilation database
    
        Path to the compilation database or a build script to generate it.
        
        The compilation database is a JSON file that contains the compiler
        commands used to build the source code.
        
        The compilation database is used to extract the compiler flags and the
        source files used to build the source code and extract symbols.
        
        This option also accepts the path to a build script such as
        CMakeLists.txt to be used to generate the compilation database.
        
        In this case, Mr.Docs will look for CMake in `PATH` or in `CMAKE_ROOT`
        and run the script to generate the compilation database file.
     */
    llvm::cl::opt<std::string> compilationDatabase;

    //--------------------------------------------
    // Filters
    // 
    // Filters to include or exclude files and symbols from the documentation
    //--------------------------------------------

    /** Input directories to extract symbols from
    
        Input directories to extract.
        
        Only symbols defined in files in these directories are extracted.
        
        The paths are relative to the mrdocs configuration file.
     */
    llvm::cl::list<std::string> input;

    /** Recursively include files from "input" paths
    
        Recursively include files.
        
        When set to true, Mr.Docs includes files in subdirectories of the
        input directories.
        
        When set to false, Mr.Docs includes only the files in the input
        directories.
     */
    llvm::cl::opt<bool> recursive;

    /** File patterns to include
    
        File patterns to include.
        
        Only the files that match these patterns are extracted.
        
        The patterns are relative to the input directories.
     */
    llvm::cl::list<std::string> filePatterns;

    /** Input directories to exclude
    
        Symbols defined in files in these directories are not extracted even
        if they are in the list of include directories.
        
        When relative, the paths are relative to the directory of the mrdocs
        configuration file.
        
        For instance, "include/experimental" will exclude all files in the
        directory `<config-dir>/include/experimental`.
     */
    llvm::cl::list<std::string> exclude;

    /** File patterns to exclude
    
        File patterns to exclude.
        
        Files that match these patterns are not extracted even if they are in
        the list of include directories.
        
        The patterns are relative to the configuration file.
        
        A single * will match all files in the directory.
        
        Double ** will match all files in the directory and its
        subdirectories.
     */
    llvm::cl::list<std::string> excludePatterns;

    /** Symbol patterns to include
    
        If any patterns are defined here, only symbols that match one of these
        patterns are extracted.
        
        The patterns are applied to the fully qualified name of the symbol
        without any leading "::".
        
        A single "*" will match all symbols in the namespace.
        
        Double "**" will match all symbols in the namespace and its
        subnamespaces.
        
        The patterns also support "?" for any chars, "[<chars>]" for charsets,
        "[^<chars>]" for inverted charsets, and "{<glob>,...}" for
        alternatives.
     */
    llvm::cl::list<std::string> includeSymbols;

    /** Symbol patterns to exclude
    
        A symbol that matches one of these patterns is not extracted even if
        whitelisted by "include-symbols".
        
        See the documentation for "include-symbols" for the pattern syntax.
     */
    llvm::cl::list<std::string> excludeSymbols;

    /** Exposition only symbols rendered as "see-below".
    
        Symbols that match one of these filters are tagged as "see-below" in
        the documentation, and so do symbols in scopes tagged as "see-below".
        
        This option is used to remove details about symbols that are
        considered part of the private API of the project but the user might
        need to interact with.
        
        In the documentation page for this symbol, the symbol is exposition
        only: the synopsis of the implementation is rendered as "see-below"
        and members of scopes (such as a namespace or record) are not listed.
        
        The rest of the documentation is rendered as usual to explain the
        symbol.
        
        See the documentation for "include-symbol" for the pattern syntax.
     */
    llvm::cl::list<std::string> seeBelow;

    /** Symbols rendered as "implementation-defined"
    
        Symbols that match one of these filters are tagged as
        "implementation-defined" in the documentation, and so do symbols in
        scopes tagged as "implementation-defined".
        
        This option is used to exclude symbols from the documentation that are
        considered part of the private API of the project.
        
        An "implementation-defined" symbol has no documentation page in the
        output.
        
        If any other symbol refers to it, the reference is rendered as
        "implementation-defined".
        
        See the documentation for "include-symbol" for the pattern syntax.
     */
    llvm::cl::list<std::string> implementationDefined;

    //--------------------------------------------
    // Comment Parsing
    // 
    // Options to control how comments are parsed
    //--------------------------------------------

    /** Use the first line of the comment as the brief
    
        When set to `true`, Mr.Docs uses the first line (until the first dot,
        question mark, or exclamation mark) of the comment as the brief of the
        symbol.
        
        When set to `false`, a explicit @brief command is required.
     */
    llvm::cl::opt<bool> autoBrief;

    /** Automatically find non-member functions
    
        When set to `true`, Mr.Docs automatically finds non-member functions
        that are related to the current class.
     */
    llvm::cl::opt<bool> autoRelates;

    /** Automatically provide missing documentation for special functions
        and trivial metadata
    
        When set to `true`, Mr.Docs automatically provides documentation for
        special functions, such as constructors, destructors, and operators.
        
        It also provides documentation for missing documentation metadata,
        such as known types.
     */
    llvm::cl::opt<bool> autoFunctionMetadata;

    //--------------------------------------------
    // Metadata Extraction
    // 
    // Metadata and C++ semantic constructs to extract
    //--------------------------------------------

    /** Extract all symbols
    
        When set to `true`, MrDocs extracts all symbols from the source code,
        even if no documentation is provided.
        
        MrDocs can only identify whether a symbol is ultimated documented
        after extracting information from all translation units.
        
        For this reason, when this option is set to `false`, it's still
        recommendable to provide file and symbol filters so that only the
        desired symbols are traversed and stored by MrDocs.
     */
    llvm::cl::opt<bool> extractAll;

    /** Extraction policy for private class members
    
        Determine whether private class members should be extracted
     */
    llvm::cl::opt<bool> extractPrivate;

    /** Extraction policy for private virtual methods of a class
    
        Determine whether private virtual methods of a class should be
        extracted
     */
    llvm::cl::opt<bool> extractPrivateVirtual;

    /** Extraction policy for private base classes
    
        Determine whether private base classes should be extracted
     */
    llvm::cl::opt<bool> extractPrivateBases;

    /** Extraction policy for static members of a file
    
        Determine whether static members of a file should be extracted.
        
        This option does not refer to static members of a class.
     */
    llvm::cl::opt<bool> extractStatic;

    /** Extraction policy for records defined locally in source files
    
        Determine whether records only defined locally in source files should
        be extracted.
     */
    llvm::cl::opt<bool> extractLocalClasses;

    /** Extraction policy for anonymous namespaces
    
        Determine whether symbols in anonymous namespaces should be extracted.
     */
    llvm::cl::opt<bool> extractAnonymousNamespaces;

    /** Extraction policy for empty namespaces
    
        Determine whether empty namespaces without documentation should be
        extracted.
     */
    llvm::cl::opt<bool> extractEmptyNamespaces;

    /** Determine how derived classes inherit base members
    
        Determine how derived classes inherit members of base classes.
        
        When set to `never`, derived classes do not inherit members of base
        classes and only the relationship is stored.
        
        When set to `reference`, derived classes list members of base classes
        but references are still linked to the base class.
        
        When set to `copy-dependencies`, a reference is created by default and
        a copy is created when the base class is a dependency.
        
        When set to `copy-all`, a copy is created for each base symbol as if
        it was declared in the derived class.
        
        If the base class is a dependency, the extraction mode is copied from
        the new parent.
     */
    llvm::cl::opt<std::string> inheritBaseMembers;

    /** Implicit template specializations used as base classes are
        extracted as dependencies
    
        When set to `true`, MrDocs extracts implicit template specializations
        used as base classes as dependencies.
        
        This allows MrDocs to extract metadata that can later be used to
        determine the members of the derived class, as specified by the
        `inherit-base-members` option.
     */
    llvm::cl::opt<bool> extractImplicitSpecializations;

    /** Extraction policy for friend functions and classes
    
        Determine whether friend functions and classes should be extracted.
        
        When set to `true`, MrDocs extracts friend functions and classes.
        
        When set to `false`, friend functions and classes are not extracted.
     */
    llvm::cl::opt<bool> extractFriends;

    /** Sort the members of a record
    
        When set to `true`, sort the members of a record by the criterion
        determined in the `sort-members-by` option.
        
        When set to `false`, the members are included in the declaration order
        they are extracted.
     */
    llvm::cl::opt<bool> sortMembers;

    /** Determine how members of a record are sorted
    
        If `sort-members` is set to `true`, determine how members of a record
        are sorted.
        
        When set to `name`, members are sorted by name.
        
        When set to `location`, members are sorted by their primary location
        in the source code, considering the short name of the path and the
        location in the file.
     */
    llvm::cl::opt<std::string> sortMembersBy;

    /** Determine how members of a namespace are sorted
    
        Although members of namespaces are always sorted, determine how
        members of a namespace are sorted.
        
        When set to `name`, members are sorted by name.
        
        When set to `location`, members are sorted by their primary location
        in the source code, considering the short name of the path and the
        location in the file.
     */
    llvm::cl::opt<std::string> sortNamespaceMembersBy;

    /** Sort constructors first
    
        When set to `true`, constructors are sorted first in the list of
        members of a record.
     */
    llvm::cl::opt<bool> sortMembersCtors1St;

    /** Sort destructors first
    
        When set to `true`, destructors are sorted first in the list of
        members of a record.
     */
    llvm::cl::opt<bool> sortMembersDtors1St;

    /** Sort assignment operators first
    
        When set to `true`, assignment operators are sorted first in the list
        of members of a record.
     */
    llvm::cl::opt<bool> sortMembersAssignment1St;

    /** Sort conversion operators last
    
        When set to `true`, conversion operators are sorted last in the list
        of members of a record or namespace.
     */
    llvm::cl::opt<bool> sortMembersConversionLast;

    /** Sort relational operators last
    
        When set to `true`, relational operators are sorted last in the list
        of members of a record or namespace.
     */
    llvm::cl::opt<bool> sortMembersRelationalLast;

    //--------------------------------------------
    // Semantic Constructs
    // 
    // C++ semantic constructs to extract
    //--------------------------------------------

    /** Detect and reduce SFINAE expressions
    
        When set to true, MrDocs detects SFINAE expressions in the source code
        and extracts them as part of the documentation.
        
        Expressions such as `std::enable_if<...>` are detected, removed, and
        documented as a requirement.
        
        MrDocs uses an algorithm that extracts SFINAE infomation from types by
        identifying inspecting the primary template and specializations to
        detect the result type and the controlling expressions in a
        specialization.
     */
    llvm::cl::opt<bool> sfinae;

    /** Detect and group function overloads
    
        When set to `true`, MrDocs detects function overloads and groups them
        as a single symbol type.
        
        The documentation for this new symbol comes from the union of
        non-ambiguous metadata from the functions.
     */
    llvm::cl::opt<bool> overloads;

    //--------------------------------------------
    // Generators
    // 
    // Generators to create the documentation and their options
    //--------------------------------------------

    /** Generator used to create the documentation
    
        The generator is responsible for creating the documentation from the
        extracted symbols.
        
        The generator uses the extracted symbols and the templates to create
        the documentation.
        
        The generator can create different types of documentation such as
        HTML, XML, and AsciiDoc.
     */
    llvm::cl::opt<std::string> generator;

    /** Generate a multipage documentation
    
        Generates a multipage documentation.
        
        The output directory must be a directory.
        
        This option acts as a hint to the generator to create a multipage
        documentation.
        
        Whether the hint is followed or not depends on the generator.
     */
    llvm::cl::opt<bool> multipage;

    /** Base URL for links to source code
    
        Base URL for links to source code.
        
        The base URL is used to create links to the source code in the
        documentation.
        
        The base URL is combined with the path to the source file to create
        the link.
     */
    llvm::cl::opt<std::string> baseUrl;

    /** Path to the Addons directory
    
        Path to the Addons directory.
        
        The Addons directory contains the template files used by generators to
        create the documentation.
        
        When a custom Addons directory is not specified, the default templates
        are used.
        
        The default templates are located at the `share/mrdocs/addons`
        directory of the MrDocs installation.
        
        Users can create custom templates by copying the default templates to
        a custom directory and specifying the custom directory using this
        option.
     */
    llvm::cl::opt<std::string> addons;

    /** Path for the tagfile
    
        Specifies the full path (filename) where the generated tagfile should
        be saved.
        
        If left empty, no tagfile will be generated.
     */
    llvm::cl::opt<std::string> tagfile;

    /** Use legible names
    
        Use legible names for ids in the documentation.
        
        When set to true, MrDocs uses legible names for symbols in the
        documentation.
        
        These are symbols that are legible but still safe for URLs.
        
        When the option is set to false, MrDocs uses a hash of the symbol ID.
     */
    llvm::cl::opt<bool> legibleNames;

    /** Output an embeddable document
    
        Output an embeddable document, which excludes the header, the footer,
        and everything outside the body of the document.
        
        This option is useful for producing documents that can be inserted
        into an external template.
     */
    llvm::cl::opt<bool> embedded;

    /** Show namespace pages in the documentation
    
        When set to true, MrDocs creates a page for each namespace in the
        documentation.
     */
    llvm::cl::opt<bool> showNamespaces;

    /** Use the global namespace page as an index for all symbols
    
        When set to true, the page for the global namespace will recursively
        list all symbols in the documentation, not just those in the global
        namespace.
        
        This makes the global namespace page act as an index for the entire
        project.
     */
    llvm::cl::opt<bool> globalNamespaceIndex;

    //--------------------------------------------
    // Build options
    // 
    // Options for building the source code
    //--------------------------------------------

    /** CMake arguments when generating the compilation database from
        CMakeLists.txt
    
        When the compilation-database option is a CMakeLists.txt file, these
        arguments are passed to the cmake command to generate the
        compilation_database.json.
     */
    llvm::cl::opt<std::string> cmake;

    /** Additional defines passed to the compiler
    
        Additional defines passed to the compiler when building the source
        code.
        
        These defines are added to the compilation database regardless of the
        strategy to generate it.
     */
    llvm::cl::list<std::string> defines;

    /** Use the system C++ standard library
    
        To achieve reproducible results, MrDocs bundles the LibC++ headers.
        
        To use the C++ standard library available in the system instead, set
        this option to true.
     */
    llvm::cl::opt<bool> useSystemStdlib;

    /** C++ Standard Library include paths
    
        When `use-system-stdlib` is disabled, the C++ standard library headers
        are available in these paths.
     */
    llvm::cl::list<std::string> stdlibIncludes;

    /** Use the system C standard library
    
        To achieve reproducible results, MrDocs bundles the LibC headers with
        its definitions.
        
        To use the C standard library available in the system instead, set
        this option to true.
     */
    llvm::cl::opt<bool> useSystemLibc;

    /** Standard Library include paths
    
        When `use-system-libc` is disabled, the C standard library headers are
        available in these paths.
     */
    llvm::cl::list<std::string> libcIncludes;

    /** System include paths
    
        System include paths.
        
        These paths are used to add directories to the system include search
        path.
        
        The system include search path is used to search for system headers.
        
        The system headers are headers that are provided by the system and are
        not part of the project.
        
        The system headers are used to provide the standard library headers
        and other system headers.
        
        The system headers are not part of the project and are not checked for
        warnings and errors.
     */
    llvm::cl::list<std::string> systemIncludes;

    /** Include paths
    
        Include paths.
        
        These paths are used to add directories to the include search path.
        
        The include search path is used to search for headers.
        
        The headers are used to provide declarations and definitions of
        symbols.
        
        The headers are part of the project and are checked for warnings and
        errors.
     */
    llvm::cl::list<std::string> includes;

    //--------------------------------------------
    // Warnings
    // 
    // Warnings and progress messages
    //--------------------------------------------

    /** Verbose output
    
        Verbose output.
        
        When set to true, MrDocs outputs additional information during the
        generation of the documentation.
     */
    llvm::cl::opt<bool> verbose;

    /** The minimum reporting level
    
        The reporting level determines the amount of information displayed
        during the generation of the documentation.
        
        The value `-1` delegates the decision to the `log-level` option.
     */
    llvm::cl::opt<unsigned> report;

    /** The minimum reporting level
    
        The reporting level determines the amount of information displayed
        during the generation of the documentation.
     */
    llvm::cl::opt<std::string> logLevel;

    /** Enable warning messages
    
        When set to `true`, MrDocs outputs warning messages during the
        generation of the documentation.
        
        It is usually recommended to enable warnings while writing the
        documentation.
     */
    llvm::cl::opt<bool> warnings;

    /** Warn if symbols are not documented
    
        When set to `true`, MrDocs outputs a warning message if a symbol that
        passes all filters is not documented.
     */
    llvm::cl::opt<bool> warnIfUndocumented;

    /** Warn if documentation has errors
    
        When set to `true`, MrDocs outputs a warning message if the
        documentation of a symbol has errors such as duplicate parameters and
        parameters that don't exist.
     */
    llvm::cl::opt<bool> warnIfDocError;

    /** Warn if parameters are not documented
    
        When set to `true`, MrDocs outputs a warning message if a named
        function parameter is not documented.
     */
    llvm::cl::opt<bool> warnNoParamdoc;

    /** Warn if documented functions have unnamed parameters
    
        When set to `true`, MrDocs outputs a warning message if a documented
        function has a parameter that is not named.
     */
    llvm::cl::opt<bool> warnUnnamedParam;

    /** Warn if enum values are not documented
    
        When set to `true`, MrDocs outputs a warning message if an enum value
        is not documented.
     */
    llvm::cl::opt<bool> warnIfUndocEnumVal;

    /** Warn if a documentation reference is broken
    
        When set to `true`, MrDocs outputs a warning message if a reference in
        the documentation is broken.
     */
    llvm::cl::opt<bool> warnBrokenRef;

    /** Treat warnings as errors
    
        When set to `true`, MrDocs treats warnings as errors and stops the
        generation of the documentation.
     */
    llvm::cl::opt<bool> warnAsError;

    //--------------------------------------------
    // Miscellaneous
    // 
    // Miscellaneous options
    //--------------------------------------------

    /** Number of threads to use
    
        The desired level of concurrency: 0 for hardware-suggested.
     */
    llvm::cl::opt<unsigned> concurrency;

    /** Continue if files are not mapped correctly
    
        When set to true, MrDocs continues to generate the documentation even
        if some files are not mapped correctly.
        
        Files are not mapped correctly when the source file is not found or
        the compilation database does not contain the compiler flags for the
        source file.
     */
    llvm::cl::opt<bool> ignoreMapErrors;

    /** Whether AST visitation failures should not stop the program
    
        When set to true, MrDocs continues to generate the documentation even
        if there are AST visitation failures.
        
        AST visitation failures occur when the source code contains constructs
        that are not supported by MrDocs.
     */
    llvm::cl::opt<bool> ignoreFailures;

    /** Visit all options
     */
    template <class F>
    void
    visit(F&& f)
    {
        std::forward<F>(f)("cmd-line-inputs", cmdLineInputs);
        std::forward<F>(f)("config", config);
        std::forward<F>(f)("source-root", sourceRoot);
        std::forward<F>(f)("output", output);
        std::forward<F>(f)("compilation-database", compilationDatabase);
        std::forward<F>(f)("input", input);
        std::forward<F>(f)("recursive", recursive);
        std::forward<F>(f)("file-patterns", filePatterns);
        std::forward<F>(f)("exclude", exclude);
        std::forward<F>(f)("exclude-patterns", excludePatterns);
        std::forward<F>(f)("include-symbols", includeSymbols);
        std::forward<F>(f)("exclude-symbols", excludeSymbols);
        std::forward<F>(f)("see-below", seeBelow);
        std::forward<F>(f)("implementation-defined", implementationDefined);
        std::forward<F>(f)("auto-brief", autoBrief);
        std::forward<F>(f)("auto-relates", autoRelates);
        std::forward<F>(f)("auto-function-metadata", autoFunctionMetadata);
        std::forward<F>(f)("extract-all", extractAll);
        std::forward<F>(f)("extract-private", extractPrivate);
        std::forward<F>(f)("extract-private-virtual", extractPrivateVirtual);
        std::forward<F>(f)("extract-private-bases", extractPrivateBases);
        std::forward<F>(f)("extract-static", extractStatic);
        std::forward<F>(f)("extract-local-classes", extractLocalClasses);
        std::forward<F>(f)("extract-anonymous-namespaces", extractAnonymousNamespaces);
        std::forward<F>(f)("extract-empty-namespaces", extractEmptyNamespaces);
        std::forward<F>(f)("inherit-base-members", inheritBaseMembers);
        std::forward<F>(f)("extract-implicit-specializations", extractImplicitSpecializations);
        std::forward<F>(f)("extract-friends", extractFriends);
        std::forward<F>(f)("sort-members", sortMembers);
        std::forward<F>(f)("sort-members-by", sortMembersBy);
        std::forward<F>(f)("sort-namespace-members-by", sortNamespaceMembersBy);
        std::forward<F>(f)("sort-members-ctors-1st", sortMembersCtors1St);
        std::forward<F>(f)("sort-members-dtors-1st", sortMembersDtors1St);
        std::forward<F>(f)("sort-members-assignment-1st", sortMembersAssignment1St);
        std::forward<F>(f)("sort-members-conversion-last", sortMembersConversionLast);
        std::forward<F>(f)("sort-members-relational-last", sortMembersRelationalLast);
        std::forward<F>(f)("sfinae", sfinae);
        std::forward<F>(f)("overloads", overloads);
        std::forward<F>(f)("generator", generator);
        std::forward<F>(f)("multipage", multipage);
        std::forward<F>(f)("base-url", baseUrl);
        std::forward<F>(f)("addons", addons);
        std::forward<F>(f)("tagfile", tagfile);
        std::forward<F>(f)("legible-names", legibleNames);
        std::forward<F>(f)("embedded", embedded);
        std::forward<F>(f)("show-namespaces", showNamespaces);
        std::forward<F>(f)("global-namespace-index", globalNamespaceIndex);
        std::forward<F>(f)("cmake", cmake);
        std::forward<F>(f)("defines", defines);
        std::forward<F>(f)("use-system-stdlib", useSystemStdlib);
        std::forward<F>(f)("stdlib-includes", stdlibIncludes);
        std::forward<F>(f)("use-system-libc", useSystemLibc);
        std::forward<F>(f)("libc-includes", libcIncludes);
        std::forward<F>(f)("system-includes", systemIncludes);
        std::forward<F>(f)("includes", includes);
        std::forward<F>(f)("verbose", verbose);
        std::forward<F>(f)("report", report);
        std::forward<F>(f)("log-level", logLevel);
        std::forward<F>(f)("warnings", warnings);
        std::forward<F>(f)("warn-if-undocumented", warnIfUndocumented);
        std::forward<F>(f)("warn-if-doc-error", warnIfDocError);
        std::forward<F>(f)("warn-no-paramdoc", warnNoParamdoc);
        std::forward<F>(f)("warn-unnamed-param", warnUnnamedParam);
        std::forward<F>(f)("warn-if-undoc-enum-val", warnIfUndocEnumVal);
        std::forward<F>(f)("warn-broken-ref", warnBrokenRef);
        std::forward<F>(f)("warn-as-error", warnAsError);
        std::forward<F>(f)("concurrency", concurrency);
        std::forward<F>(f)("ignore-map-errors", ignoreMapErrors);
        std::forward<F>(f)("ignore-failures", ignoreFailures);
    }

}; // struct PublicToolArgs

} // namespace mrdocs
} // namespace clang

#endif // MRDOCS_PUBLIC_TOOLARGS_HPP
